---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: 适用于 SQL Server 的插件可与 Windows 主机上的 Microsoft SQL Server 以及存储系统上的 NetApp Snapshot 副本技术集成。要使用适用于 SQL Server 的插件，请使用 SnapCenter 界面。 
---
= 适用于 Microsoft SQL Server 的 SnapCenter 插件功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于 SQL Server 的插件可与 Windows 主机上的 Microsoft SQL Server 以及存储系统上的 NetApp Snapshot 副本技术集成。要使用适用于 SQL Server 的插件，请使用 SnapCenter 界面。

适用于 SQL Server 的插件包括以下主要功能：

* * 由 SnapCenter 提供支持的统一图形用户界面 *
+
SnapCenter 界面为您提供了跨插件和环境的标准化和一致性。通过 SnapCenter 界面，您可以跨插件完成一致的备份和还原过程，使用集中式报告，使用信息板概览视图，设置基于角色的访问控制（ Role-Based Access Control ， RBAC ）以及监控所有插件中的作业。SnapCenter 还提供集中式计划和策略管理，以支持备份和克隆操作。

* * 自动化中央管理 *
+
您可以计划例行 SQL Server 备份，配置基于策略的备份保留以及设置时间点和最新还原操作。您还可以通过配置 SnapCenter 以发送电子邮件警报来主动监控 SQL Server 环境。

* * 无中断 NetApp Snapshot 副本技术 *
+
适用于 SQL Server 的插件将 NetApp Snapshot 副本技术与适用于 Microsoft Windows 的 NetApp SnapCenter 插件结合使用。这样，您就可以在几秒钟内备份数据库并快速还原它们，而无需使 SQL Server 脱机。Snapshot 副本占用的存储空间极少。



除了这些主要功能之外，适用于 SQL Server 的插件还具有以下优势：

* 支持备份，还原，克隆和验证工作流
* 支持 RBAC 的安全性和集中式角色委派
* 使用 NetApp FlexClone 技术为生产数据库创建节省空间的时间点副本，以供测试或数据提取
+
持有克隆的存储系统需要 FlexClone 许可证。

* 无中断自动备份验证
* 能够在多个服务器上同时运行多个备份
* PowerShell cmdlet ，用于编写备份，验证，还原和克隆操作的脚本
* 在 SQL Server 中支持 AlwaysOn 可用性组（ AGS ），以加快 AG 设置，备份和还原操作
* 内存数据库和缓冲池扩展（ BPE ）作为 SQL Server 2014 的一部分
* 支持备份 LUN 和虚拟机磁盘（ VMDK ）
* 支持物理和虚拟化基础架构
* 支持 iSCSI ，光纤通道， FCoE ，原始设备映射（ RDM ）以及基于 NFS 和 VMFS 的 VMDK
+

NOTE: NAS 卷在 Storage Virtual Machine （ SVM ）中应具有默认导出策略。

* 支持 SQL Server 独立数据库中的文件流和文件组。

