---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: 使用 SnapCenter 备份 SQL Server 系统和用户数据库需要选择资源类型，例如数据库， SQL Server 实例和可用性组 \ （ ag\ ）。Snapshot 副本技术用于为资源所在的卷创建联机只读副本。 
---
= 支持的备份类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 SnapCenter 备份 SQL Server 系统和用户数据库需要选择资源类型，例如数据库， SQL Server 实例和可用性组（ Availability Group ， AG ）。Snapshot 副本技术用于为资源所在的卷创建联机只读副本。

您可以选择仅复制选项以指定 SQL Server 不截断事务日志。如果同时使用其他备份应用程序管理 SQL Server ，则应使用此选项。保持事务日志完好无损可使任何备份应用程序恢复系统数据库。纯副本备份与计划的备份顺序无关，它们不会影响数据库的备份和还原过程。

|===
| 备份类型 | Description | 具有备份类型的仅复制选项 


 a| 
完整备份和日志备份
 a| 
备份系统数据库并截断事务日志。

SQL Server 通过删除已提交到数据库的条目来截断事务日志。

完整备份完成后，此选项将创建一个事务日志以捕获事务信息。通常，您应选择此选项。但是，如果备份时间较短，您可以选择不在执行完整备份的情况下运行事务日志备份。

您不能为主数据库和 msdb 系统数据库创建日志备份。但是，您可以为型号系统数据库创建日志备份。
 a| 
备份系统数据库文件和事务日志，而不截断日志。

纯副本备份不能用作差异基础或差异备份，也不会影响差异基础。还原纯副本完整备份与还原任何其他完整备份相同。



 a| 
完整数据库备份
 a| 
备份系统数据库文件。

您可以为主数据库，模型数据库和 msdb 系统数据库创建完整的数据库备份。
 a| 
备份系统数据库文件。



 a| 
事务日志备份
 a| 
备份截断的事务日志，仅复制自备份最新事务日志以来提交的事务。

如果您计划频繁执行事务日志备份以及完整数据库备份，则可以选择粒度恢复点。
 a| 
备份事务日志而不截断它们。

此备份类型不会影响常规日志备份的顺序。仅复制日志备份对于执行联机还原操作非常有用。

|===