---
permalink: protect-scsql/quick_start_to_install_snapcenter_plug-in_for_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: 提供有关安装 SnapCenter 服务器和适用于 Microsoft SQL Server 的 SnapCenter 插件的说明。 
---
= 快速开始安装适用于 SQL Server 的 SnapCenter 插件
:icons: font
:imagesdir: ../media/


[role="lead"]
提供了一组有关安装 SnapCenter 服务器和适用于 Microsoft SQL Server 的 SnapCenter 插件的简要安装说明。



== 准备安装

* 域和工作组要求 *

SnapCenter 服务器可以安装在域或工作组中的系统上。

如果您使用的是 Active Directory 域，则应使用具有本地管理员权限的域用户。域用户应是 Windows 主机上本地管理员组的成员。

如果您使用的是工作组，则应使用具有本地管理员权限的本地帐户。

* 许可证要求 *

您安装的许可证类型取决于您的环境。

|===
| 许可证 | 必要时 


 a| 
基于 SnapCenter 标准控制器
 a| 
对于 FAS 或 AFF 存储控制器为必需项

SnapCenter 标准版许可证是一种基于控制器的许可证，作为高级包的一部分提供。如果您拥有 SnapManager 套件许可证，则还可以获得 SnapCenter 标准许可证授权。如果要在 FAS 或 AFF 存储中试用 SnapCenter ，您可以联系销售代表以获取超值包评估许可证。



 a| 
基于 SnapCenter 标准容量
 a| 
ONTAP Select 和 Cloud Volumes ONTAP 必需

如果您是 Cloud Volumes ONTAP 或 ONTAP Select 客户，则需要根据 SnapCenter 管理的数据购买基于每 TB 容量的许可证。默认情况下， SnapCenter 会提供一个内置 90 天 100 TB SnapCenter 标准容量试用许可证。有关其他详细信息，请联系销售代表。



 a| 
SnapMirror 或 SnapVault
 a| 
ONTAP

如果在 SnapCenter 中启用了复制，则需要 SnapMirror 或 SnapVault 许可证。



 a| 
其他许可证（可选）
 a| 
请参见 link:../install/concept_snapcenter_licenses.html["SnapCenter 许可证"^]。



 a| 
SnapCenter 标准许可证（可选）
 a| 
二级目标


NOTE: 建议（但不要求）将 SnapCenter 标准版许可证添加到二级目标。如果二级目标上未启用 SnapCenter 标准许可证，则在执行故障转移操作后，您将无法使用 SnapCenter 备份二级目标上的资源。但是，要执行克隆和验证操作，二级目标需要 FlexClone 许可证。

|===
* 其他要求 *

有关 ONTAP 和应用程序插件的最低要求，请参见 https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["互操作性表工具"^]

|===
| 主机 | 最低要求 


 a| 
操作系统（ 64 位）
 a| 
请参见 https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["互操作性表工具"^]



 a| 
CPU
 a| 
* 服务器主机： 4 个核心
* 插件主机： 1 个核心




 a| 
RAM
 a| 
* 服务器主机： 8 GB
* 插件主机： 1 GB




 a| 
硬盘驱动器空间
 a| 
服务器主机：

* 4 GB ，用于 SnapCenter 服务器软件和日志
* 6 GB 用于 SnapCenter 存储库
* 每个插件主机： 2 GB 用于插件安装和日志，只有在专用主机上安装了插件时才需要此空间。




 a| 
第三方库
 a| 
SnapCenter 服务器主机和插件主机上需要：

* Microsoft .NET Framework 4.5.2 或更高版本
* Windows Management Framework （ WMF ） 4.0 或更高版本
* PowerShell 4.0 或更高版本




 a| 
浏览器
 a| 
Chrome ， Internet Explorer 和 Microsoft Edge

|===
|===
| 端口类型 | 默认端口 


 a| 
SnapCenter 端口
 a| 
8146 （ HTTPS ），双向，可自定义，如 URL ： _\https://server:8146_



 a| 
SnapCenter SMCore 通信端口
 a| 
8145 （ HTTPS ），双向，可自定义



 a| 
存储库数据库
 a| 
3306 （ HTTPS ），双向



 a| 
Windows 插件主机
 a| 
135 ， 445 （ TCP ）

除了端口 135 和 445 之外， Microsoft 指定的动态端口范围也应处于打开状态。远程安装操作使用 Windows Management Instrumentation （ WMI ）服务，该服务会动态搜索此端口范围。

有关支持的动态端口范围的信息，请参见 https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Windows 的服务概述和网络端口要求"^]。



 a| 
适用于 Windows 的 SnapCenter 插件
 a| 
8145 （ HTTPS ），双向，可自定义



 a| 
ONTAP 集群或 SVM 通信端口
 a| 
443 （ HTTPS ），双向； 80 （ HTTP ），双向

此端口用于在 SnapCenter 服务器主机，插件主机和 SVM 或 ONTAP 集群之间进行通信。

|===
* 适用于 Microsoft SQL Server 的 SnapCenter 插件要求 *

您应拥有一个具有本地管理员权限的用户，并在远程主机上拥有本地登录权限。如果您管理集群节点，则需要一个对集群中所有节点具有管理权限的用户。

您应具有一个对 SQL Server 具有 sysadmin 权限的用户。此插件使用 Microsoft VDI Framework ，需要 sysadmin 访问权限。

如果您使用的是适用于 Microsoft SQL Server 的 SnapManager ，并且希望将数据从适用于 Microsoft SQL Server 的 SnapManager 导入到 SnapCenter ，请参见 link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["导入归档备份"^]



== 安装 SnapCenter 服务器

* 下载并安装 SnapCenter Server*

* 步骤 *

. 从下载 SnapCenter 服务器安装包 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 支持站点"^] 然后双击该 exe 。
+
启动安装后，系统将执行所有预检，如果不满足最低要求，则会显示相应的错误或警告消息。您可以忽略警告消息并继续安装；但是，错误应予以修复。

. 查看安装 SnapCenter 服务器所需的预填充值，并根据需要进行修改。
+
您不必指定 MySQL Server 存储库数据库的密码。在 SnapCenter 服务器安装期间，系统会自动生成密码。

+

NOTE: 自定义安装路径不支持特殊字符 "%" 。如果在路径中包含 "%" ，则安装将失败。

. 单击 * 立即安装 * 。


* 登录到 SnapCenter *

* 步骤 *

. 从主机桌面上的快捷方式或安装提供的 URL 启动 SnapCenter （对于安装 SnapCenter 服务器的默认端口 8146 ，为 _\https://server:8146_ ）。
. 输入凭据。
+
对于内置的域管理员用户名格式，请使用： _netbios\< 用户名 >_ 或 _ < 用户名 >@ < 域 >_ 或 _ < 域 FQDN>\ < 用户名 >_ 。

+
对于内置的本地管理员用户名格式，请使用 _ < 用户名 >_ 。

. 单击 * 登录 * 。


* 添加基于 SnapCenter 标准控制器的许可证 *

* 步骤 *

. 使用 ONTAP 命令行登录到控制器并输入：
+
`ssystem license add -license-code <license_key>`

. 验证许可证：
+
`许可证显示`



* 添加基于 SnapCenter 容量的许可证 *

* 步骤 *

. 在 SnapCenter 图形用户界面左窗格中，单击 * 设置 > 软件 * ，然后在许可证部分中单击 * 。
. 选择以下两种获取许可证的方法之一：
+
** 输入 NetApp 支持站点登录凭据以导入许可证。
** 浏览到 NetApp 许可证文件的位置，然后单击 * 打开 * 。


. 在向导的 * 通知 * 页面上，使用默认容量阈值 90% 。
. 单击 * 完成 * 。


* 设置存储系统连接 *

* 步骤 *

. 在左窗格中，单击 * 存储系统 > 新建 * 。
. 在添加存储系统页面中，执行以下操作：
+
.. 输入存储系统的名称或 IP 地址。
.. 输入用于访问存储系统的凭据。
.. 选中相应复选框以启用事件管理系统（ EMS ）和 AutoSupport 。


. 如果要修改分配给平台，协议，端口和超时的默认值，请单击 * 更多选项 * 。
. 单击 * 提交 * 。




== 安装适用于 Microsoft SQL Server 的插件

* 设置运行身份凭据以安装适用于 Microsoft SQL Server* 的插件

* 步骤 *

. 在左窗格中，单击 * 设置 > 凭据 > 新建 * 。
. 输入凭据。
+
对于内置的域管理员用户名格式，请使用： _netbios\< 用户名 >_ 或 _ < 用户名 >@ < 域 >_ 或 _ < 域 FQDN>\ < 用户名 >_ 。

+
对于内置的本地管理员用户名格式，请使用 _ < 用户名 >_ 。



* 添加主机并安装适用于 Microsoft SQL Server* 的插件

* 步骤 *

. 在 SnapCenter 图形用户界面左窗格中，单击 * 主机 > 受管主机 > 添加 * 。
. 在向导的主机页面上，执行以下操作：
+
.. Host Type ：选择 Windows 主机类型。
.. 主机名：使用 SQL 主机或指定专用 Windows 主机的 FQDN 。
.. Credentials ：选择您创建的主机的有效凭据名称或创建新凭据。


. 在选择要安装的插件部分中，选择 * Microsoft SQL Server* 。
. 单击 * 更多选项 * 以指定以下详细信息：
+
.. port ：保留默认端口号或指定端口号。
.. 安装路径：默认路径为 _C ： \Program Files\NetApp\SnapCenter_ 。您可以选择自定义路径。
.. 添加集群中的所有主机：如果您在 WSFC 中使用 SQL ，请选中此复选框。
.. 跳过安装前检查：如果您已手动安装插件或不想验证主机是否满足插件安装要求，请选中此复选框。


. 单击 * 提交 * 。

