---
permalink: protect-scsql/quick-start-to-prepare-for-snapcenter-plug-in-install-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: 提供有关准备安装SnapCenter 服务器和适用于Microsoft SQL Server的SnapCenter 插件的说明。 
---
= 准备SnapCenter 服务器和插件安装
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
提供了一组有关安装SnapCenter 服务器和适用于Microsoft SQL Server的SnapCenter 插件的精简准备说明。



== 域和工作组要求

SnapCenter 服务器可以安装在域或工作组中的系统上。

如果您使用的是 Active Directory 域，则应使用具有本地管理员权限的域用户。域用户应是 Windows 主机上本地管理员组的成员。

如果您使用的是工作组，则应使用具有本地管理员权限的本地帐户。



== 许可证要求

您安装的许可证类型取决于您的环境。

[cols="1,3"]
|===
| 许可证 | 必要时 


 a| 
基于 SnapCenter 标准控制器
 a| 
对于 FAS 或 AFF 存储控制器为必需项

SnapCenter 标准版许可证是一种基于控制器的许可证，作为高级包的一部分提供。如果您拥有 SnapManager 套件许可证，则还可以获得 SnapCenter 标准许可证授权。如果要在 FAS 或 AFF 存储中试用 SnapCenter ，您可以联系销售代表以获取超值包评估许可证。



 a| 
SnapMirror 或 SnapVault
 a| 
ONTAP

如果在 SnapCenter 中启用了复制，则需要 SnapMirror 或 SnapVault 许可证。



 a| 
其他许可证（可选）
 a| 
请参见 link:../install/concept_snapcenter_licenses.html["SnapCenter 许可证"^]。



 a| 
SnapCenter 标准许可证（可选）
 a| 
二级目标


NOTE: 建议（但不要求）将 SnapCenter 标准版许可证添加到二级目标。如果二级目标上未启用 SnapCenter 标准许可证，则在执行故障转移操作后，您将无法使用 SnapCenter 备份二级目标上的资源。但是，要执行克隆和验证操作，二级目标需要 FlexClone 许可证。

|===


== 主机和端口要求

有关ONTAP和应用程序插件的最低要求、请参见 https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT[][互操作性表工具^]。

[cols="1,3"]
|===
| 主机 | 最低要求 


 a| 
操作系统（ 64 位）
 a| 
请参见 https://imt.netapp.com/matrix/imt.jsp?components=121030;&solution=1259&isHWU&src=IMT["互操作性表工具"^]



 a| 
CPU
 a| 
* 服务器主机： 4 个核心
* 插件主机：4个核心




 a| 
RAM
 a| 
* 服务器主机： 8 GB
* 插件主机： 4 GB




 a| 
硬盘驱动器空间
 a| 
服务器主机：

* 7 GB ，用于 SnapCenter 服务器软件和日志
* 8 GB 用于 SnapCenter 存储库
* 每个插件主机： 2 GB 用于插件安装和日志，只有在专用主机上安装了插件时才需要此空间。




 a| 
第三方库
 a| 
SnapCenter 服务器主机和插件主机上需要：

* Microsoft .NET Framework 4.7.2或更高版本
* ASP。 NET Core托管包(8.0.5或更高版本)
* PowerShell 7.4.2或更高版本




 a| 
浏览器
 a| 
Chrome ， Internet Explorer 和 Microsoft Edge

|===
[cols="1,3"]
|===
| 端口类型 | 默认端口 


 a| 
SnapCenter 端口
 a| 
8146 （ HTTPS ），双向，可自定义，如 URL ： _\https://server:8146_



 a| 
SnapCenter SMCore 通信端口
 a| 
8145 （ HTTPS ），双向，可自定义



 a| 
存储库数据库
 a| 
3306 （ HTTPS ），双向



 a| 
Windows 插件主机
 a| 
135 ， 445 （ TCP ）

除了端口 135 和 445 之外， Microsoft 指定的动态端口范围也应处于打开状态。远程安装操作使用 Windows Management Instrumentation （ WMI ）服务，该服务会动态搜索此端口范围。

有关支持的动态端口范围的信息，请参见 https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Windows 的服务概述和网络端口要求"^]。



 a| 
适用于 Windows 的 SnapCenter 插件
 a| 
8145 （ HTTPS ），双向，可自定义



 a| 
ONTAP 集群或 SVM 通信端口
 a| 
443 （ HTTPS ），双向； 80 （ HTTP ），双向

此端口用于在 SnapCenter 服务器主机，插件主机和 SVM 或 ONTAP 集群之间进行通信。

|===


== 适用于Microsoft SQL Server的SnapCenter 插件要求

您应拥有一个具有本地管理员权限的用户，并在远程主机上拥有本地登录权限。如果您管理集群节点，则需要一个对集群中所有节点具有管理权限的用户。

您应具有一个对 SQL Server 具有 sysadmin 权限的用户。此插件使用 Microsoft VDI Framework ，需要 sysadmin 访问权限。

如果您使用的是适用于 Microsoft SQL Server 的 SnapManager ，并且希望将数据从适用于 Microsoft SQL Server 的 SnapManager 导入到 SnapCenter ，请参见 link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["导入归档备份"^]
