---
permalink: protect-scsql/task-install-snapcenter-server-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: 提供有关安装适用于Microsoft SQL Server的SnapCenter 服务器的说明。 
---
= 安装SnapCenter 服务器for Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
提供了一组精简的安装说明、用于安装SnapCenter Server for Microsoft SQL Server。



== 第1步：下载并安装SnapCenter 服务器

. 从下载 SnapCenter 服务器安装包 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 支持站点"^] 然后双击该 exe 。
+
启动安装后，系统将执行所有预检，如果不满足最低要求，则会显示相应的错误或警告消息。您可以忽略警告消息并继续安装；但是，错误应予以修复。

. 查看安装 SnapCenter 服务器所需的预填充值，并根据需要进行修改。
+
您不必指定 MySQL Server 存储库数据库的密码。在 SnapCenter 服务器安装期间，系统会自动生成密码。

+

NOTE: 自定义安装路径不支持特殊字符 "%" 。如果在路径中包含 "%" ，则安装将失败。

. 单击 * 立即安装 * 。




== 第2步：登录到SnapCenter

. 从主机桌面上的快捷方式或安装提供的 URL 启动 SnapCenter （对于安装 SnapCenter 服务器的默认端口 8146 ，为 _\https://server:8146_ ）。
. 输入凭据。
+
对于内置的域管理员用户名格式，请使用： _netbios\< 用户名 >_ 或 _ < 用户名 >@ < 域 >_ 或 _ < 域 FQDN>\ < 用户名 >_ 。

+
对于内置的本地管理员用户名格式，请使用 _ < 用户名 >_ 。

. 单击 * 登录 * 。




== 第3步：添加基于SnapCenter 标准控制器的许可证

. 使用 ONTAP 命令行登录到控制器并输入：
+
`ssystem license add -license-code <license_key>`

. 验证许可证：
+
`许可证显示`





== 第4步：设置存储系统连接

. 在左窗格中，单击 * 存储系统 > 新建 * 。
. 在添加存储系统页面中，执行以下操作：
+
.. 输入存储系统的名称或 IP 地址。
.. 输入用于访问存储系统的凭据。
.. 选中相应复选框以启用事件管理系统（ EMS ）和 AutoSupport 。


. 如果要修改分配给平台，协议，端口和超时的默认值，请单击 * 更多选项 * 。
. 单击 * 提交 * 。

