---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords:  
summary: 在使用适用于 Microsoft Windows 的 SnapCenter 插件配置 NetApp 存储系统后，您可以使用 SnapCenter 图形用户界面（图形用户界面）或 PowerShell cmdlet 将资源迁移到 NetApp 存储系统，或者从一个 NetApp LUN 迁移到另一个 NetApp LUN 。 
---
= 将资源迁移到 NetApp 存储系统
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用适用于 Microsoft Windows 的 SnapCenter 插件配置 NetApp 存储系统后，您可以使用 SnapCenter 图形用户界面（ GUI ）或 PowerShell cmdlet 将资源迁移到 NetApp 存储系统或从一个 NetApp LUN 迁移到另一个 NetApp LUN 。

* 您需要的内容 *

* 您必须已将存储系统添加到 SnapCenter 服务器。
* 您必须已刷新（发现） SQL Server 资源。


这些向导页面上的大多数字段都是不言自明的。以下信息介绍了一些可能需要指导的字段。

* 步骤 *

. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 在 * 资源 * 页面中，从 * 视图 * 下拉列表中选择 * 数据库 * 或 * 实例 * 。
. 从列表中选择数据库或实例，然后单击 * 迁移 * 。
. 在 * 资源 * 页面中，执行以下操作：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
* 数据库名称 * （可选）
 a| 
如果选择了要迁移的实例，则必须从 * 数据库 * 下拉列表中选择该实例的数据库。



 a| 
* 选择目标 *
 a| 
选择数据和日志文件的目标位置。

数据和日志文件将分别移至选定 NetApp 驱动器下的 Data 和 Log 文件夹。如果文件夹结构中不存在任何文件夹，则会创建一个文件夹并迁移资源。



 a| 
* 显示数据库文件详细信息 * （可选）
 a| 
如果要迁移单个数据库的多个文件，请选择此选项。


NOTE: 选择 * 实例 * 资源时不会显示此选项。



 a| 
* 选项 *
 a| 
选择 * 删除原始位置的已迁移数据库副本 * 可从源中删除数据库副本。

可选： * 在断开数据库之前对表运行更新统计信息 * 。

|===
. 在 * 验证 * 页面中，执行以下操作：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
* 数据库一致性检查选项 *
 a| 
选择 * 在迁移之前运行 * 以在迁移之前检查数据库的完整性。选择 * 迁移后运行 * 可在迁移后检查数据库的完整性。



 a| 
* DBCC CHECKDB 选项 *
 a| 
** 选择 * 物理仅 * 选项可将完整性检查限制为数据库的物理结构，并检测会影响数据库的已破页面，校验和故障以及常见硬件故障。
** 选择 * 否 _INFOMSGS* 选项可禁止显示所有信息性消息。
** 选择 * 全部 _ERRORMSGs* 选项可显示每个对象报告的所有错误。
** 如果不想检查非集群索引，请选择 * NOINDIEX* 选项。
+
SQL Server 数据库使用 Microsoft SQL Server 数据库一致性检查程序（ DBCC ）来检查数据库中对象的逻辑和物理完整性。

+

NOTE: 您可能需要选择此选项以缩短执行时间。

** 选择 "**TABLOCK_" 选项以限制检查并获取锁定，而不是使用内部数据库 Snapshot 副本。


|===
. 查看摘要，然后单击 "* 完成 "* 。

