---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: 您可以在使用 SnapCenter 备份 SQL Server 资源之前为资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。 
---
= 为 SQL Server 数据库创建备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用 SnapCenter 备份 SQL Server 资源之前为资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。

.开始之前
* 您必须已定义数据保护策略。
* 您必须已通过完成安装 SnapCenter ，添加主机，识别资源以及创建存储系统连接等任务为数据保护做好准备。
* 您必须已为日志备份配置主机日志目录。
* 您必须已刷新（发现） SQL Server 资源。
* 如果要将快照复制到镜像或存储、SnapCenter管理员必须已将源卷和目标卷的Storage Virtual Machine (SVM)分配给您。
+
有关管理员如何为用户分配资源的信息，请参见 SnapCenter 安装信息。

* 如果要在预处理脚本和后处理脚本中运行 PowerShell 脚本，应在 web.config 文件中将 usePowershellProcessforScripts 参数的值设置为 true 。
+
默认值为 false 。

* 查看SnapMirror主动同步的特定前提条件和限制。有关信息，请参阅 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror活动同步的对象限制"]。


.关于此任务
* 备份策略是一组规则，用于控制如何管理和保留备份以及备份资源或资源组的频率。此外，您还可以指定复制和脚本设置。在策略中指定选项可节省将策略重复用于其他资源组的时间。
+
脚本路径使用位于插件主机SMCoreServiceHost.exe配置文件中的预定义WindowsScriptsDirectory密钥进行定义。

+
如果需要、您可以更改此路径并重新启动SMcore服务。建议您使用默认安全路径。

+
可以通过API：API /4.7/configsettings从Swagger显示密钥值

+
您可以使用GET API显示密钥的值。不支持设置API。

* SnapLock
+
** 如果选择了"将备份副本保留特定天数"选项、则SnapLock保留期限必须小于或等于上述保留天数。
+
指定Snapshot锁定期限可防止删除Snapshot、直到保留期限到期为止。  这样可能会导致保留的Snapshot数量超过策略中指定的数量。

+
对于ONTAP 9.12.1及更低版本、在还原过程中从SnapLock存储快照创建的克隆将继承SnapLock存储到期时间。存储管理员应在SnapLock到期时间后手动清理克隆。







== 第1步：创建策略名称

. 在左侧导航窗格中，选择*Settings*。
. 在设置页面中，选择*Policies*。
. 选择*New*。
. 在*Name*页面中，输入策略名称和详细信息。




== 第2步：配置策略选项

. 在"Policy type"(策略类型)页面中、执行以下步骤：
+
.. 选择存储类型。
.. 选择策略范围。
+
[role="tabbed-block"]
====
.完整备份和日志备份
--
备份数据库文件和事务日志、并将事务日志进行truncate。

... 选择 * 完整备份和日志备份 * 。
... 输入应为每个Snapshot备份的最大数据库数。
+

NOTE: 如果要同时运行多个备份操作，则必须增加此值。



--
.完整备份
--
备份数据库文件。

... 选择 * 完整备份 * 。
... 输入应为每个Snapshot备份的最大数据库数。
默认值为 100
+

NOTE: 如果要同时运行多个备份操作，则必须增加此值。



--
.日志备份
--
... 备份事务日志。
... 选择 * 日志备份 * 。


--
.仅复制备份
--
... 如果要使用另一个备份应用程序备份资源，请选择 * 仅复制备份 * 。


保持事务日志完好无损可使任何备份应用程序恢复数据库。在任何其他情况下，通常不应使用仅复制选项。


NOTE: 对于二级存储， Microsoft SQL 不支持 * 仅复制备份 * 选项以及 * 完整备份和日志备份 * 选项。

--
====






== 第3步：配置可用性组设置

. 在可用性组设置部分中，执行以下操作：
+
.. 仅在首选备份副本上备份。
+
选择此选项可仅在首选备份副本上进行备份。首选备份副本由为 SQL Server 中的 AG 配置的备份首选项决定。

.. 选择要备份的副本。
+
为备份选择主 AG 副本或二级 AG 副本。

.. 选择备份优先级(最小和最大备份优先级)
+
指定最小备份优先级数和最大备份优先级数，用于确定要备份的 AG 副本。例如，您可以将最小优先级设置为 10 ，最大优先级设置为 50 。在这种情况下，优先级大于 10 且小于 50 的所有 AG 副本都会考虑进行备份。

+
默认情况下，最小优先级为 1 ，最大优先级为 100 。



+

NOTE: 在集群配置中，备份会根据策略中设置的保留设置保留在集群的每个节点上。如果 AG 的所有者节点发生更改，则会根据保留设置进行备份，并保留先前所有者节点的备份。AG 的保留仅适用于节点级别。





== 第4步：配置Snapshot和复制设置

. 在Snapshot and Replication页面中、执行以下步骤：
+
.. 通过选择 * 按需 * ， * 每小时 * ， * 每日 * ， * 每周 * 或 * 每月 * 来指定计划类型。
+
您只能为策略选择一种计划类型。

+

NOTE: 您可以在创建资源组时为备份操作指定计划（开始日期，结束日期和频率）。这样，您可以创建共享相同策略和备份频率的资源组，但可以为每个策略分配不同的备份计划。

+

NOTE: 如果您已计划凌晨 2 ： 00 ，则在夏令时（ DST ）期间不会触发此计划。







== 第5步：配置最新保留设置

. 在分钟级保留设置部分中、根据在备份类型页面中选择的备份类型、执行以下一项或多项操作：


[role="tabbed-block"]
====
.特定份数
--
仅保留特定数量的快照。

. 选择 * 保留适用于过去 < 天数 > 天 * 的日志备份选项，并指定要保留的天数。如果您接近此限制，则可能需要删除较早的副本。


--
.特定天数
--
将备份副本保留特定天数。

. 选择 * 保留适用于最后 < 天数 > 天完整备份 * 选项，并指定保留日志备份副本的天数。


--
====


== 第6步：配置Snapshot设置

. 对于完整备份保留设置、请执行以下操作：
+
.. 指定要保留的快照总数
+
... 要指定要保留的快照数量，请选择*要保留的副本*。
... 如果快照数量超过指定数量、则会删除快照、并首先删除最早的副本。
+

IMPORTANT: 默认情况下，保留计数值设置为 2 。如果将保留计数设置为1、则保留操作可能会失败、因为第一个快照是SnapVault关系的参考快照、直到将较新的快照复制到目标为止。

+

NOTE: 最大保留值为1018。如果保留设置的值高于底层NetApp ONTAP版本支持的值、备份将失败。







. 保留快照的时间长度
+
.. 如果要指定在删除快照之前保留快照的天数、请选择*保留副本*。


. 选择*Snapshot 副本锁定期限*并指定天、月或年的持续时间。
+
SnapLock保留期限应少于100年。

. 选择策略标签。
+

NOTE: 您可以为远程复制的主快照分配SnapMirror标签，从而允许主快照将快照复制操作从SnapCenter卸载到ONTAP二级系统。无需在策略页面中启用SnapMirror或SnapVault选项即可完成此操作。





== 第7步：配置二级复制选项

. 在选择二级复制选项部分中、选择以下一个或两个二级复制选项：


[role="tabbed-block"]
====
.更新SnapMirror
--
创建本地Snapshot副本后更新SnapMirror。

. 选择此选项可在另一个卷（ SnapMirror ）上创建备份集的镜像副本。
+
对于SnapMirror活动同步、应启用此选项。

+
在二级复制期间、SnapLock到期时间会加载主SnapLock到期时间。单击"Topology"页面中的*Refresh*按钮可刷新从ONTAP检索到的二级和主SnapLock到期时间。

+
请参阅。 link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在拓扑页面中查看 SQL Server 备份和克隆"]



--
.更新SnapVault
--
创建Snapshot副本后更新SnapVault。

. 选择此选项可执行磁盘到磁盘备份复制。
+
在二级复制期间、SnapLock到期时间会加载主SnapLock到期时间。单击"Topology"页面中的*Refresh*按钮可刷新从ONTAP检索到的二级和主SnapLock到期时间。

+
如果仅在ONTAP中称为SnapLock存储的二级系统上配置了SnapLock，则单击“拓扑”页面中的*Refresh*按钮可刷新从ONTAP检索到的二级系统上的锁定期限。

+
有关SnapLock存储的详细信息、请参见 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["将Snapshot副本提交到存储目标上的WORM"]

+
请参阅。 link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["在拓扑页面中查看 SQL Server 备份和克隆"]



--
.错误重试计数
--
. 输入在进程暂停之前应进行的复制尝试次数。


--
====


== 第8步：配置脚本设置

. 在脚本页面中，分别输入应在备份操作前后运行的预处理或后处理程序的路径和参数。
+
例如，您可以运行脚本来更新 SNMP 陷阱，自动执行警报和发送日志。

+

NOTE: 预处理脚本或后处理脚本路径不应包含驱动器或共享。路径应与scripts_path相关。

+

NOTE: 您必须在ONTAP中配置SnapMirror保留策略、以使二级存储不会达到Snapshot的最大限制。





== 第9步：配置验证设置

在验证页面中，执行以下步骤：

. 在 Run verification for following backup schedules 部分中，选择计划频率。
. 在 Database consistency check options 部分中，执行以下操作：
+
.. 将完整性结构限制为数据库的物理结构（ physical_only ）
+
... 选择 * 将完整性结构限制为数据库的物理结构（ physical_only ） * 可将完整性检查限制为数据库的物理结构，并检测影响数据库的已破页面，校验和故障以及常见硬件故障。


.. 禁止所有信息消息(无INFOMSGS)
+
... 选择 * 禁止所有信息消息（ NO_INFOMSGS ） * 以禁止所有信息消息。默认情况下处于选中状态。


.. 显示每个对象报告的所有错误消息（ all_ERRORMSGS ）
+
... 选择 * 显示每个对象报告的所有错误消息（ all_ERRORMSGS ） * 以显示每个对象报告的所有错误。


.. 不要检查非集群索引（ NOINDEX ）
+
... 如果不想检查非集群索引，请选择 * 不检查非集群索引（ NOINDEX ） * 。SQL Server 数据库使用 Microsoft SQL Server 数据库一致性检查程序（ DBCC ）来检查数据库中对象的逻辑和物理完整性。


.. 限制检查并获取锁定、而不是使用内部数据库快照(TABLOCk)
+
... 选择*限制检查并获取锁定，而不是使用内部数据库Snapshot副本(TABLOC)*来限制检查并获取锁定，而不是使用内部数据库Snapshot。




. 在 * 日志备份 * 部分中，选择 * 完成时验证日志备份 * 以在完成后验证日志备份。
. 在 * 验证脚本设置 * 部分中，分别输入在验证操作之前或之后应运行的预处理或后处理脚本的路径和参数。
+

NOTE: 预处理脚本或后处理脚本路径不应包含驱动器或共享。路径应与scripts_path相关。





== 第10步：查看摘要

. 查看摘要，然后选择*完成*。

