---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: 使用 SnapCenter ，您可以从资源组或数据库创建克隆。您可以执行按需克隆，也可以计划资源组或数据库的重复克隆操作。如果定期克隆备份，则可以使用克隆开发应用程序，填充数据或恢复数据。 
---
= 执行克隆生命周期
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 SnapCenter ，您可以从资源组或数据库创建克隆。您可以执行按需克隆，也可以计划资源组或数据库的重复克隆操作。如果定期克隆备份，则可以使用克隆开发应用程序，填充数据或恢复数据。

通过 SnapCenter ，您可以计划在多个服务器上同时运行多个克隆操作。

* 您需要的内容 *

* 在克隆到独立数据库实例时，请确保挂载点路径存在且它是专用磁盘。
* 在克隆到故障转移集群实例（ FCI ）时，请确保挂载点存在，挂载点是共享磁盘，并且路径和 FCI 应属于同一个 SQL 资源组。
* 如果源数据库或目标实例位于集群共享卷（ csv ）上，则克隆的数据库将位于 csv 上。



NOTE: 对于虚拟环境（ VMDB/RDM ），请确保挂载点是专用磁盘。

* 步骤 *

. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 在 * 资源 * 页面中，从 * 视图 * 列表中选择 * 数据库 * 或 * 资源组 * 。
. 选择资源组或数据库，然后单击 * 克隆生命周期 * 。
. 在 * 选项 * 页面中，执行以下操作：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
克隆作业名称
 a| 
指定有助于监控和修改克隆生命周期作业的克隆生命周期作业名称。



 a| 
克隆服务器
 a| 
选择应放置克隆的主机。



 a| 
克隆实例
 a| 
选择要将数据库克隆到的克隆实例。此 SQL 实例必须位于指定的克隆服务器中。



 a| 
克隆后缀
 a| 
输入要附加到克隆数据库的后缀，以确定它是克隆。用于创建克隆资源组的每个 SQL 实例都必须具有唯一的数据库名称。例如，如果克隆资源组包含来自 SQL 实例 "`inst1` " 的源数据库 " `dB1` " ，并且 " `dB1` " 克隆为 "`inst1` " ，则克隆数据库名称应为 " `db1_clone` " 。"` _clone` " 是用户定义的必填后缀，因为数据库已克隆到同一实例。如果将 "`dB1` " 克隆到 SQL 实例 "`inst2` " ，则克隆数据库名称可以保持为 " `dB1` " （后缀为可选），因为该数据库会克隆到其他实例。



 a| 
在路径下自动分配挂载点或自动分配卷挂载点
 a| 
选择是在路径下自动分配挂载点还是卷挂载点。通过选择在路径下自动分配卷挂载点，您可以提供特定目录。挂载点将在该目录中创建。在选择此选项之前，必须确保目录为空。如果目录中存在数据库，则在执行挂载操作后，该数据库将处于无效状态。

|===
. 在 * 位置 * 页面中，选择要创建克隆的存储位置。
. 在 * 脚本 * 页面中，分别输入应在克隆操作之前或之后运行的预处理或后处理的路径和参数。
+
例如，您可以运行脚本来更新 SNMP 陷阱，自动执行警报，发送日志等操作。

+
默认脚本超时为 60 秒。

. 在 * 计划 * 页面中，执行以下操作之一：
+
** 如果要立即执行克隆作业，请选择 * 立即运行 * 。
** 如果要确定克隆操作的频率，克隆计划的启动时间，克隆操作的发生日期，计划的到期时间以及计划到期后是否需要删除克隆，请选择 * 配置计划 * 。


. 在 * 通知 * 页面的 * 电子邮件首选项 * 下拉列表中，选择要发送电子邮件的场景。
+
您还必须指定发件人和收件人电子邮件地址以及电子邮件主题。如果要附加所执行克隆操作的报告，请选择 * 附加作业报告 * 。

+

NOTE: 对于电子邮件通知，您必须已使用 GUI 或 PowerShell 命令 set-SmtpServer 指定 SMTP 服务器详细信息。

+
对于 EMS ，您可以参考 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection["管理 EMS 数据收集"]

. 查看摘要，然后单击 * 完成 * 。


您应使用 * 监控 * > * 作业 * 页面监控克隆过程。
