---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter 使用凭据对 SnapCenter 操作的用户进行身份验证。您应创建用于安装 SnapCenter 插件的凭据以及用于对数据库或 Windows 文件系统执行数据保护操作的其他凭据。 
---
= 设置适用于 Windows 的 SnapCenter 插件软件包的凭据
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 使用凭据对 SnapCenter 操作的用户进行身份验证。您应创建用于安装 SnapCenter 插件的凭据以及用于对数据库或 Windows 文件系统执行数据保护操作的其他凭据。

* 您需要的内容 *

* 在安装插件之前，您必须设置 Windows 凭据。
* 您必须使用管理员权限设置凭据，包括对远程主机的管理员权限。
* Windows 主机上的 SQL 身份验证
+
您必须在安装插件后设置 SQL 凭据。

+
如果要部署适用于 Microsoft SQL Server 的 SnapCenter 插件，则必须在安装插件后设置 SQL 凭据。为具有 SQL Server sysadmin 权限的用户设置凭据。

+
SQL 身份验证方法针对 SQL Server 实例进行身份验证。这意味着必须在 SnapCenter 中发现 SQL Server 实例。因此，在添加 SQL 凭据之前，您必须添加主机，安装插件软件包并刷新资源。要执行计划或发现资源等操作，您需要进行 SQL Server 身份验证。



* 步骤 *

. 在左侧导航窗格中，单击 * 设置 * 。
. 在 * 设置 * 页面中，单击 * 凭据 * 。
. 单击 * 新建 * 。
. 在 * 凭据 * 页面中，指定配置凭据所需的信息：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
凭据名称
 a| 
输入凭据的名称。



 a| 
用户名 / 密码
 a| 
输入要用于身份验证的用户名和密码。

** 域管理员
+
在要安装 SnapCenter 插件的系统上指定域管理员。用户名字段的有效格式为：

+
*** `netbios\username`
*** `d域名 FQDN\username`


** 本地管理员（仅适用于工作组）
+
对于属于工作组的系统，请指定要安装 SnapCenter 插件的系统上的内置本地管理员。如果用户帐户具有提升的权限或在主机系统上禁用了用户访问控制功能，则可以指定属于本地管理员组的本地用户帐户。用户名字段的有效格式为： `username`

+
请勿在密码中使用双引号（ " ）。





 a| 
身份验证模式
 a| 
选择要使用的身份验证模式。如果选择 SQL 身份验证模式，则还必须指定 SQL Server 实例和 SQL 实例所在的主机。

|===
. 单击 * 确定 * 。


完成凭据设置后，您可能需要在 * 用户和访问 * 页面上为用户或用户组分配凭据维护。
