---
permalink: protect-sco/alternate-ways-install-plug-in-linux-aix.html 
sidebar: sidebar 
keywords: alternate methods, install, plug-ins package, linux, aix, remote hosts, cmdlets, cluster host, silent mode, console mode 
summary: 您可以使用其他方法安装适用于 Linux 的 SnapCenter 插件软件包或适用于 AIX 的 SnapCenter 插件软件包。 
---
= 安装适用于 Linux 或 AIX 的插件软件包的其他方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您也可以使用cmdlet或CLI手动安装适用于Linux或AIX的插件软件包。

在手动安装此插件之前、您应使用* snapcenter_public_key.pub *和* snapcenter_linux_host_plugin.bin.SIG*密钥来验证二进制软件包的签名、该密钥位于_C：\ProgramData\NetApp\SnapCenter\Package Repository_。


NOTE: 确保要安装此插件的主机上安装了* OpenSSL 1.0.2g*。

运行以下命令、验证二进制文件包的签名：

* 对于Linux主机： `openssl dgst -sha256 -verify snapcenter_public_key.pub -signature snapcenter_linux_host_plugin.bin.sig snapcenter_linux_host_plugin.bin`
* 对于AIX主机： `openssl dgst -sha256 -verify snapcenter_public_key.pub -signature snapcenter_linux_host_plugin.bsx.sig snapcenter_linux_host_plugin.bsx`




== 使用 cmdlet 在多个远程主机上安装

您应使用 _Install-SmHostPackage_ PowerShell cmdlet 在多个主机上安装适用于 Linux 的 SnapCenter 插件软件包或适用于 AIX 的 SnapCenter 插件软件包。

* 您需要的内容 *

您应在要安装此插件软件包的每个主机上以具有本地管理员权限的域用户身份登录到 SnapCenter 。

* 步骤 *

. 启动 PowerShell 。
. 在 SnapCenter 服务器主机上，使用 _Open-SmConnection_ cmdlet 建立会话，然后输入凭据。
. 使用 _Install-SmHostPackage_ cmdlet 和所需参数安装适用于 Linux 的 SnapCenter 插件软件包或适用于 AIX 的 SnapCenter 插件软件包。
+
如果您已手动安装插件，并且不想验证主机是否满足安装插件的要求，则可以使用 _-skipprecheck_ 选项。

+

NOTE: 如果在防火墙拒绝规则中指定了插件端口防火墙状态，则预检脚本不会对其进行验证。

. 输入远程安装的凭据。


有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《 SnapCenter 软件 cmdlet 参考指南》"^]。



== 在集群主机上安装

您应在集群主机的两个节点上安装适用于 Linux 的 SnapCenter 插件软件包或适用于 AIX 的 SnapCenter 插件软件包。

集群主机的每个节点都有两个 IP 。其中一个 IP 是相应节点的公有 IP ，另一个 IP 是两个节点之间共享的集群 IP 。

* 步骤 *

. 在集群主机的两个节点上安装适用于 Linux 的 SnapCenter 插件软件包或适用于 AIX 的 SnapCenter 插件软件包。
. 验证是否在位于 /var/opt/snapcenter/spl/etc/ 的 spl.properties 文件中指定了正确的 SNAPCENTER_SERVER_host ， SPL_port ， SNAPCENTER_SERVER_PORT 和 SPL_END_plugins 参数值。
+
如果 spl.properties 中未指定 SPL_END_plugins ，则可以添加它并分配值 SCO ， scU 。

. 在 SnapCenter 服务器主机上，使用 _Open-SmConnection_ cmdlet 建立会话，然后输入凭据。
. 在每个节点中，使用 _set-PreferredHostIPsInStorageExportPolicy_ sccli 命令和所需参数设置节点的首选 IP 。
. 在 SnapCenter 服务器主机中，在 _C ： \Windows\System32\drivers\etc\hosts_ 中为集群 IP 和相应的 DNS 名称添加一个条目。
. 使用 _Add-SmHost_ cmdlet 指定主机名的集群 IP ，将节点添加到 SnapCenter 服务器。


发现节点 1 上的 Oracle 数据库（假设集群 IP 托管在节点 1 上）并创建数据库备份。如果发生故障转移，您可以使用在节点 1 上创建的备份来还原节点 2 上的数据库。您也可以使用在节点 1 上创建的备份在节点 2 上创建克隆。


NOTE: 如果在运行任何其他 SnapCenter 操作时发生故障转移，则会存在陈旧的卷，目录和锁定文件。



== 在静默模式下安装适用于Linux的插件软件包

您可以使用命令行界面(CLI)在静默模式下安装适用于Linux的SnapCenter 插件软件包。

* 您需要的内容 *

* 您应查看安装插件软件包的前提条件。
* 您应确保未设置显示环境变量。
+
如果设置了 display 环境变量，则应运行 unset display ，然后尝试手动安装此插件。



* 关于此任务 *

在控制台模式下安装时，您需要提供必要的安装信息，而在静默模式下安装时，则无需提供任何安装信息。

* 步骤 *

. 从 SnapCenter 服务器安装位置下载适用于 Linux 的 SnapCenter 插件软件包。
+
默认安装路径为 _C ： \ProgramData\NetApp\SnapCenter\PackageRepository 。可以从安装了 SnapCenter 服务器的主机访问此路径。

. 在命令提示符处，导航到下载安装文件的目录。
. 运行
+
` ./SnapCenter_Linux_host_plugin.bin-I silent-Dport=8145-dserver_ip=SnapCenter_Server_FQDN-dserver_HTTPS_port=SnapCenter_Server_Port-Duser_install_DIR=/opt/custom_path`

. 编辑位于 /var/opt/snapcenter/spl/etc/_ 的 spl.properties 文件以添加 SPL_enabled_plugins=SCO ， scu ，然后重新启动 SnapCenter 插件加载程序服务。



IMPORTANT: 安装插件软件包时，会在主机上注册插件，而不是在 SnapCenter 服务器上注册插件。您应使用 SnapCenter 图形用户界面或 PowerShell cmdlet 添加主机，以便在 SnapCenter 服务器上注册插件。添加主机时，请选择 " 无 " 作为凭据。添加主机后，系统会自动发现已安装的插件。



== 在静默模式下安装适用于 AIX 的插件软件包

您可以使用命令行界面（ CLI ）在静默模式下安装适用于 AIX 的 SnapCenter 插件软件包。

* 您需要的内容 *

* 您应查看安装插件软件包的前提条件。
* 您应确保未设置显示环境变量。
+
如果设置了 display 环境变量，则应运行 unset display ，然后尝试手动安装此插件。



* 步骤 *

. 从 SnapCenter 服务器安装位置下载适用于 AIX 的 SnapCenter 插件软件包。
+
默认安装路径为 _C ： \ProgramData\NetApp\SnapCenter\PackageRepository 。可以从安装了 SnapCenter 服务器的主机访问此路径。

. 在命令提示符处，导航到下载安装文件的目录。
. 运行
+
` ./snapcenter_aix_host_plugin.bsx-I silent-Dport=8145-dserver_ip=SnapCenter_Server_FQDN-dserver_HTTPS_port=SnapCenter_Server_Port-Duser_install_DIR=/opt/custom_path-DINSTALL_log_name=SnapCenter_AIX_Host_Plug_User_List_User_CN_US_CNES_US_US_USER_DIR=/CTO_USER_USER_CH_USER.CHOCH_USER.CH_USER_USER_DIR=DTO_NAME=DTO_USER.`

. 编辑位于 /var/opt/snapcenter/spl/etc/_ 的 spl.properties 文件以添加 SPL_enabled_plugins=SCO ， scu ，然后重新启动 SnapCenter 插件加载程序服务。



IMPORTANT: 安装插件软件包时，会在主机上注册插件，而不是在 SnapCenter 服务器上注册插件。您应使用 SnapCenter 图形用户界面或 PowerShell cmdlet 添加主机，以便在 SnapCenter 服务器上注册插件。添加主机时，请选择 " 无 " 作为凭据。添加主机后，系统会自动发现已安装的插件。
