---
permalink: protect-sco/catalog-backups.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter 如何发现Oracle数据库。 
---
= 如何使用 Oracle Recovery Manager 对备份进行目录编制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Oracle Recovery Manager (RMAN)为Oracle数据库的备份编制目录、以便将备份信息存储在Oracle RMAN存储库中。

编目备份可供稍后块级还原或表空间时间点恢复操作使用。如果您不需要这些已编目的备份，则可以删除目录信息。

数据库必须处于挂载状态或更高状态才能进行编目。您可以对数据备份，归档日志备份和完整备份执行目录编制。如果为包含多个数据库的资源组的备份启用了目录编制，则会对每个数据库执行目录编制。对于 Oracle RAC 数据库，将在数据库至少处于挂载状态的首选节点上执行目录编制。

如果要对 RAC 数据库的备份进行编目，请确保此数据库未运行任何其他作业。如果另一个作业正在运行，则编目操作将失败，而不是排队。



== 外部目录数据库

默认情况下，目标数据库控制文件用于目录编制。如果要添加外部目录数据库，可以通过在 SnapCenter 图形用户界面（ GUI ）中使用数据库设置向导指定外部目录的凭据和透明网络基线（ Network Substrate ， TNS ）名称来对其进行配置。此外，您还可以从命令行界面使用 -OracleRmanCatalogCredentialName 和 -OracleRmanCatalogTnsName 选项运行 Configure-SmOracleDatabase 命令来配置外部目录数据库。



== RMAN命令

如果在从 SnapCenter 图形用户界面创建 Oracle 备份策略时启用了编目选项，则在备份操作中会使用 Oracle RMAN 对备份进行编目。您还可以通过运行来执行延迟备份编目 `Catalog-SmBackupWithOracleRMAN` 命令：

编制备份目录后、您可以运行 `Get-SmBackupDetails` 命令以获取已编制目录的备份信息、例如、已编制目录的数据文件的标记、控制文件目录路径以及已编制目录的归档日志位置。



== 命名格式

如果 ASM 磁盘组名称大于或等于 16 个字符，则从 SnapCenter 3.0 开始，用于备份的命名格式为 SC_HASHCODEofDISKGROUP_DBSID_BACKUPID 。但是，如果磁盘组名称少于 16 个字符，则用于备份的命名格式为 DISKGROUPNAME_DBSID_BACKUPID ，此格式与 SnapCenter 2.0 中使用的格式相同。

HASHCODEofDISKGROUP 是为每个 ASM 磁盘组自动生成的唯一数字（ 2 到 10 位数）。



== 交叉检查操作

您可以执行交叉检查来更新有关存储库记录与其物理状态不匹配的备份的过时 RMAN 存储库信息。例如，如果用户使用操作系统命令从磁盘中删除归档日志，则控制文件仍会指示这些日志位于磁盘上，而实际上不在磁盘上。

通过交叉检查操作，您可以使用信息更新控制文件。您可以通过运行 set-SmConfigSettings 命令并为 enable_casscheck 参数分配值 true 来启用交叉检查。默认值设置为 false 。

`sCCLI Set-SmConfigSettings-ConfigSettingsTypePlug-PluginCodeSCo-ConfigSettings "key=enable_sponcheck ， value=true"`



== 删除目录信息

您可以运行 Uncatalog -SmBackupWithOracleRMAN 命令来删除目录信息。您不能使用 SnapCenter 图形用户界面删除目录信息。但是，在删除备份或删除与该已编目备份关联的保留和资源组时，会删除已编目备份的信息。


NOTE: 强制删除 SnapCenter 主机时，不会删除与该主机关联的已编目备份的信息。在强制删除主机之前，必须删除该主机的所有已编目备份的信息。

如果由于操作时间超过为 ORACLE_plugin_RMAN_catalog 超时参数指定的超时值而导致编目和取消编目失败，则应运行以下命令来修改参数的值：

` /opt/netapp/snapcenter/spl/bin/sccli set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCo-ConfigSettings "key=ORACLE_plugin_RMAN_catalog timeout ， value=user_defined_value"`

修改参数值后，运行以下命令重新启动 SnapCenter 插件加载程序（ SPL ）服务：

` /opt/netapp/snapcenter/spl/bin/spl restart`

有关可与命令结合使用的参数及其说明的信息，可通过运行 get-help command_name 来获取。或者，您也可以参考 https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["《 SnapCenter 软件命令参考指南》"^]。
