---
permalink: protect-sco/concept_prepare_for_protecting_oracle_databases.html 
sidebar: sidebar 
keywords: oracle, preparation for protection, prerequisites 
summary: 在执行备份，克隆或还原操作等任何数据保护操作之前，您必须定义策略并设置环境。您还可以设置 SnapCenter 服务器以使用 SnapMirror 和 SnapVault 技术。 
---
= 准备保护 Oracle 数据库
:icons: font
:imagesdir: ../media/


[role="lead"]
在执行备份，克隆或还原操作等任何数据保护操作之前，您必须定义策略并设置环境。您还可以设置 SnapCenter 服务器以使用 SnapMirror 和 SnapVault 技术。

要利用 SnapVault 和 SnapMirror 技术，您必须在存储设备上的源卷和目标卷之间配置和初始化数据保护关系。您可以使用 NetAppSystem Manager ，也可以使用存储控制台命令行执行这些任务。

在使用适用于 Oracle 数据库的插件之前， SnapCenter 管理员应安装和配置 SnapCenter 服务器并执行前提条件任务。

* 安装和配置 SnapCenter 服务器。 link:../install/task_install_the_snapcenter_server_using_the_install_wizard.html["了解更多信息。"^]
* 通过添加存储系统连接来配置 SnapCenter 环境。 link:../install/task_add_storage_systems.html["了解更多信息。"^]
+

NOTE: SnapCenter 不支持在不同集群上使用相同名称的多个 SVM 。使用 SVM 注册或集群注册向 SnapCenter 注册的每个 SVM 都必须是唯一的。

* 为安装用户创建身份验证模式为 Linux 或 AIX 的凭据。 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#set-up-credentials["了解更多信息。"^]
* 添加主机，安装插件以及发现资源。
* 如果您使用 SnapCenter 服务器保护驻留在 VMware RDM LUN 或 VMDK 上的 Oracle 数据库，则必须部署适用于 VMware vSphere 的 SnapCenter 插件并向 SnapCenter 注册此插件。
* 在 Linux 或 AIX 主机上安装 Java 。
+
请参见 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#linux-host-requirements["Linux 主机要求"^] 或  有关详细信息 ...

* 您应将应用程序防火墙的超时值设置为 3 小时或更长时间。
* 如果在 NFS 环境中使用 Oracle 数据库，则必须至少为主存储或二级存储配置一个 NFS 数据 LIF ，才能执行挂载，克隆，验证和还原操作。
* 如果您有多个数据路径（ LIF ）或 DNFS 配置，则可以在数据库主机上使用 SnapCenter 命令行界面执行以下操作：
+
** 默认情况下，数据库主机的所有 IP 地址都会添加到 Storage Virtual Machine （ SVM ）中克隆卷的 NFS 存储导出策略中。如果要使用特定的 IP 地址或限制为部分 IP 地址，请运行 Set-PreferredHostIPsInStorageExportPolicy CLI 。
** 如果 SVM 中有多个数据路径（ LIF ），则 SnapCenter 会选择适当的数据路径（ LIF ）来挂载 NFS 克隆卷。但是，如果要指定特定数据路径（ LIF ），则必须运行 Set-SvmPreferredDataPath CLI 。命令参考指南提供了更多信息。


* 如果在 SAN 环境中使用 Oracle 数据库，请确保按照以下指南中所述的建议配置 SAN 环境：
+
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547957["Linux Unified Host Utilities 的建议主机设置"^]
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["将 Linux 主机与 ONTAP 存储结合使用"^]
** https://library.netapp.com/ecm/ecm_download_file/ECMP1119218["受 AIX Host Utilities 影响的主机设置"^]


* 如果 Oracle 数据库位于 Oracle Linux 或 RHEL 操作系统中的 LVM 上，请安装最新版本的逻辑卷管理（ LVM ）。
* 如果您使用的是适用于 Oracle 的 SnapManager ，并且希望迁移到适用于 Oracle 数据库的 SnapCenter 插件，则可以使用 sccli 命令 sc-migrate 将配置文件迁移到 SnapCenter 的策略和资源组。
* 如果要进行备份复制，请在 ONTAP 上配置 SnapMirror 和 SnapVault


对于 SnapCenter 4.1.1 用户，适用于 VMware vSphere 的 SnapCenter 插件 4.1.1 文档提供了有关保护虚拟化数据库和文件系统的信息。对于 SnapCenter 4.2.x 用户，即 NetApp Data Broker 1.0 和 1.0.1 ，文档提供了有关使用适用于 VMware vSphere 的 SnapCenter 插件保护虚拟化数据库和文件系统的信息，该插件由基于 Linux 的 NetApp 数据代理虚拟设备（开放式虚拟设备格式）提供。对于 SnapCenter 4.3.x 用户，适用于 VMware vSphere 的 SnapCenter 插件 4.3 文档提供了有关使用适用于 VMware vSphere 的基于 Linux 的 SnapCenter 插件虚拟设备（开放式虚拟设备格式）保护虚拟化数据库和文件系统的信息。

* 查找更多信息 *

* https://mysupport.netapp.com/matrix/imt.jsp?components=100747;&solution=1257&isHWU&src=IMT["互操作性表工具"^]
* https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/index.html["适用于 VMware vSphere 的 SnapCenter 插件文档"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Data_protection_operation_fails_in_a_non-multipath_environment_in_RHEL_7_and_later["在 RHEL 7 及更高版本的非多路径环境中，数据保护操作失败"^]

