---
permalink: protect-sco/concept_snapcenter_plug_in_for_oracle_database_features.html 
sidebar: sidebar 
keywords: plug-in for Oracle features 
summary: 适用于 Oracle 数据库的插件可与 Linux 或 AIX 主机上的 Oracle 数据库以及存储系统上的 NetApp 技术集成。 
---
= 适用于 Oracle 数据库的插件的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于 Oracle 数据库的插件可与 Linux 或 AIX 主机上的 Oracle 数据库以及存储系统上的 NetApp 技术集成。

* 统一图形用户界面
+
SnapCenter 界面可在插件和环境之间实现标准化和一致性。通过 SnapCenter 界面，您可以跨插件完成一致的备份，还原，恢复和克隆操作，使用集中式报告，使用信息板概览视图，设置基于角色的访问控制（ Role-Based Access Control ， RBAC ）以及监控所有插件中的作业。

* 自动化中央管理
+
您可以计划备份和克隆操作，配置基于策略的备份保留以及执行还原操作。您还可以通过配置 SnapCenter 以发送电子邮件警报来主动监控您的环境。

* 无中断NetApp Snapshot技术
+
SnapCenter将NetApp快照技术与适用于Oracle数据库的插件和适用于UNIX的插件结合使用来备份数据库。快照占用的存储空间最少。



适用于 Oracle 数据库的插件还具有以下优势：

* 支持备份，还原，克隆，挂载，卸载， 和验证工作流
* 自动发现主机上配置的 Oracle 数据库
* 支持使用 Oracle Recovery Manager （ RMAN ）进行目录编制和取消目录编制
* 支持 RBAC 的安全性和集中式角色委派
+
您还可以设置凭据，以便授权的 SnapCenter 用户具有应用程序级别的权限。

* 支持使用归档日志管理(ALM)执行还原和克隆操作
* 使用 NetApp FlexClone 技术为生产数据库创建节省空间的时间点副本，以供测试或数据提取
+
要创建克隆的存储系统需要 FlexClone 许可证。

* 在 SAN 和 ASM 环境中创建备份时，支持 ONTAP 的一致性组（ Consistency Group ， CG ）功能
* 无中断自动备份验证
* 能够在多个数据库主机之间同时运行多个备份
+
在单个操作中、如果单个主机中的数据库共享同一个卷、则会整合Snapshot。

* 支持物理和虚拟化基础架构
* 支持 NFS ， iSCSI ，光纤通道（ FC ）， RDM ，基于 NFS 和 VMFS 的 VMDK 以及基于 NFS ， SAN ， RDM 和 VMDK 的 ASM
* 支持 ONTAP 的选择性 LUN 映射（ SLM ）功能
+
默认情况下， SLM 功能会定期发现没有优化路径的 LUN 并对其进行修复。您可以通过修改位于 /var/opt/snapcenter/scU/etc 的 scu.properties 文件中的参数来配置 SLM

+
** 您可以通过将enable_lunpath_monitoring参数的值设置为false来禁用此功能。
** 您可以通过为lunpath_monitoring_interval参数分配值(以小时为单位)来指定自动修复LUN路径的频率。有关 SLM 的信息，请参见 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["《 ONTAP 9 SAN 管理指南》"^]。


* 在Linux上支持非易失性内存快速(NVMe)
+
** 应在主机上安装NVMe util。
+
您必须安装NVMe util才能克隆或挂载到备用主机。

** 备份、还原、克隆、挂载、卸载、 NVMe硬件支持目录、取消目录和验证操作、但VMDK和RDM等虚拟化环境除外。
+
不带分区或具有单个分区的设备支持上述操作。






NOTE: 您可以通过在内核中设置原生 多路径选项来为NVMe设备配置多路径解决方案。不支持设备映射程序(Device Mapper、DM)多路径。

* 支持任何非默认用户、而不是Oracle和GRID。
+
要支持非默认用户、您应通过修改位于_file /var/opt/snapcenter/soc/etc/_的* sco.properties*文件中的参数值来设置非默认用户。

+
参数的默认值设置为Oracle和GRID。

+
** DB_USER=Oracle
** DB_Group=oinstall
** gi_user=网格
** gi_Group=oinstall



