---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-restore.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, restore 
summary: 通过 SnapCenter ，您可以在还原数据库时执行预处理和后处理脚本时使用预定义的环境变量。 
---
= 用于还原特定的预处理和后处理的预定义环境变量
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 SnapCenter ，您可以在还原数据库时执行预处理和后处理脚本时使用预定义的环境变量。

* 支持用于还原数据库的预定义环境变量 *

* * 。 sc_job_ID* 指定操作的作业 ID 。
+
示例： 257

* *SC_ORACLE_SID* 指定数据库的系统标识符。
+
如果此操作涉及多个数据库，则此名称将包含由管道分隔的数据库名称。

+
示例： NFS31

* *SC_HOST* 指定数据库的主机名。
+
将为应用程序卷填充此参数。

+
示例： scsmohost2.gdl.englabe.netapp.com

* *SC_OS_USER* 指定数据库的操作系统所有者。
+
示例： Oracle

* *SC_OS_Group* 指定数据库的操作系统组。
+
示例： oinstall

* * sc_backup_name* 用于指定备份的名称。
+
将为应用程序卷填充此参数。

+
示例

+
** 如果数据库未在 ARCHIVELOG 模式下运行： DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267 0_LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267
** 如果数据库在 ARCHIVELOG 模式下运行： DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267 0_LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267 ； 1 ， Rg2_scspr2417819002_07-21-2021_12.16.48.9267_1 ， Rg2_scspr2417819002_07-22-2021_12.16.48.9267_1


* * sc_backup_ID* 用于指定备份的 ID 。
+
将为应用程序卷填充此参数。

+
示例

+
** 如果数据库未在 ARCHIVELOG 模式下运行： data@203| log@205
** 如果数据库在 ARCHIVELOG 模式下运行： data@203| log@205 ， 206 ， 207


* * sc_resource_Group_name* 用于指定资源组的名称。
+
示例： RG1

* *SC_ORACLE_HOME* 指定 Oracle 主目录的路径。
+
示例： /ora01/app/oracle/product/181.0/db_1

* * sc_recovery_type* 用于指定已恢复的文件以及恢复范围。
+
示例： RESTORESCOPE ： usingBackupControlfile=false=RECOVERYSCOPE ： allLogs=true ， noLogs=false ， UntisTime=false ， untisscn=false 。



有关分隔符的信息，请参见 link:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["支持的分隔符"^]。
