---
permalink: protect-sco/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux.html 
sidebar: sidebar 
keywords: SnapCenter, host requirement for Linux, sudo privileges, non-root user 
summary: 在安装适用于 Linux 的 SnapCenter 插件软件包之前，应确保主机满足要求。 
---
= 安装适用于 Linux 的插件软件包的主机要求
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装适用于 Linux 的 SnapCenter 插件软件包之前，应确保主机满足要求。

|===
| 项目 | 要求 


 a| 
操作系统
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
+

NOTE: 如果在 Oracle Linux 或 Red Hat Enterprise Linux 6.6 或 7.0 操作系统的 LVM 上使用 Oracle 数据库，则必须安装最新版本的逻辑卷管理器（ LVM ）。

* SUSE Linux Enterprise Server （ SLES ）




 a| 
主机上 SnapCenter 插件的最小 RAM
 a| 
1 GB



 a| 
主机上 SnapCenter 插件的最小安装和日志空间
 a| 
2 GB


NOTE: 您应分配足够的磁盘空间并通过 logs 文件夹监控存储消耗。所需的日志空间因要保护的实体数量和数据保护操作的频率而异。如果没有足够的磁盘空间，则不会为最近运行的操作创建日志。



 a| 
所需的软件包
 a| 
Java 1.8.x （ 64 位） Oracle Java 和 OpenJDK 版本

如果已将 Java 升级到最新版本，则必须确保 /var/opt/snapcenter/spl/etc/spl.properties 上的 java_home 选项设置为正确的 Java 版本和路径。

|===
有关受支持版本的最新信息，请参见 http://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]。



== 为 Linux 插件主机的非 root 用户配置 sudo 权限

通过 SnapCenter 2.0 及更高版本，非 root 用户可以安装适用于 Linux 的 SnapCenter 插件软件包并启动插件过程。您应为非 root 用户配置 sudo 权限，以提供对多个路径的访问权限。

* 您需要的内容 *

* sudo 1.8.7 或更高版本。
* 确保非 root 用户属于 Oracle 安装组。
* 编辑 /etc/ssh/sshd_config_ 文件以配置消息身份验证代码算法： macs HMAC-SHA2-256 和 MAC HMAC-SHA2-512 。
+
更新配置文件后重新启动 sshd 服务。

+
示例

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


* 关于此任务 *

您应为非 root 用户配置 sudo 权限，以提供对以下路径的访问：

* /home/_sudo _user_//.SC_NetApp/snapcenter_linux_host_plugin.bin
* /custom_location/netapp/snapcenter/spl/installation/plugins/uninstall
* /custom_location/netapp/snapcenter/spl/bin/spl


* 步骤 *

. 登录到要安装适用于 Linux 的 SnapCenter 插件软件包的 Linux 主机。
. 使用 visudo Linux 实用程序将以下行添加到 /etc/sudoers 文件中。
+
[listing, subs="+quotes"]
----
Cmnd_Alias SCCMD = sha224:checksum_value== /home/_SUDO_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall,
/opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_SUDO_USER_/.sc_netapp/Linux_Prechecks.sh
_SUDO_USER_ ALL=(ALL) NOPASSWD:SETENV: SCCMD, PRECHECKCMD
Defaults: _SUDO_USER_ env_keep=JAVA_HOME
Defaults: _SUDO_USER_ !visiblepw
Defaults: _SUDO_USER_ !requiretty
----
+
_sudo _user_ 是您创建的非 root 用户的名称。

+
您可以从 * ORACLE_checksum.txt * 文件中获取校验和值，该文件位于 _C ： \ProgramData\NetApp\SnapCenter\Package Repository_ 。

+
如果指定了自定义位置，则此位置将为 _custom_path\NetApp\SnapCenter\Package Repository_ 。

+

IMPORTANT: 此示例只能用作创建自己数据的参考。



|===


| * 最佳实践： * 出于安全原因，您应在完成每次安装或升级后删除 sudo 条目。 
|===