---
permalink: protect-sco/task_set_up_credentials_for_installing_the_plug_in_package_for_linux_or_aix.html 
sidebar: sidebar 
keywords: credentials, authenticate, domain administrator, local administrator, workgroup, sudo, non-root user, root user 
summary: SnapCenter 使用凭据对 SnapCenter 操作的用户进行身份验证。您应创建在 Linux 或 AIX 主机上安装插件软件包的凭据。 
---
= 设置用于安装适用于 Linux 或 AIX 的插件软件包的凭据
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 使用凭据对 SnapCenter 操作的用户进行身份验证。您应创建在 Linux 或 AIX 主机上安装插件软件包的凭据。

* 关于此任务 *

这些凭据是为 root 用户或具有 sudo 权限的非 root 用户创建的，用于安装和启动插件过程。

有关信息，请参见 link:../protect-sco/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux.html#configuring-sudo-privileges-for-non-root-users-for-linux-plug-in-host["为 Linux 主机配置 sudo 权限"^] 或 。

|===


| * 最佳实践： * 虽然允许您在部署主机和安装插件后创建凭据，但最佳实践是在添加 SVM 之后，在部署主机和安装插件之前创建凭据。 
|===
* 步骤 *

. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 凭据 * 。
. 单击 * 新建 * 。
. 在 Credential 页面中，输入凭据信息：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
凭据名称
 a| 
输入凭据的名称。



 a| 
用户名 / 密码
 a| 
输入要用于身份验证的用户名和密码。

** 域管理员
+
在要安装 SnapCenter 插件的系统上指定域管理员。用户名字段的有效格式为：

+
*** _netbios\username_
*** 域 FQDN\username_


** 本地管理员（仅适用于工作组）
+
对于属于工作组的系统，请指定要安装 SnapCenter 插件的系统上的内置本地管理员。如果用户帐户具有提升的权限或在主机系统上禁用了用户访问控制功能，则可以指定属于本地管理员组的本地用户帐户。用户名字段的有效格式为： _username_





 a| 
身份验证模式
 a| 
选择要使用的身份验证模式。

根据插件主机的操作系统，选择 Linux 或 AIX 。



 a| 
使用 sudo 权限
 a| 
如果要为非 root 用户创建凭据，请选中 * 使用 sudo 权限 * 复选框。

|===
. 单击 * 确定 * 。


完成凭据设置后，您可能需要在 * 用户和访问 * 页面上为用户或用户组分配凭据维护。
