---
permalink: protect-sce/concept_snapcenter_plug_in_for_exchange_server_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Exchange Server 
summary: 适用于 Microsoft Exchange Server 的 SnapCenter 插件是 NetAppSnapCenter 软件的主机端组件，可用于对 Exchange 数据库进行应用程序感知型数据保护管理。适用于 Exchange 的插件可自动备份和还原 SnapCenter 环境中的 Exchange 数据库。 
---
= 适用于 Microsoft Exchange Server 的 SnapCenter 插件概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
适用于 Microsoft Exchange Server 的 SnapCenter 插件是 NetApp SnapCenter 软件的主机端组件，可用于对 Exchange 数据库进行应用程序感知型数据保护管理。适用于 Exchange 的插件可自动备份和还原 SnapCenter 环境中的 Exchange 数据库。

安装适用于 Exchange 的插件后，您可以使用采用 NetApp SnapMirror 技术的 SnapCenter 在另一个卷上创建备份集的镜像副本，并使用 NetApp SnapVault 技术执行磁盘到磁盘备份复制，以满足标准合规性或归档要求。

如果要还原和恢复邮件或邮箱，而不是整个 Exchange 数据库，则可以使用 Single Mailbox Recovery （ SMBR ）软件。
NetApp®Single Mailbox Recovery已于2023年5月12日终止提供(EOA)。在支持授权期间、NetApp将继续通过2020年6月24日推出的营销部件号为已购买邮箱容量、维护和支持的客户提供支持。

NetApp Single Mailbox Recovery是Ontrack提供的合作伙伴产品。Ontrack PowerControls提供的功能与NetApp Single Mailbox Recovery类似。客户可以从Ontrack (通过licensingteam@ontrack.com)购买新的Ontrack PowerControls软件许可证以及Ontrack PowerControls维护和支持续订、以实现精细邮箱恢复。

适用于Exchange的插件支持SnapMirror活动同步(最初作为SnapMirror Business Continuing [SM-BC)发布)、即使在站点完全瘫痪时、业务服务也能继续运行、从而支持应用程序使用二级副本透明地进行故障转移。使用SnapMirror活动同步触发故障转移无需手动干预或额外编写脚本。

它支持SnapMirror活动同步的非对称、故障转移或非双工模式。这是指优化路径仅来自主端LUN所属节点的解决方案。通过将二级集群路径上的任何I/O代理到主集群来提供这些I/O。同步复制是单向的、从主复制到二级复制。

* 为 SnapCenter 环境中的 Microsoft Exchange Server 数据库和数据库可用性组（ DAG ）自动执行应用程序感知型备份和还原操作
* 在部署适用于VMware vSphere的SnapCenter插件并向SnapCenter注册此插件时、支持在RDM LUN上使用虚拟化的Exchange Server。

