---
permalink: protect-sce/reference_prerequisites_to_add_hosts_and_install_snapcenter_plug_in_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords:  
summary: 在添加主机并安装插件软件包之前，您必须满足所有要求。 
---
= 添加主机和安装适用于 Microsoft Exchange Server 的 SnapCenter 插件的前提条件
:icons: font
:imagesdir: ../media/


[role="lead"]
在添加主机并安装插件软件包之前，您必须满足所有要求。

* 如果使用的是 iSCSI ，则 iSCSI 服务必须正在运行。
* 您必须具有具有本地管理员权限的域用户，并在远程主机上具有本地登录权限。
* 您必须对独立和数据库可用性组配置使用 Microsoft Exchange Server 2013 ， 2016 或 2019 。
* 在 Windows 主机上安装插件时，如果您指定的凭据不是内置的，或者用户属于本地工作组用户，则必须在主机上禁用 UAC 。
* 如果您在 SnapCenter 中管理集群节点，则必须具有对集群中所有节点具有管理权限的用户。
* 您必须具有对 Exchange Server 具有管理权限的用户。
* 如果已安装 SnapManager for Microsoft Exchange Server 和 SnapDrive for Windows ，则必须先注销 SnapDrive for Windows 使用的 VSS 硬件提供程序，然后才能在同一 Exchange Server 上安装适用于 Exchange 的插件，以确保使用 SnapCenter 成功保护数据。
* 如果 SnapManager for Microsoft Exchange Server 和 Plug-in for Exchange 安装在同一台服务器上，则必须暂停或从 Windows 计划程序中删除 SnapManager for Microsoft Exchange Server 创建的所有计划。
* 主机必须可从服务器解析为完全限定域名（ FQDN ）。如果修改了 hosts 文件以使其可解析，并且在 hosts 文件中同时指定了短名称和 FQDN ，请在 SnapCenter hosts 文件中以以下格式创建一个条目： _<IP_address> <host_FQDN> <host_name>_ 。
* 确保防火墙中未阻止以下端口，否则添加主机操作将失败。要解决此问题描述，请配置动态端口范围。有关详细信息，请参见 https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-rpc-dynamic-port-allocation-with-firewalls["Microsoft 文档"^]。
+
** 对于 Windows 2016 和 Exchange 2016 ，端口范围为 50000 - 51000
** 对于 Windows 2012 R2 和 Exchange 2013 ，端口范围为 6000 - 6500
** 对于 Windows 2019 ，端口范围为 49152 - 65536



