---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 在创建备份作业之前定义备份策略有助于确保您拥有成功还原数据库所需的备份。您的服务级别协议（ Service Level Agreement ， SLA ），恢复时间目标（ Recovery Time Objective ， RTO ）和恢复点目标（ Recovery Point Objective ， RPO ）在很大程度上决定了您的备份策略。 
---
= 为 Exchange Server 资源定义备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建备份作业之前定义备份策略有助于确保您拥有成功还原数据库所需的备份。您的服务级别协议（ Service Level Agreement ， SLA ），恢复时间目标（ Recovery Time Objective ， RTO ）和恢复点目标（ Recovery Point Objective ， RPO ）在很大程度上决定了您的备份策略。

SLA 定义了预期的服务级别，并解决了许多与服务相关的问题，包括服务的可用性和性能。RTO 是指服务中断后必须恢复业务流程的时间。RPO 定义了必须从备份存储中恢复的文件的使用期限策略，以便在发生故障后恢复常规操作。SLA ， RTO 和 RPO 有助于制定备份策略。



== Exchange 数据库支持的备份类型

使用 SnapCenter 备份 Exchange 邮箱要求您选择资源类型，例如数据库和数据库可用性组（ DAG ）。Snapshot 副本技术用于为资源所在的卷创建联机只读副本。

|===
| 备份类型 | Description 


 a| 
完整备份和日志备份
 a| 
备份数据库和所有事务日志，包括截断的日志。

完整备份完成后， Exchange Server 会截断已提交到数据库的事务日志。

通常，您应选择此选项。但是，如果备份时间较短，您可以选择不在执行完整备份的情况下运行事务日志备份。



 a| 
完整备份
 a| 
备份数据库和事务日志。

不会备份截断的事务日志。



 a| 
日志备份
 a| 
备份所有事务日志。

不会备份已提交到数据库的截断日志。如果您计划在完全数据库备份之间频繁备份事务日志，则可以选择粒度恢复点。

|===


== 数据库插件的备份计划

备份频率（计划类型）在策略中指定；备份计划在资源组配置中指定。在确定备份频率或计划时，最关键的因素是资源的更改率以及数据的重要性。您可以每小时备份一次使用率较高的资源，而每天备份一次很少使用的资源。其他因素包括资源对组织的重要性，服务级别协议（ Service Level Agreement ， SLA ）和恢复点目标（ Recovery Point Objective ， RPO ）。

SLA 定义了预期的服务级别，并解决了许多与服务相关的问题，包括服务的可用性和性能。RPO 定义了必须从备份存储中恢复的文件的使用期限策略，以便在发生故障后恢复常规操作。SLA 和 RPO 有助于制定数据保护策略。

即使对于使用率较高的资源，也不需要每天运行一次或两次以上的完整备份。例如，定期事务日志备份可能足以确保您拥有所需的备份。备份数据库的频率越高， SnapCenter 在还原时必须使用的事务日志就越少，从而可以加快还原操作的速度。

备份计划分为两部分，如下所示：

* 备份频率
+
备份频率（执行备份的频率）（对于某些插件称为 _schedule type_ ）是策略配置的一部分。您可以选择每小时，每天，每周或每月作为策略的备份频率。如果不选择其中任何频率，则创建的策略是一个按需策略。您可以单击 * 设置 * > * 策略 * 来访问策略。

* 备份计划
+
备份计划（恰好在执行备份的时间）是资源组配置的一部分。例如，如果您的资源组配置了每周备份的策略，则可以将该计划配置为每星期四晚上 10 ： 00 进行备份。您可以通过单击 * 资源 * > * 资源组 * 来访问资源组计划。





== 数据库所需的备份作业数

决定所需备份作业数量的因素包括资源大小，已用卷数，资源更改率以及您的服务级别协议（ Service Level Agreement ， SLA ）。



== 备份命名约定

您可以使用默认 Snapshot 副本命名约定，也可以使用自定义命名约定。默认备份命名约定会为 Snapshot 副本名称添加一个时间戳，以帮助您确定副本的创建时间。

Snapshot 副本使用以下默认命名约定：

`resourcegroupname_hostname_timestamp`

您应按逻辑方式命名备份资源组，如以下示例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在此示例中，语法元素具有以下含义：

* _dts1_ 是资源组名称。
* _mach1X88_ 是主机名。
* _03-12-2015_23.17.26_ 是日期和时间戳。


或者，您也可以通过选择 * 对 Snapshot 副本使用自定义名称格式 * 来在保护资源或资源组时指定 Snapshot 副本名称格式。例如， customtext_resourcegroup_policy_hostname 或 resourcegroup_hostname 。默认情况下，时间戳后缀会添加到 Snapshot 副本名称中。



== 备份保留选项

您可以选择保留备份副本的天数，也可以指定要保留的备份副本数， ONTAP 最多可保留 255 个副本。例如，您的组织可能要求您保留 10 天的备份副本或 130 个备份副本。

创建策略时，您可以为备份类型和计划类型指定保留选项。

如果设置了 SnapMirror 复制，则保留策略将在目标卷上镜像。

SnapCenter 会删除保留标签与计划类型匹配的保留备份。如果更改了资源或资源组的计划类型，则具有旧计划类型标签的备份可能仍会保留在系统上。


NOTE: 要长期保留备份副本，应使用 SnapVault 备份。



== 在 Exchange Server 的源存储卷上保留事务日志备份的时间

适用于 Microsoft Exchange Server 的 SnapCenter 插件需要事务日志备份来执行最新的还原操作，以便将数据库还原到两个完整备份之间的时间。

例如，如果适用于 Exchange 的插件在上午 8 ： 00 执行完整备份 + 事务日志备份而另一个完整的 + 事务日志备份则在下午 5 ： 00 进行，它可以使用最新的事务日志备份将数据库还原到上午 8 ： 00 之间的任何时间和下午 5 ： 00如果事务日志不可用，则适用于 Exchange 的插件只能执行时间点还原操作，从而将数据库还原到适用于 Exchange 的插件完成完整备份时为止。

通常，您只需要一天或两天的最新还原操作。默认情况下， SnapCenter 至少保留两天。
