---
permalink: protect-sce/task_install_the_snapcenter_plug_in_for_exchange_silently_from_the_command_line.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 您应从 SnapCenter 用户界面中安装适用于 Exchange 的插件。但是，如果由于某种原因而无法运行此插件，则可以通过 Windows 命令行在无人参与的情况下以静默模式运行适用于 Exchange 的插件安装程序。 
---
= 通过命令行以静默方式安装适用于 Exchange 的 SnapCenter 插件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应从 SnapCenter 用户界面中安装适用于 Exchange 的插件。但是，如果由于某种原因而无法运行此插件，则可以通过 Windows 命令行在无人参与的情况下以静默模式运行适用于 Exchange 的插件安装程序。

.开始之前
* 您必须已备份 Microsoft Exchange Server 资源。
* 您必须已安装 SnapCenter 插件软件包。
* 在安装之前，必须删除适用于 Microsoft SQL Server 的早期版本的 SnapCenter 插件。
+
有关详细信息，请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host["如何手动或直接从插件主机安装 SnapCenter 插件"^]。



.步骤
. 验证插件主机上是否存在 _C ： \temp_ 文件夹，并且已登录用户是否具有对该文件夹的完全访问权限。
. 从 _C ： \ProgramData\NetApp\SnapCenter\Package_ 存储库下载适用于 Microsoft Windows 的 SnapCenter 插件。
+
可以从安装了 SnapCenter 服务器的主机访问此路径。

. 将安装文件复制到要安装此插件的主机。
. 在本地主机上的 Windows 命令提示符处，导航到保存插件安装文件的目录。
. 输入以下命令以安装此插件。
+
_snapcenter_windows_host_plugin.exe"/silent /debuglog"<debug_Log_Path>" /log"<Log_Path>" BI_SNAPCENTER_port=<Num>suite_INSTALLDIR="<Install_Directory_Path>" BI_SERVERCACCOUNT=<domain\administrator> ， STAW=<IFICW> ， STAW=<IFORE>

+
例如：

+
_C ： \ProgramData\NetApp\SnapCenter\Package Repository\snapcenter_windows_host_plugin.exe "/silent /debuglog"C ： \HPPW_SCSQL_Install.log /log"C ： \temp" BI_SNFeatureAPCTER_port=8145 suite_INSTALLDIR="C ： \Program Files\SCSQL_Install.log" /SnapCenter=Microsoft ， SnapICBI_CSEBI_SERVER_SERVER_SERVER=8145 SUPPICBI_INSTALLDISCBI=C

+

NOTE: 在安装适用于 Exchange 的插件期间传递的所有参数都区分大小写。

+
为变量输入以下值：

+
|===
| 变量 | 价值 


 a| 
_/debuglog"<debug_Log_Path>_
 a| 
指定套件安装程序日志文件的名称和位置，如以下示例所示：

_Setup.exe /debuglog"C ： \PathToLog\setupexe.log_



 a| 
BI_SNAPCENTER_PORT
 a| 
指定 SnapCenter 与 SMCore 通信所使用的端口。



 a| 
suite_INSTALLDIR
 a| 
指定主机插件软件包安装目录。



 a| 
BI_SERVERICEACCOUNT
 a| 
指定适用于 Microsoft Windows 的 SnapCenter 插件 Web 服务帐户。



 a| 
BI_SERVERICEPWD
 a| 
指定适用于 Microsoft Windows 的 SnapCenter 插件 Web 服务帐户的密码。



 a| 
ISFeatureInstall
 a| 
指定 SnapCenter 要在远程主机上部署的解决方案。

|===
. 监控 Windows 任务计划程序，主安装日志文件 _C ： \Installdebug.log_ 以及 _C ： \Temp_ 中的其他安装文件。
. 监控 _%temp%_ 目录，检查 _msiexe.exe_ 安装程序是否在安装软件时没有错误。
+

NOTE: 安装适用于 Exchange 的插件会在主机上注册此插件，而不是在 SnapCenter 服务器上注册此插件。您可以通过使用 SnapCenter 图形用户界面或 PowerShell cmdlet 添加主机来在 SnapCenter 服务器上注册此插件。添加主机后，系统将自动发现此插件。


