---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords:  
summary: 您可以在使用 SnapCenter 备份 Microsoft Exchange Server 资源之前为 Exchange 资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。 
---
= 为 Exchange Server 数据库创建备份策略
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用 SnapCenter 备份 Microsoft Exchange Server 资源之前为 Exchange 资源或资源组创建备份策略，也可以在创建资源组或备份单个资源时创建备份策略。

* 您需要的内容 *

* 您必须已定义数据保护策略。
+
有关详细信息，请参见有关为 Exchange 数据库定义数据保护策略的信息。

* 您必须已通过完成安装 SnapCenter ，添加主机，识别资源以及创建存储系统连接等任务为数据保护做好准备。
* 您必须已刷新（发现） Exchange Server 资源。
* 如果要将 Snapshot 副本复制到镜像或存储， SnapCenter 管理员必须已为源卷和目标卷分配 Storage Virtual Machine （ SVM ）。
* 如果要在预处理脚本和后处理脚本中运行 PowerShell 脚本，应在 `web.config` 文件中将 `usePowershellProcessforScripts` 参数的值设置为 true 。
+
默认值为 false 。



* 关于此任务 *

备份策略是一组规则，用于控制如何管理和保留备份以及备份资源或资源组的频率。此外，您还可以指定脚本设置。在策略中指定选项可节省将策略重复用于其他资源组的时间。

完整备份保留是特定于给定策略的。使用策略 A 且完整备份保留为 4 的数据库或资源会保留 4 个完整备份，并且不会对同一数据库或资源的策略 B 产生影响，该策略可能会保留 3 个完整备份。

日志备份保留在各个策略中有效，并对数据库或资源的所有日志备份进行适用场景。因此，使用策略 B 执行完整备份时，日志保留设置会影响策略 A 在同一数据库或资源上创建的日志备份。同样，策略 A 的日志保留设置也会影响策略 B 在同一数据库上创建的日志备份。

|===


| * 最佳实践： * 最好根据要保留的完整备份和日志备份总数配置二级保留策略。在配置二级保留策略时，请注意，如果数据库和日志位于不同的卷中，则每个备份可以包含三个 Snapshot 副本，而数据库和日志位于同一个卷中，则每个备份可以包含两个 Snapshot 副本。 
|===
* 步骤 *

. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 策略 * 。
. 单击 * 新建 * 。
. 在名称页面上，输入策略名称和问题描述。
. 在备份类型页面上，执行以下步骤：
+
.. 选择备份类型：
+
|===
| 如果您要 ... | 执行此操作 ... 


 a| 
备份数据库文件和所需的事务日志
 a| 
选择 * 完整备份和日志备份 * 。

数据库会通过日志截断进行备份，并备份所有日志，包括截断的日志。


NOTE: 这是建议的备份类型。



 a| 
备份数据库文件和未提交的事务日志
 a| 
选择 * 完整备份 * 。

数据库会通过日志截断进行备份，而截断的日志不会进行备份。



 a| 
备份所有事务日志
 a| 
选择 * 日志备份 * 。

活动文件系统上的所有事务日志都会进行备份，并且不会发生日志截断。

在与实时日志相同的磁盘上创建 _scebackupinfo_ 目录。此目录包含指向 Exchange 数据库增量更改的指针，它与完整的日志文件并不等效。



 a| 
备份所有数据库文件和事务日志，而不截断事务日志文件
 a| 
选择 * 复制备份 * 。

所有数据库和所有日志都会进行备份，并且不会发生日志截断。通常，您可以使用此备份类型来重新获取副本或测试或诊断问题。

|===
+

NOTE: 您应根据完整备份保留而不是基于分钟内（ UTM ）保留来定义日志备份所需的空间。

.. 在 Database Availability Group Settings 部分中，选择一项操作：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
备份活动副本
 a| 
选择此选项可仅备份选定数据库的活动副本。

对于数据库可用性组（ DAG ），此选项仅备份 DAG 中所有数据库的活动副本。

不会备份被动副本。



 a| 
备份服务器上的副本，以便在创建备份作业时选择
 a| 
选择此选项可备份选定服务器上的任何数据库副本，包括活动和被动。

对于 DAG ，此选项会备份选定服务器上所有数据库的活动副本和被动副本。

|===
+

NOTE: 在集群配置中，备份会根据策略中设置的保留设置保留在集群的每个节点上。如果集群的所有者节点发生更改，则会保留先前所有者节点的备份。此保留仅适用于节点级别。

.. 在计划频率部分中，选择一个或多个频率类型： * 按需 * ， * 每小时 * ， * 每日 * ， * 每周 * 和 * 每月 * 。
+

NOTE: 您可以在创建资源组时为备份操作指定计划（开始日期，结束日期）。这样，您可以创建共享相同策略和备份频率的资源组，但可以为每个策略分配不同的备份计划。

+

NOTE: 如果您已计划凌晨 2 ： 00 ，则在夏令时（ DST ）期间不会触发此计划。



. 在保留页面上，配置保留设置。
+
显示的选项取决于您先前选择的备份类型和频率类型。

+

NOTE: 对于 ONTAP 9.4 或更高版本上的资源，最大保留值为 1018 ，对于 ONTAP 9.3 或更早版本上的资源，最大保留值为 254 。如果将保留设置为高于底层 ONTAP 版本支持的值，则备份将失败。

+

IMPORTANT: 如果计划启用 SnapVault 复制，则必须将保留计数设置为 2 或更高。如果将保留数量设置为 1 ，则保留操作可能会失败，因为第一个 Snapshot 副本是 SnapVault 关系的参考 Snapshot 副本，直到将较新的 Snapshot 副本复制到目标。

+
.. 在日志备份保留设置部分中，选择以下选项之一：
+
|===
| 如果您要 ... | 执行此操作 ... 


 a| 
仅保留特定数量的日志备份
 a| 
选择 * 保留日志的完整备份数 * ，并指定要在分钟内还原的完整备份数。

通过完整备份或日志备份创建的实时（ UTM ）保留适用场景日志备份。例如，如果将 UTM 保留设置配置为保留最后 5 个完整备份的日志备份，则最后 5 个完整备份的日志备份将保留下来。

作为完整备份和日志备份的一部分创建的日志文件夹会作为 UTM 的一部分自动删除。您不能手动删除日志文件夹。例如，如果保留设置为 Full 或 Full ，日志备份设置为 1 个月，而 UTM 保留设置为 10 天，则作为这些备份一部分创建的日志文件夹将根据 UTM 被删除。因此，只会有 10 天的日志文件夹，所有其他备份都标记为时间点还原。

如果您不想执行最新的还原，可以将 UTM 保留值设置为 0 。这将启用时间点还原操作。

* 最佳实践： * 最佳做法是，此设置必须等于完整备份保留设置部分中 Snapshot 副本总数（完整备份）的设置。这样可以确保每次完整备份都保留日志文件。



 a| 
将备份副本保留特定天数
 a| 
选择 * 保留日志备份作为最后一个 * 选项，并指定保留日志备份副本的天数。

日志备份会保留到完整备份的天数。

|===
+
如果您选择 * 日志备份 * 作为备份类型，则日志备份将作为完整备份的最新保留设置的一部分保留。

.. 在完整备份保留设置部分中，为按需备份选择以下选项之一，然后为完整备份选择一项：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
仅保留特定数量的 Snapshot 副本
 a| 
如果要指定要保留的完整备份数，请选择 * 要保留的 Snapshot 副本总数 * 选项，并指定要保留的 Snapshot 副本数（完整备份）。

如果完整备份数超过指定数量，则会删除超过指定数量的完整备份，并首先删除最旧的副本。



 a| 
将完整备份保留特定天数
 a| 
选择 * 将 Snapshot 副本保留 * 选项，并指定保留 Snapshot 副本（完整备份）的天数。

|===
+

NOTE: 如果您的数据库在 DAG 配置中的主机上仅具有日志备份，而没有完整备份，则日志备份将按以下方式保留：

+
*** 默认情况下， SnapCenter 会在 DAG 中的所有其他主机中查找此数据库的最旧完整备份，并删除此主机上在完整备份之前创建的所有日志备份。
*** 通过在 _C ： \Program Files\NetApp\SnapCenter WebApp\web.config 文件中添加 * MaxLogBackupOnlyCountWithoutFullBackup* 密钥，您可以仅使用日志备份覆盖 DAG 中主机上数据库的上述默认保留行为。
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
在此示例中，值 10 表示您在主机上最多保留 10 个日志备份。





. 在复制页面上，选择以下一个或两个二级复制选项：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
创建本地 Snapshot 副本后更新 SnapMirror
 a| 
选择此选项可将备份集的镜像副本保留在另一个卷（ SnapMirror ）上。



 a| 
创建本地 Snapshot 副本后更新 SnapVault
 a| 
选择此选项可执行磁盘到磁盘备份复制。



 a| 
二级策略标签
 a| 
选择 Snapshot 标签。

根据您选择的 Snapshot 副本标签， ONTAP 会应用与该标签匹配的二级 Snapshot 副本保留策略。


NOTE: 如果选择了 * 创建本地 Snapshot 副本后更新 Snapmirror* ，则可以选择指定二级策略标签。但是，如果在创建本地 Snapshot 副本之后选择了 * 更新 SnapVault * ，则应指定二级策略标签。



 a| 
错误重试次数
 a| 
输入在进程暂停之前应进行的复制尝试次数。

|===
+

NOTE: 您应在 ONTAP 中为二级存储配置 SnapMirror 保留策略，以避免达到二级存储上 Snapshot 副本的最大限制。

. 在脚本页面上，分别输入应在备份操作前后运行的预处理或后处理程序的路径和参数。
+
** 预录备份参数包括 "` $Database` " 和 "` $ServerInstance` " 。
** PostScript 备份参数包括 "` $Database` " ， "` $ServerInstance` " ， "` $BackupName` " ， "` $LogDirectory` " 和 "` $LogSnapshot` " 。
+
您可以运行脚本来更新 SNMP 陷阱，自动执行警报，发送日志等操作。



. 查看摘要，然后单击 * 完成 * 。

