---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter 使用凭据对 SnapCenter 操作的用户进行身份验证。您应创建用于安装插件软件包的凭据以及用于对数据库执行数据保护操作的其他凭据。 
---
= 设置适用于 Windows 的 SnapCenter 插件的凭据
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 使用凭据对 SnapCenter 操作的用户进行身份验证。您应创建用于安装插件软件包的凭据以及用于对数据库执行数据保护操作的其他凭据。

* 关于此任务 *

您必须设置在 Windows 主机上安装插件的凭据。虽然您可以在部署主机和安装插件后为 Windows 创建凭据，但最佳做法是在添加 SVM 之后，在部署主机和安装插件之前创建凭据。

使用管理员权限设置凭据，包括对远程主机的管理员权限。

如果您为各个资源组设置了凭据，并且用户名不具有完全管理员权限，则必须至少为此用户名分配资源组和备份权限。

* 步骤 *

. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 凭据 * 。
. 单击 * 新建 * 。
+
此时将显示凭据窗口。

. 在凭据页面中，执行以下操作：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
凭据名称
 a| 
输入凭据的名称。



 a| 
Username
 a| 
输入用于身份验证的用户名。

** 域管理员或管理员组的任何成员
+
指定要安装 SnapCenter 插件的系统上的域管理员或管理员组的任何成员。用户名字段的有效格式为：

+
*** `netbios\username`
*** `d域名 FQDN\username`


** 本地管理员（仅适用于工作组）
+
对于属于工作组的系统，请指定要安装 SnapCenter 插件的系统上的内置本地管理员。如果用户帐户具有提升的权限或在主机系统上禁用了用户访问控制功能，则可以指定属于本地管理员组的本地用户帐户。用户名字段的有效格式为： `username`





 a| 
Password
 a| 
输入用于身份验证的密码。



 a| 
身份验证
 a| 
选择 Windows 作为身份验证模式。

|===
. 单击 * 确定 * 。

