---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: 您可以使用 SnapCenter 克隆 Windows 文件系统备份。如果您需要错误删除或更改的单个文件的副本，则可以克隆备份并访问克隆中的该文件。 
---
= 从 Windows 文件系统备份克隆
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SnapCenter 克隆 Windows 文件系统备份。如果您需要错误删除或更改的单个文件的副本，则可以克隆备份并访问克隆中的该文件。

.开始之前
* 您应已准备好通过完成添加主机，识别资源和创建 Storage Virtual Machine （ SVM ）连接等任务来保护数据。
* 您应具有文件系统的备份。
* 您应确保托管卷的聚合应位于 Storage Virtual Machine （ SVM ）的已分配聚合列表中。
* 您不能克隆资源组。您只能克隆单个文件系统备份。
* 如果备份驻留在具有 VMDK 磁盘的虚拟机上，则 SnapCenter 无法将备份克隆到物理服务器。
* 如果克隆 Windows 集群（例如，共享 LUN 或集群共享卷（ CSV ） LUN ），则该克隆将作为专用 LUN 存储在您指定的主机上。
* 对于克隆操作，卷挂载点的根目录不能是共享目录。
* 您不能在不是聚合主节点的节点上创建克隆。
* 您不能为 Windows 文件系统计划重复克隆（克隆生命周期）操作；您只能按需克隆备份。
* 如果将包含克隆的 LUN 移动到新卷，则 SnapCenter 将无法再支持此克隆。例如，您不能使用 SnapCenter 删除该克隆。
* 您不能跨环境克隆。例如，从物理磁盘克隆到虚拟磁盘，反之亦然。


.关于此任务
* 脚本路径使用位于插件主机SMCoreServiceHost.exe配置文件中的预定义WindowsScriptsDirectory密钥进行定义。
+
如果需要、您可以更改此路径并重新启动SMcore服务。建议您使用默认安全路径。

+
可以通过API：API /4.7/configsettings从Swagger显示密钥值

+
您可以使用GET API显示密钥的值。不支持设置API。

* 对于ONTAP 9.12.1及更低版本、在还原过程中从SnapLock存储快照创建的克隆将继承SnapLock存储到期时间。存储管理员应在SnapLock到期时间后手动清理克隆。


[role="tabbed-block"]
====
.SnapCenter UI
--
.步骤
. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 在资源页面中，从列表中选择 * 文件系统 * 。
. 选择主机。
+
如果资源受保护，则会自动显示拓扑视图。

. 从资源列表中，选择要克隆的备份，然后单击克隆图标。
. 在选项页面中，执行以下操作：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
克隆服务器
 a| 
选择应在其中创建克隆的主机。



 a| 
"`自动分配挂载点` " 或 "`自动分配路径` 下的卷挂载点 "
 a| 
选择是自动在路径下分配挂载点还是卷挂载点。

在路径下自动分配卷挂载点：通过路径下的挂载点，您可以提供要在其中创建挂载点的特定目录。在选择此选项之前，您必须验证此目录是否为空。如果目录中存在备份，则在执行挂载操作后，备份将处于无效状态。



 a| 
归档位置
 a| 
如果要克隆二级备份，请选择归档位置。

|===
. 在脚本页面中，指定要执行的任何预处理脚本或后处理脚本。
+

NOTE: 预处理脚本或后处理脚本路径不应包含驱动器或共享。路径应与scripts_path相关。

. 查看摘要，然后单击 * 完成 * 。
. 单击 * 监控 * > * 作业 * 以监控操作进度。


--
.PowerShell cmdlet
--
.步骤
. 使用 Open-SmConnection cmdlet 为指定用户启动与 SnapCenter 服务器的连接会话。
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
. 列出可使用 Get-SmBackup 或 Get-SmResourceGroup cmdlet 克隆的备份。
+
此示例显示有关所有可用备份的信息：

+
[listing]
----
C:\PS>PS C:\> Get-SmBackup

BackupId   BackupName                     BackupTime   BackupType
--------   ----------                     ----------   ----------
1          Payroll Dataset_vise-f6_08...  8/4/2015     Full Backup
                                          11:02:32 AM

2          Payroll Dataset_vise-f6_08...  8/4/2015
                                          11:23:17 AM
----
+
此示例显示有关指定资源组，其资源和关联策略的信息：

+
[listing]
----
PS C:\> Get-SmResourceGroup -ListResources –ListPolicies

Description :
CreationTime : 8/4/2015 3:44:05 PM
ModificationTime : 8/4/2015 3:44:05 PM
EnableEmail : False
EmailSMTPServer :
EmailFrom :
EmailTo :
EmailSubject :
EnableSysLog : False
ProtectionGroupType : Backup
EnableAsupOnFailure : False
Policies : {FinancePolicy}
HostResourceMaping : {}
Configuration : SMCoreContracts.SmCloneConfiguration
LastBackupStatus :
VerificationServer :
EmailBody :
EmailNotificationPreference : Never
VerificationServerInfo : SMCoreContracts.SmVerificationServerInfo
SchedulerSQLInstance :
CustomText :
CustomSnapshotFormat :
SearchResources : False
ByPassCredential : False
IsCustomSnapshot :
MaintenanceStatus : Production
PluginProtectionGroupTypes : {SMSQL}
Name : Payrolldataset
Type : Group
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
ApplySnapvaultUpdate : False
ApplyRetention : False
RetentionCount : 0
RetentionDays : 0
ApplySnapMirrorUpdate : False
SnapVaultLabel :
MirrorVaultUpdateRetryCount : 7
AppPolicies : {}
Description : FinancePolicy
PreScriptPath :
PreScriptArguments :
PostScriptPath :
PostScriptArguments :
ScriptTimeOut : 60000
DateModified : 8/4/2015 3:43:30 PM
DateCreated : 8/4/2015 3:43:30 PM
Schedule : SMCoreContracts.SmSchedule
PolicyType : Backup
PluginPolicyType : SMSQL
Name : FinancePolicy
Type :
Id : 1
Host :
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
CloneLevel : 0
clab-a13-13.sddev.lab.netapp.com
DatabaseGUID :
SQLInstance : clab-a13-13
DbStatus : AutoClosed
DbAccess : eUndefined
IsSystemDb : False
IsSimpleRecoveryMode : False
IsSelectable : True
SqlDbFileGroups : {}
SqlDbLogFiles : {}
AppFileStorageGroups : {}
LogDirectory :
AgName :
Version :
VolumeGroupIndex : -1
IsSecondary : False
Name : TEST
Type : SQL Database
Id : clab-a13-13\TEST
Host : clab-a13-13.sddev.mycompany.com
UserName :
Passphrase :
Deleted : False
Auth : SMCoreContracts.SmAuth
IsClone : False
----
. 使用 New-SmClone cmdlet 从现有备份启动克隆操作。
+
以下示例将使用所有日志从指定备份创建克隆：

+
[listing]
----
PS C:\> New-SmClone
-BackupName payroll_dataset_vise-f3_08-05-2015_15.28.28.9774
-Resources @{"Host"="vise-f3.sddev.mycompany.com";
"Type"="SQL Database";"Names"="vise-f3\SQLExpress\payroll"}
-CloneToInstance vise-f3\sqlexpress -AutoAssignMountPoint
-Suffix _clonefrombackup
-LogRestoreType All -Policy clonefromprimary_ondemand

PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
+
以下示例将为指定的 Microsoft SQL Server 实例创建一个克隆：

+
[listing]
----
PS C:\> New-SmClone
-BackupName "BackupDS1_NY-VM-SC-SQL_12-08-2015_09.00.24.8367"
-Resources @{"host"="ny-vm-sc-sql";"Type"="SQL Database";
"Names"="ny-vm-sc-sql\AdventureWorks2012_data"}
-AppPluginCode SMSQL -CloneToInstance "ny-vm-sc-sql"
-Suffix _CLPOSH -AssignMountPointUnderPath "C:\SCMounts"
----
. 使用 Get-SmCloneReport cmdlet 查看克隆作业的状态。
+
此示例显示指定作业 ID 的克隆报告：

+
[listing]
----
PS C:\> Get-SmCloneReport -JobId 186

SmCloneId : 1
SmJobId : 186
StartDateTime : 8/3/2015 2:43:02 PM
EndDateTime : 8/3/2015 2:44:08 PM
Duration : 00:01:06.6760000
Status : Completed
ProtectionGroupName : Draper
SmProtectionGroupId : 4
PolicyName : OnDemand_Clone
SmPolicyId : 4
BackupPolicyName : OnDemand_Full_Log
SmBackupPolicyId : 1
CloneHostName : SCSPR0054212005.mycompany.com
CloneHostId : 4
CloneName : Draper__clone__08-03-2015_14.43.53
SourceResources : {Don, Betty, Bobby, Sally}
ClonedResources : {Don_DRAPER, Betty_DRAPER, Bobby_DRAPER,
                   Sally_DRAPER}
----


有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《 SnapCenter 软件 cmdlet 参考指南》"^]。

--
====