---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: 在创建备份之前定义备份策略可为您提供成功还原或克隆文件系统所需的备份。您的服务级别协议（ SLA ），恢复时间目标（ RTO ）和恢复点目标（ RPO ）在很大程度上决定了您的备份策略。 
---
= 为 Windows 文件系统定义备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建备份之前定义备份策略可为您提供成功还原或克隆文件系统所需的备份。您的服务级别协议（ SLA ），恢复时间目标（ RTO ）和恢复点目标（ RPO ）在很大程度上决定了您的备份策略。

SLA 定义了预期的服务级别，并解决了许多与服务相关的问题，包括服务的可用性和性能。RTO 是指服务中断后必须恢复业务流程的时间。RPO 定义了必须从备份存储中恢复的文件的使用期限策略，以便在发生故障后恢复常规操作。SLA ， RTO 和 RPO 有助于实施数据保护策略。



== Windows 文件系统的备份计划

备份频率在策略中指定；备份计划在资源组配置中指定。在确定备份频率或计划时，最关键的因素是资源的更改率以及数据的重要性。您可以每小时备份一次使用率较高的资源，而每天备份一次很少使用的资源。其他因素包括资源对组织的重要性，服务级别协议（ Service Level Agreement ， SLA ）和恢复点目标（ Recovery Point Objective ， RPO ）。

SLA 定义了预期的服务级别，并解决了许多与服务相关的问题，包括服务的可用性和性能。RPO 定义了必须从备份存储中恢复的文件的使用期限策略，以便在发生故障后恢复常规操作。SLA 和 RPO 有助于制定数据保护策略。

即使对于使用率较高的资源，也不需要每天运行一次或两次以上的完整备份。

备份计划分为两部分，如下所示：

* 备份频率
+
备份频率（执行备份的频率）（对于某些插件称为 _schedule type_ ）是策略配置的一部分。例如，您可以将备份频率配置为每小时，每天，每周或每月，也可以指定 * 无 * ，以使该策略成为按需策略。您可以单击 * 设置 * > * 策略 * 来访问策略。

* 备份计划
+
备份计划（恰好在执行备份的时间）是资源组配置的一部分。例如，如果您的资源组配置了每周备份的策略，则可以将该计划配置为每星期四晚上 10 ： 00 进行备份。您可以通过单击 * 资源 * > * 资源组 * 来访问资源组计划。





== Windows 文件系统所需的备份数

决定所需备份数量的因素包括 Windows 文件系统的大小，使用的卷数，文件系统的更改率以及您的服务级别协议（ Service Level Agreement ， SLA ）。



== Windows 文件系统的备份命名约定

Windows 文件系统备份使用默认的 Snapshot 副本命名约定。默认备份命名约定会为 Snapshot 副本名称添加一个时间戳，以帮助您确定副本的创建时间。

Snapshot 副本使用以下默认命名约定： resourcegroupname_hostname_timestamp

您应按逻辑方式命名备份资源组，如以下示例所示：

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
在此示例中，语法元素具有以下含义：

* `dTS1` 是资源组名称。
* `mach1X88` 是主机名。
* `03-12-2016_23.17.26` 是日期和时间戳。


创建备份时，您还可以添加一个描述性标记来帮助识别备份。相反，如果要使用自定义备份命名约定，则需要在备份操作完成后重命名备份。



== 备份保留选项

您可以选择保留备份副本的天数，也可以指定要保留的备份副本数， ONTAP 最多可保留 255 个副本。例如，您的组织可能要求您保留 10 天的备份副本或 130 个备份副本。

创建策略时，您可以为备份类型和计划类型指定保留选项。

如果设置了 SnapMirror 复制，则保留策略将在目标卷上镜像。

SnapCenter 会删除保留标签与计划类型匹配的保留备份。如果更改了资源或资源组的计划类型，则具有旧计划类型标签的备份可能仍会保留在系统上。


NOTE: 要长期保留备份副本，应使用 SnapVault 备份。
