---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup policy 
summary: 您可以在使用 SnapCenter 备份 Windows 文件系统之前为资源创建新的备份策略，也可以在创建资源组或备份资源时创建新的备份策略。 
---
= 为 Windows 文件系统创建备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在使用 SnapCenter 备份 Windows 文件系统之前为资源创建新的备份策略，也可以在创建资源组或备份资源时创建新的备份策略。

.开始之前
* 您必须已定义备份策略。 link:task_define_a_backup_strategy_for_windows_file_systems.html["了解更多信息。"^]
* 您必须已做好数据保护准备。
+
要准备数据保护，您必须完成安装 SnapCenter ，添加主机，发现资源以及创建 Storage Virtual Machine （ SVM ）连接等任务。

* 如果要将快照复制到镜像或存储二级存储、则SnapCenter管理员必须已为源卷和目标卷分配SVM。
* 如果要在预处理脚本和后处理脚本中运行 PowerShell 脚本，应在 web.config 文件中将 usePowershellProcessforScripts 参数的值设置为 true 。
+
默认值为 false 。

* 查看SnapMirror主动同步的特定前提条件和限制。有关信息，请参阅 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror活动同步的对象限制"]。


.关于此任务
* 脚本路径使用位于插件主机SMCoreServiceHost.exe配置文件中的预定义WindowsScriptsDirectory密钥进行定义。
+
如果需要、您可以更改此路径并重新启动SMcore服务。建议您使用默认安全路径。

+
可以通过API：API /4.7/configsettings从Swagger显示密钥值

+
您可以使用GET API显示密钥的值。不支持设置API。

* SnapLock
+
** 如果选择了"将备份副本保留特定天数"选项、则SnapLock保留期限必须小于或等于上述保留天数。
** 指定Snapshot锁定期限可防止删除Snapshot、直到保留期限到期为止。这样可能会导致保留的Snapshot数量超过策略中指定的数量。
** 对于ONTAP 9.12.1及更低版本、在还原过程中从SnapLock存储快照创建的克隆将继承SnapLock存储到期时间。存储管理员应在SnapLock到期时间后手动清理克隆。




.步骤
. 在左侧导航窗格中，选择*Settings*。
. 在设置页面中，选择*Policies*。
. 选择*New*。
. 在名称页面中、输入策略名称和详细信息。
. 在备份和复制页面中、执行以下任务：
+
.. 选择备份设置。
+
|===
| 选项 | Description 


 a| 
文件系统一致的备份
 a| 
如果希望 SnapCenter 在备份操作开始之前暂停文件系统所在的磁盘驱动器，然后在备份操作结束后恢复磁盘驱动器，请选择此选项。



 a| 
文件系统崩溃状态一致的备份
 a| 
如果不希望 SnapCenter 暂停文件系统所在的磁盘驱动器，请选择此选项。

|===
.. 选择计划频率（也称为策略类型）。
+
此策略仅指定备份频率。用于备份的特定保护计划在资源组中定义。因此，两个或更多资源组可以共享相同的策略和备份频率，但备份计划不同。

+

NOTE: 如果您已计划凌晨 2 ： 00 ，则在夏令时（ DST ）期间不会触发此计划。

.. 选择策略标签。
+
根据您选择的Snapshot标签、ONTAP会应用与该标签匹配的二级Snapshot保留策略。

+

NOTE: 如果选择了 * 创建本地 Snapshot 副本后更新 Snapmirror* ，则可以选择指定二级策略标签。但是，如果在创建本地 Snapshot 副本之后选择了 * 更新 SnapVault * ，则应指定二级策略标签。



. 在选择二级复制选项部分中、选择以下一个或两个二级复制选项：
+

NOTE: 要使*二级Snapshot副本锁定期限*生效、必须选择二级复制选项。

+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
创建本地 Snapshot 副本后更新 SnapMirror
 a| 
选择此选项可在另一个卷（ SnapMirror ）上创建备份集的镜像副本。

应为SnapSnapMirror活动同步启用此选项。

在二级复制期间、SnapLock到期时间会加载主SnapLock到期时间。单击"Topology"页面中的*Refresh*按钮可刷新从ONTAP检索到的二级和主SnapLock到期时间。

请参见 link:../protect-scw/task_view_related_backups_and_clones_in_the_topology_page.html["在 Topology 页面中查看相关备份和克隆"]。



 a| 
创建 Snapshot 副本后更新 SnapVault
 a| 
选择此选项可执行磁盘到磁盘备份复制。

在二级复制期间、SnapLock到期时间会加载主SnapLock到期时间。单击"Topology"页面中的"Refresh"按钮可刷新从ONTAP检索到的二级和主SnapLock到期时间。

如果仅在ONTAP中称为SnapLock存储的二级系统上配置了SnapLock、则单击"拓扑"页面中的"刷新"按钮可刷新从ONTAP检索到的二级系统上的锁定期限。

有关SnapLock存储的详细信息、请参见 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["将Snapshot副本提交到存储目标上的WORM"]



 a| 
错误重试次数
 a| 
输入在进程暂停之前应进行的复制尝试次数。

|===
+

NOTE: 您应在ONTAP中为二级存储配置SnapMirror保留策略、以避免达到二级存储上Snapshot的最大限制。

. 在保留设置页面中、为按需备份和您选择的每个计划频率指定保留设置。
+
|===
| 选项 | Description 


 a| 
要保留的 Snapshot 副本总数
 a| 
如果要在自动删除快照SnapCenter存储之前指定其数量、请选择此选项。



 a| 
保留 Snapshot 副本
 a| 
如果要指定 SnapCenter 在删除备份副本之前保留备份副本的天数，请选择此选项。



 a| 
主Snapshot副本锁定期限
 a| 
选择Snapshot锁定期限、然后选择天、月或年。

SnapLock保留期限应少于100年。



 a| 
二级Snapshot副本锁定期限
 a| 
选择*二级Snapshot副本锁定期限*、然后选择天、月或年。

|===
+

IMPORTANT: 您应将保留数量设置为2或更高。保留数量的最小值为2。

+

NOTE: 最大保留值为1018。如果将保留设置为高于底层 ONTAP 版本支持的值，则备份将失败。

. 在脚本页面中，输入您希望 SnapCenter 服务器在备份操作前后运行的预处理或后脚本的路径，以及 SnapCenter 在超时前等待脚本执行的时间限制。
+
例如，您可以运行脚本来更新 SNMP 陷阱，自动执行警报和发送日志。

+

NOTE: 预处理脚本或后处理脚本路径不应包含驱动器或共享。路径应与scripts_path相关。

. 查看摘要，然后单击 * 完成 * 。

