---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: 您可以使用 SnapCenter 还原文件系统备份。文件系统还原是一个多阶段过程，可将所有数据从指定备份复制到文件系统的原始位置。 
---
= 还原 Windows 文件系统备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SnapCenter 还原文件系统备份。文件系统还原是一个多阶段过程，可将所有数据从指定备份复制到文件系统的原始位置。

* 您需要的内容 *

* 您必须已备份文件系统。
* 如果某个文件系统当前正在执行计划的操作，例如备份操作，则必须先取消该操作，然后才能启动还原操作。
* 您只能将文件系统备份还原到原始位置，而不能还原到备用路径。
+
您无法从备份中还原单个文件，因为还原的文件系统会覆盖文件系统原始位置上的任何数据。要从文件系统备份还原单个文件，您必须克隆该备份并访问克隆中的文件。

* 您不能还原系统或启动卷。
* SnapCenter 可以还原 Windows 集群中的文件系统，而无需使集群组脱机。


* 步骤 *

. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 要筛选资源列表，请选择文件系统和资源组选项。
. 从列表中选择一个资源组，然后单击 * 还原 * 。
. 在备份页面中，选择要从主存储系统还是从二级存储系统还原，然后选择要还原的备份。
. 在还原向导中选择您的选项。
. 您可以输入希望 SnapCenter 在还原操作前后运行的预处理或后处理的路径和参数。
+
例如，您可以运行脚本来更新 SNMP 陷阱，自动执行警报，发送日志等操作。

. 在通知页面中，选择以下选项之一：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
将 SnapCenter 服务器事件记录到存储系统系统系统日志中
 a| 
选择此选项可将 SnapCenter 服务器事件记录到存储系统的系统日志中。



 a| 
向存储系统发送失败操作的 AutoSupport 通知
 a| 
选择此选项可使用 AutoSupport 向 NetApp 发送有关任何失败操作的信息。



 a| 
电子邮件首选项
 a| 
选择 * 始终 * ， * 发生故障 * 或 * 发生故障或警告 * ，以便在还原备份后向收件人发送电子邮件消息。输入 SMTP 服务器，默认电子邮件主题行以及收件人和发件人电子邮件地址。

|===
. 查看摘要，然后单击 * 完成 * 。
. 单击 * 监控 * > * 作业 * 以监控操作进度。



IMPORTANT: 如果还原的文件系统包含数据库，则还必须还原该数据库。如果不还原数据库，则数据库可能处于无效状态。有关还原数据库的信息，请参见该数据库的《数据保护指南》。
