---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: 您可以使用 SnapCenter 还原文件系统备份。文件系统还原是一个多阶段过程，可将所有数据从指定备份复制到文件系统的原始位置。 
---
= 还原 Windows 文件系统备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SnapCenter 还原文件系统备份。文件系统还原是一个多阶段过程，可将所有数据从指定备份复制到文件系统的原始位置。

.开始之前
* 您必须已备份文件系统。
* 如果某个文件系统当前正在执行计划的操作，例如备份操作，则必须先取消该操作，然后才能启动还原操作。
* 您只能将文件系统备份还原到原始位置，而不能还原到备用路径。
+
您无法从备份中还原单个文件，因为还原的文件系统会覆盖文件系统原始位置上的任何数据。要从文件系统备份还原单个文件，您必须克隆该备份并访问克隆中的文件。

* 您不能还原系统或启动卷。
* SnapCenter 可以还原 Windows 集群中的文件系统，而无需使集群组脱机。


.关于此任务
* 脚本路径使用位于插件主机SMCoreServiceHost.exe配置文件中的预定义WindowsScriptsDirectory密钥进行定义。
+
如果需要、您可以更改此路径并重新启动SMcore服务。建议您使用默认安全路径。

+
可以通过API：API /4.7/configsettings从Swagger显示密钥值

+
您可以使用GET API显示密钥的值。不支持设置API。

* 对于SnapMirror活动同步还原操作、您必须从主位置选择备份。
* 对于ONTAP 9.12.1及更低版本、在还原过程中从SnapLock存储快照创建的克隆将继承SnapLock存储到期时间。存储管理员应在SnapLock到期时间后手动清理克隆。


[role="tabbed-block"]
====
.SnapCenter UI
--
.步骤
. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 要筛选资源列表，请选择文件系统和资源组选项。
. 从列表中选择一个资源组，然后单击 * 还原 * 。
. 在备份页面中，选择要从主存储系统还是从二级存储系统还原，然后选择要还原的备份。
. 在还原向导中选择您的选项。
. 您可以输入希望 SnapCenter 在还原操作前后运行的预处理或后处理的路径和参数。
+
例如，您可以运行脚本来更新 SNMP 陷阱，自动执行警报，发送日志等操作。

+

NOTE: 预处理脚本或后处理脚本路径不应包含驱动器或共享。路径应与scripts_path相关。

. 在通知页面中，选择以下选项之一：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
将 SnapCenter 服务器事件记录到存储系统系统系统日志中
 a| 
选择此选项可将 SnapCenter 服务器事件记录到存储系统的系统日志中。



 a| 
向存储系统发送失败操作的 AutoSupport 通知
 a| 
选择此选项可使用 AutoSupport 向 NetApp 发送有关任何失败操作的信息。



 a| 
电子邮件首选项
 a| 
选择 * 始终 * ， * 发生故障 * 或 * 发生故障或警告 * ，以便在还原备份后向收件人发送电子邮件消息。输入 SMTP 服务器，默认电子邮件主题行以及收件人和发件人电子邮件地址。

|===
. 查看摘要，然后单击 * 完成 * 。
. 单击 * 监控 * > * 作业 * 以监控操作进度。



IMPORTANT: 如果还原的文件系统包含数据库，则还必须还原该数据库。如果不还原数据库，则数据库可能处于无效状态。有关还原数据库的信息，请参见该数据库的《数据保护指南》。

--
.PowerShell cmdlet
--
.步骤
. 使用 Open-SmConnection cmdlet 为指定用户启动与 SnapCenter 服务器的连接会话。
+
[listing]
----
PS C:\> Open-Smconnection
----
. 使用 Get-SmBackup 和 Get-SmBackupReport cmdlet 检索有关要还原的一个或多个备份的信息。
+
此示例显示有关所有可用备份的信息：

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
此示例显示了有关 2015 年 1 月 29 日至 2015 年 2 月 3 日备份的详细信息：

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. 使用 Restore-SmBackup cmdlet 从备份中还原数据。
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《 SnapCenter 软件 cmdlet 参考指南》"^]。

--
====