---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: 您可以使用 SnapCenter 克隆 Windows 文件系统备份。如果您需要错误删除或更改的单个文件的副本，则可以克隆备份并访问克隆中的该文件。 
---
= 从 Windows 文件系统备份克隆
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SnapCenter 克隆 Windows 文件系统备份。如果您需要错误删除或更改的单个文件的副本，则可以克隆备份并访问克隆中的该文件。

.开始之前
* 您应已准备好通过完成添加主机，识别资源和创建 Storage Virtual Machine （ SVM ）连接等任务来保护数据。
* 您应具有文件系统的备份。
* 您应确保托管卷的聚合应位于 Storage Virtual Machine （ SVM ）的已分配聚合列表中。
* 您不能克隆资源组。您只能克隆单个文件系统备份。
* 如果备份驻留在具有 VMDK 磁盘的虚拟机上，则 SnapCenter 无法将备份克隆到物理服务器。
* 如果克隆 Windows 集群（例如，共享 LUN 或集群共享卷（ CSV ） LUN ），则该克隆将作为专用 LUN 存储在您指定的主机上。
* 对于克隆操作，卷挂载点的根目录不能是共享目录。
* 您不能在不是聚合主节点的节点上创建克隆。
* 您不能为 Windows 文件系统计划重复克隆（克隆生命周期）操作；您只能按需克隆备份。
* 如果将包含克隆的 LUN 移动到新卷，则 SnapCenter 将无法再支持此克隆。例如，您不能使用 SnapCenter 删除该克隆。
* 您不能跨环境克隆。例如，从物理磁盘克隆到虚拟磁盘，反之亦然。


.关于此任务
* 脚本路径使用位于插件主机SMCoreServiceHost.exe配置文件中的预定义WindowsScriptsDirectory密钥进行定义。
+
如果需要、您可以更改此路径并重新启动SMcore服务。建议您使用默认安全路径。

+
可以通过API：API /4.7/configsettings从Swagger显示密钥值

+
您可以使用GET API显示密钥的值。不支持设置API。

* 对于启用了SnapLock的策略、对于ONTAP 9.12.1及更低版本、如果指定了Snapshot副本锁定期限、则在还原过程中从防篡改Snapshot副本创建的克隆将继承SnapLock到期时间。存储管理员应在SnapLock到期时间后手动清理克隆。


.步骤
. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 在资源页面中，从列表中选择 * 文件系统 * 。
. 选择主机。
+
如果资源受保护，则会自动显示拓扑视图。

. 从资源列表中，选择要克隆的备份，然后单击克隆图标。
. 在选项页面中，执行以下操作：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
克隆服务器
 a| 
选择应在其中创建克隆的主机。



 a| 
"`自动分配挂载点` " 或 "`自动分配路径` 下的卷挂载点 "
 a| 
选择是自动在路径下分配挂载点还是卷挂载点。

在路径下自动分配卷挂载点：通过路径下的挂载点，您可以提供要在其中创建挂载点的特定目录。在选择此选项之前，您必须验证此目录是否为空。如果目录中存在备份，则在执行挂载操作后，备份将处于无效状态。



 a| 
归档位置
 a| 
如果要克隆二级备份，请选择归档位置。

|===
. 在脚本页面中，指定要执行的任何预处理脚本或后处理脚本。
+

NOTE: 预处理脚本或后处理脚本路径不应包含驱动器或共享。路径应与scripts_path相关。

. 查看摘要，然后单击 * 完成 * 。
. 单击 * 监控 * > * 作业 * 以监控操作进度。

