---
permalink: protect-concept/concept_disaster_recovery.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用 SnapCenter 灾难恢复功能在发生资源损坏或服务器崩溃等灾难时恢复 SnapCenter 服务器。 
---
= 灾难恢复
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 SnapCenter 灾难恢复功能在发生资源损坏或服务器崩溃等灾难时恢复 SnapCenter 服务器。您可以恢复 SnapCenter 存储库，服务器计划和服务器配置组件。

您还可以恢复适用于 SQL Server 的 SnapCenter 插件和适用于 SQL Server 的 SnapCenter 插件存储。

以下是灾难恢复（ DR ）的类型：

* * SnapCenter 服务器灾难恢复 *
+
无论 SnapCenter 服务器是否添加了任何插件或管理了任何插件，都将备份和恢复 SnapCenter 服务器数据。

+
二级SnapCenter 服务器应安装在与主SnapCenter 服务器相同的安装目录和端口上。

+
对于多因素身份验证(MFA)、在对SnapCenter 服务器执行灾难恢复还原时、请关闭所有浏览器选项卡并重新打开浏览器以重新登录。这将清除现有或活动的会话Cookie、并确保更新正确的配置数据。

+
SnapCenter 灾难恢复功能使用 REST API 备份 SnapCenter 服务器。

+
link:../sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html["用于 SnapCenter 服务器灾难恢复的 REST API 工作流"]

* * SnapCenter 插件和存储灾难恢复 *
+
只有适用于 SQL Server 的 SnapCenter 插件才支持 DR 。当适用于 SQL Server 的 SnapCenter 插件关闭时，切换到另一个 SQL 主机，并通过执行几个步骤来恢复数据。

+
link:../protect-scsql/task_disaster_recovery_scsql.html["适用于 SQL Server 的 SnapCenter 插件的灾难恢复"]



SnapCenter 使用 ONTAP SnapMirror 技术复制数据。它可用于将数据复制到二级站点以进行灾难恢复并保持同步。可以通过中断 SnapMirror 中的复制关系来启动故障转移。在故障恢复期间，可以反转同步，并将灾难恢复站点中的数据复制回主位置。
