---
permalink: concept/reference_role_based_access_control_permissions_and_roles.html 
sidebar: sidebar 
keywords: RBAC, roles, permissions 
summary: 通过 SnapCenter 基于角色的访问控制（ Role-Based Access Control ， RBAC ），您可以创建角色并为这些角色添加权限，然后将用户或用户组分配给这些角色。这样， SnapCenter 管理员就可以创建一个集中管理的环境，而应用程序管理员则可以管理数据保护作业。SnapCenter 附带了一些预定义的角色和权限。 
---
= RBAC 权限和角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 SnapCenter 基于角色的访问控制（ Role-Based Access Control ， RBAC ），您可以创建角色并为这些角色分配权限，然后将用户或用户组分配给这些角色。这样， SnapCenter 管理员就可以创建一个集中管理的环境，而应用程序管理员则可以管理数据保护作业。SnapCenter 附带了一些预定义的角色和权限。



== SnapCenter 角色

SnapCenter 附带以下预定义角色。您可以将用户和组分配给这些角色，也可以创建新角色。

将角色分配给用户时，只有与该用户相关的作业才会显示在 " 作业 " 页面中，除非您已分配 SnapCenter 管理员角色。

* 应用程序备份和克隆管理员
* 备份和克隆查看器
* 基础架构管理员
* SnapCenterAdmin




== 适用于 VMware vSphere 的 SnapCenter 插件角色

为了管理 VM ， VMDK 和数据存储库的 VM 一致数据保护，适用于 VMware vSphere 的 SnapCenter 插件会在 vCenter 中创建以下角色：

* SCV 管理员
* SCV 视图
* SCV 备份
* SCV 恢复
* SCV 子系统文件还原


有关详细信息，请参见 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_types_of_rbac_for_snapcenter_users.html["适用于 VMware vSphere 的 SnapCenter 插件用户的 RBAC 类型"^]

|===


| * 最佳实践： * NetApp 建议您为适用于 VMware vSphere 的 SnapCenter 插件操作创建一个 ONTAP 角色，并为其分配所有必需的特权。 
|===


== SnapCenter 权限

SnapCenter 提供以下权限：

* Resource Group
* 策略
* 备份
* 主机
* 存储连接
* 克隆
* 配置（仅适用于 Microsoft SQL 数据库）
* 信息板
* 报告
* 还原
+
** 完整卷还原（仅适用于自定义插件）


* 资源
+
要执行资源发现操作，非管理员需要具有管理员提供的插件权限。

* 插件安装或卸载
+

NOTE: 启用插件安装权限时，您还必须修改主机权限以启用读取和更新。

* migration
* 挂载（仅适用于 Oracle 数据库）
* 卸载（仅适用于 Oracle 数据库）
* 作业监控器
+
通过作业监控权限，不同角色的成员可以查看其分配到的所有对象上的操作。


