---
permalink: protect-hana/concept_auto_discovery_of_resources_on_linux_host.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: '资源是指 Linux 主机上由 SnapCenter 管理的 SAP HANA 数据库和非数据卷。安装适用于 SAP HANA 数据库的 SnapCenter 插件后，系统会自动发现该 Linux 主机上的 SAP HANA 数据库，并将其显示在 "Resources" 页面上。' 
---
= 自动发现 Linux 主机上的资源
:icons: font
:imagesdir: ../media/


[role="lead"]
资源是指 Linux 主机上由 SnapCenter 管理的 SAP HANA 数据库和非数据卷。安装适用于 SAP HANA 数据库的 SnapCenter 插件后，系统会自动发现该 Linux 主机上的 SAP HANA 数据库，并将其显示在 "Resources" 页面上。

以下 SAP HANA 资源支持自动发现：

* 单个容器
+
安装或升级此插件后，位于中央主机插件上的单个容器资源将继续作为手动添加的资源使用。

+
安装或升级此插件后， SAP HANA 数据库只会自动发现在直接注册到 SnapCenter 的 SAP HANA Linux 主机上。

* 多租户数据库容器（ MDC ）
+
安装或升级此插件后，位于中央主机插件上的 MDC 资源将继续作为手动添加的资源使用。

+
升级到 SnapCenter 4.3 后，您必须继续在中央主机插件上手动添加 MDC 资源。

+
对于直接在 SnapCenter 中注册的 SAP HANA Linux 主机，安装或升级此插件将触发自动发现主机上的资源。升级此插件后，对于插件主机上的每个 MDC 资源，系统将自动发现另一个采用不同 GUID 格式的 MDC 资源，并将其注册到 SnapCenter 中。新资源将处于锁定状态。

+
例如，在 SnapCenter 4.2 中，如果 E90 MDC 资源位于插件主机上并手动注册，则在升级到 SnapCenter 4.3 后，将在 SnapCenter 中发现并注册具有不同 GUID 的另一个 E90 MDC 资源。



《 SAP HANA 数据库数据保护指南》提供了有关如何在 SnapCenter 插件主机上使用新 MDC 资源执行数据保护操作的详细信息

以下配置不支持自动发现：

* RDM 和 VMDK 布局
+

NOTE: 如果发现上述资源，这些资源不支持数据保护操作。

* HANA 多主机配置
* HANA 系统复制
* 同一主机上的多个实例

