---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 在添加主机并安装插件软件包之前，您必须满足所有要求。适用于 SAP HANA 数据库的 SnapCenter 插件可在 Windows 和 Linux 环境中使用。 
---
= 添加主机和安装适用于 SAP HANA 数据库的 SnapCenter 插件的前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在添加主机并安装插件软件包之前，您必须满足所有要求。适用于 SAP HANA 数据库的 SnapCenter 插件可在 Windows 和 Linux 环境中使用。

* 您必须已在主机上安装 Java 1.8 64 位。
+

NOTE: 不支持IBM Java。

* 您必须已在主机上安装 SAP HANA 数据库交互式终端（ HDBSQL 客户端）。
* 对于 Windows ，插件 Creator 服务应使用 "`LocalSystem` " Windows 用户运行，这是以域管理员身份安装适用于 SAP HANA 数据库的插件时的默认行为。
* 对于 Windows ，应以系统用户身份创建用户存储密钥。
* 在 Windows 主机上安装插件时，如果您指定的凭据不是内置的，或者用户属于本地工作组用户，则必须在主机上禁用 UAC 。默认情况下，适用于 Microsoft Windows 的 SnapCenter 插件将与 SAP HANA 插件一起部署在 Windows 主机上。
* 对于 Linux 主机， HDB 安全用户存储密钥以 HDBSQL OS 用户身份访问。
* SnapCenter 服务器应有权访问适用于 SAP HANA 数据库主机的插件的 8145 或自定义端口。




== Windows 主机

* 您必须具有具有本地管理员权限的域用户，并在远程主机上具有本地登录权限。
* 在 Windows 主机上安装适用于 SAP HANA 数据库的插件时，适用于 Microsoft Windows 的 SnapCenter 插件会自动安装。
* 您必须已为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须已在 Windows 主机上安装 Java 1.8 64 位。
+
http://www.java.com/en/download/manual.jsp["适用于所有操作系统的 Java 下载"]

+
https://imt.netapp.com/matrix/imt.jsp?components=108391;&solution=1259&isHWU&src=IMT["NetApp 互操作性表工具"]





== Linux 主机

* 您必须已为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须已在 Linux 主机上安装 Java 1.8 64 位。
+
http://www.java.com/en/download/manual.jsp["适用于所有操作系统的 Java 下载"]

+
https://imt.netapp.com/matrix/imt.jsp?components=108391;&solution=1259&isHWU&src=IMT["NetApp 互操作性表工具"]

* 对于在 Linux 主机上运行的 SAP HANA 数据库，在安装适用于 SAP HANA 数据库的插件时，系统会自动安装适用于 UNIX 的 SnapCenter 插件。

