---
permalink: protect-hana/task_prepare_multitenant_database_containers_for_data_protection.html 
sidebar: sidebar 
keywords: multitenant database containers 
summary: '对于直接在 SnapCenter 中注册的 SAP HANA 主机，安装或升级适用于 SAP HANA 数据库的 SnapCenter 插件将触发主机上资源的自动发现。安装或升级此插件后，对于插件主机上的每个多租户数据库容器 \ （ MDC\ ）资源，系统将自动发现另一个采用不同 GUID 格式的 MDC 资源并在 SnapCenter 中注册。新资源将处于 " 已锁定 " 状态。' 
---
= 准备多租户数据库容器以进行数据保护
:icons: font
:imagesdir: ../media/


[role="lead"]
对于直接在 SnapCenter 中注册的 SAP HANA 主机，安装或升级适用于 SAP HANA 数据库的 SnapCenter 插件将触发主机上资源的自动发现。安装或升级此插件后，对于插件主机上的每个多租户数据库容器（ MDC ）资源，系统将自动发现另一个采用不同 GUID 格式的 MDC 资源并在 SnapCenter 中注册。新资源将处于 "`locked` " 状态。

* 关于此任务 *

例如，在 SnapCenter 4.2 中，如果 E90 MDC 资源位于插件主机上并手动注册，则在升级到 SnapCenter 4.3 后，将在 SnapCenter 中发现并注册具有不同 GUID 的另一个 E90 MDC 资源。


NOTE: 必须保留与 SnapCenter 4.2 及更早版本资源关联的备份，直到保留期限到期为止。保留期限到期后，您可以删除旧的 MDC 资源并继续管理新的自动发现的 MDC 资源。

`旧 MDC 资源` 是在 SnapCenter 4.2 或更早版本中手动添加的插件主机的 MDC 资源。

执行以下步骤，开始使用在 SnapCenter 4.3 中发现的新资源执行数据保护操作：

* 步骤 *

. 在 * 资源 * 页面上，选择已添加到早期 SnapCenter 版本的备份 `m的旧 MDC 资源，然后将其从拓扑页面置于 " 维护模式` " 。
+
`m资源属于某个资源组，请将该资源组置于 " 维护模式` " 。

. 通过从 "Resources" 页面中选择新资源，配置升级到 SnapCenter 4.3 后发现的新 MDC 资源。
+
"`新的 MDC 资源` " 是在 SnapCenter 服务器和插件主机升级到 4.3 后发现的新发现的 MDC 资源。对于给定主机，可以将新的 MDC 资源标识为与旧 MDC 资源具有相同 SID 的资源，并在 "Resources" 页面中将其旁边显示一个红色挂锁图标。

. 通过选择保护策略，计划和通知设置，保护升级到 SnapCenter 4.3 后发现的新 MDC 资源。
. 根据保留设置删除在 SnapCenter 4.2 或更早版本中创建的备份。
. 从 Topology 页面中删除资源组。
. 从 "Resources" 页面中删除旧的 MDC 资源。
+
例如，如果主 Snapshot 副本保留期限为 7 天，而二级 Snapshot 副本保留期限为 45 天，则在完成 45 天后以及删除所有备份后，您必须删除资源组和旧的 MDC 资源。



* 查找更多信息 *

link:task_configure_hdb_user_store_key_and_hdbsql_os_user_for_the_sap_hana_database.html["为 SAP HANA 数据库配置 HDB 用户存储密钥和 HDBSQL 操作系统用户"]

link:task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["在拓扑页面中查看 SAP HANA 数据库备份和克隆"]
