---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_features.html 
sidebar: sidebar 
keywords: Custom Plug-ins features 
summary: SnapCenter 可与插件应用程序以及存储系统上的 NetApp 技术集成。要使用自定义插件，请使用 SnapCenter 图形用户界面。 
---
= SnapCenter 自定义插件功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 可与插件应用程序以及存储系统上的 NetApp 技术集成。要使用自定义插件，请使用 SnapCenter 图形用户界面。

* * 统一图形用户界面 *
+
SnapCenter 界面可在插件和环境之间实现标准化和一致性。通过 SnapCenter 界面，您可以跨插件完成一致的备份，还原，恢复和克隆操作，使用集中式报告，使用信息板概览视图，设置基于角色的访问控制（ Role-Based Access Control ， RBAC ）以及监控所有插件中的作业。

* * 自动化中央管理 *
+
您可以计划备份操作，配置基于策略的备份保留以及执行还原操作。您还可以通过配置 SnapCenter 以发送电子邮件警报来主动监控您的环境。

* * 无中断 NetApp Snapshot 副本技术 *
+
SnapCenter 将 NetApp Snapshot 副本技术与 SnapCenter 自定义插件结合使用来备份资源。Snapshot 副本占用的存储空间极少。



使用自定义插件功能还具有以下优势：

* 支持备份，还原和克隆工作流
* 支持 RBAC 的安全性和集中式角色委派
+
您还可以设置凭据，以便授权的 SnapCenter 用户具有应用程序级别的权限。

* 使用 NetApp FlexClone 技术为测试或数据提取创建节省空间的时间点资源副本
+
要创建克隆的存储系统需要 FlexClone 许可证。

* 在创建备份过程中支持 ONTAP 的一致性组（ CG ） Snapshot 副本功能。
* 能够在多个资源主机之间同时运行多个备份
+
在一次操作中，如果一个主机中的资源共享同一个卷，则会整合 Snapshot 副本。

* 可以使用外部命令创建 Snapshot 副本。
* 能够在 Windows 环境中创建文件系统一致的 Snapshot 副本。

