---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: SnapCenter Custom Plug-ins 
summary: 您可以为使用的应用程序开发自定义插件，然后使用 SnapCenter 备份，还原或克隆这些应用程序。与其他 SnapCenter 插件一样，您的自定义插件也充当 NetAppSnap Center 软件的主机端组件，从而实现应用程序感知型数据保护和资源管理。 
---
= SnapCenter 自定义插件概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以为使用的应用程序开发自定义插件，然后使用 SnapCenter 备份，还原或克隆这些应用程序。与其他 SnapCenter 插件一样，您的自定义插件也充当 NetApp SnapCenter 软件的主机端组件，从而实现应用程序感知型数据保护和资源管理。

安装自定义插件后，您可以使用采用 NetApp SnapMirror 技术的 SnapCenter 在另一个卷上创建备份集的镜像副本，并使用 NetApp SnapVault 技术执行磁盘到磁盘备份复制。自定义插件既可以在 Windows 环境中使用，也可以在 Linux 环境中使用。


NOTE: SnapCenterCLI 不支持 SnapCenter 自定义插件命令。

NetApp 提供了存储插件，可使用 SnapCenter 中内置的自定义插件框架对 ONTAP 存储上的数据卷执行数据保护操作。

您可以从添加主机页面安装自定义插件和存储插件。

link:task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html["添加主机并在远程主机上安装插件软件包。"^]

NetApp 还提供 MySQL ， MaxDB ， DB2 ， Sybase ， DPGLUE ， MongoDB ， ORASCPM 和 PostgreSQL 自定义插件。这些插件可从下载 https://automationstore.netapp.com/home.shtml["NetApp 存储自动化商店"^]。


NOTE: SnapCenter 支持策略将涵盖对 SnapCenter 自定义插件框架，核心引擎和关联 API 的支持。支持范围不包括插件源代码以及基于自定义插件框架构建的关联脚本。

您可以参考创建自己的自定义插件 link:concept_develop_a_plug_in_for_your_application.html["为您的应用程序开发一个插件"^]。
