---
permalink: protect-scc/prerequisites_for_using_custom_plugins.html 
sidebar: sidebar 
keywords: Credentials 
summary: 在使用SnapCenter自定义插件之前、SnapCenter管理员必须安装和配置SnapCenter服务器并执行必备任务。 
---
= 使用 SnapCenter 自定义插件的前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter自定义插件之前、SnapCenter管理员必须安装和配置SnapCenter服务器并执行必备任务。

* 安装和配置 SnapCenter 服务器。
* 登录到 SnapCenter 服务器。
* 如果适用，可通过添加存储系统连接和创建凭据来配置 SnapCenter 环境。
* 添加主机，然后安装和上传插件。
* 如果适用、请在插件主机上安装Java 11。
* 如果您有多个数据路径（ LIF ）或 DNFS 配置，则可以在数据库主机上使用 SnapCenter 命令行界面执行以下操作：
+
** 默认情况下，数据库主机的所有 IP 地址都会添加到 Storage Virtual Machine （ SVM ）中克隆卷的 NFS 存储导出策略中。如果要使用特定的 IP 地址或限制为部分 IP 地址，请运行 Set-PreferredHostIPsInStorageExportPolicy CLI 。
** 如果 SVM 中有多个数据路径（ LIF ），则 SnapCenter 会选择适当的数据路径（ LIF ）来挂载 NFS 克隆卷。但是，如果要指定特定数据路径（ LIF ），则必须运行 Set-SvmPreferredDataPath CLI 。有关可与命令结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://library.netapp.com/ecm/ecm_download_file/ECMLP3323470["《 SnapCenter 软件命令参考指南》"^]。


* 如果要进行备份复制，请设置 SnapMirror 和 SnapVault 。
* 确保端口 9090 未被主机上的任何其他应用程序使用。
+
除了SnapCenter所需的其他端口之外、还必须保留端口9090供自定义插件使用。


