---
permalink: protect-scc/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_custom_plug_ins.html 
sidebar: sidebar 
keywords: credentials 
summary: 在添加主机并安装插件软件包之前，您必须满足所有要求。自定义插件既可以在 Windows 环境中使用，也可以在 Linux 环境中使用。 
---
= 添加主机和安装 SnapCenter 自定义插件的前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在添加主机并安装插件软件包之前，您必须满足所有要求。自定义插件既可以在 Windows 环境中使用，也可以在 Linux 环境中使用。

* 您必须已创建自定义插件。有关详细信息，请参见开发人员信息。
+
link:concept_develop_a_plug_in_for_your_application.html["为您的应用程序开发一个插件"]

* 如果要管理 MySQL 或 DB2 应用程序，必须已下载 NetApp 提供的 MySQL 和 DB2 自定义插件。
* 您必须已在Linux或Windows主机上安装Java 1.8或Java 11 (64位)。
* 在 Windows 主机上安装插件时，如果您指定的凭据不是内置的，或者用户属于本地工作组用户，则必须在主机上禁用 UAC 。
* 自定义插件必须在执行添加主机操作的客户端主机上可用。




== 常规

如果使用的是iSCSI、则iSCSI服务应正在运行。



== SHA512哈希

* 对于NetApp提供的自定义插件、您应确保已将自定义插件文件的SHA512哈希添加到_custom_plugin_checksum_list_文件中。
+
** 对于Linux主机、SHA512哈希位于：_/var/opt/snapcenter/SCC/custom_plugin_checksum_list.txt
** 对于Windows主机、SHA512哈希位于_C：\Program Files\NetApp\SnapCenter Plug-in Creator\etc\custom_plugin_checksum_list.txt
+
对于自定义安装路径、SHA512哈希位于_<custom path>\NetApp\SnapCenter\SnapCenter Plug-in Creator\etc\custom_plugin_checksum_list.txt



+
custom_plugin_checksum_list是SnapCenter 在主机上安装的自定义插件的一部分。

* 对于为应用程序创建的自定义插件、您应已执行以下步骤：
+
.. 已生成插件zip文件的SHA512哈希。
+
您可以使用等联机工具 https://emn178.github.io/online-tools/sha512_file_hash.html["SHA512哈希"^]。

.. 已将生成的SHA512哈希添加到custom_plugin_checksum_list文件中的新行。
+
注释以#符号开头、用于标识哈希所属的插件。

+
以下是校验和文件中SHA512哈希条目的示例：

+
....
#ORASCPM
03721f567a1e4a1cb5569066b9a58af619ee12b1f8713108f81b696cfbdb81c25232fa63d6e6777a2b2a1ec068bb0a93a59a8ade71587182f8bccbe81f7e0ba6
....






== Windows 主机

* 您必须具有具有本地管理员权限的域用户，并在远程主机上具有本地登录权限。
* 如果您在 SnapCenter 中管理集群节点，则必须具有对集群中所有节点具有管理权限的用户。




== Linux 主机

* 您必须已为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须已在Linux主机上安装Java 1.8或Java 11 (64位)。
+
如果要对SnapCenter 服务器主机使用Windows Server 2019或Windows Server 2016、则必须安装Java 1.8或Java 11 (64位)。互操作性表工具（ IMT ）包含有关要求的最新信息。

+
http://www.java.com/en/download/manual.jsp["适用于所有操作系统的 Java 下载"]

+
https://imt.netapp.com/matrix/imt.jsp?components=105308;&solution=1259&isHWU&src=IMT["NetApp 互操作性表工具"]

* 您必须为非 root 用户配置 sudo 权限，才能提供对多个路径的访问权限。使用 visudo Linux 实用程序将以下行添加到 /etc/sudoers 文件中。
+

NOTE: 确保使用的是sudo 1.8.7或更高版本。

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_linux_user_是 您创建的非root用户的名称。

+
您可以从* ORACLE_checksum.txt *文件中获取_checksum_value_、该文件位于_C：\ProgramData\NetApp\SnapCenter\Package Repository _。

+

IMPORTANT: 此示例只能用作创建自己数据的参考。


