---
permalink: protect-scc/task_install_the_snapcenter_custom_plug_ins_on_linux_hosts_using_the_command_line_interface.html 
sidebar: sidebar 
keywords:  
summary: 您应使用 SnapCenter 用户界面（ UI ）安装 SnapCenter 自定义插件。如果您的环境不允许从 SnapCenter UI 远程安装此插件，您可以使用命令行界面 \ （ cli\ ）在控制台模式或静默模式下安装此自定义插件。 
---
= 使用命令行界面在 Linux 主机上安装 SnapCenter 自定义插件
:icons: font
:imagesdir: ../media/


[role="lead"]
您应使用 SnapCenter 用户界面（ UI ）安装 SnapCenter 自定义插件。如果您的环境不允许从 SnapCenter UI 远程安装此插件，则可以使用命令行界面（ CLI ）在控制台模式或静默模式下安装此自定义插件。

* 步骤 *

. 将适用于 Linux 的 SnapCenter 插件软件包安装文件（ snapcenter_linux_host_plugin.bin ）从 C ： \ProgramData\NetApp\SnapCenter\Package Repository 复制到要安装自定义插件的主机。
+
您可以从安装了 SnapCenter 服务器的主机访问此路径。

. 在命令提示符处，导航到复制安装文件的目录。
. 安装插件： `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -dport=port_number_for_host -dserver_ip=server_name_or_ip_address -dserver_HTTPS_port=port_number_for_server`
+
** -dport 用于指定 SMCore HTTPS 通信端口。
** -dserver_ip 指定 SnapCenter 服务器 IP 地址。
** -dserver_HTTPS_port 指定 SnapCenter 服务器 HTTPS 端口。
** -duser_install_DIR 指定要安装适用于 Linux 的 SnapCenter 插件软件包的目录。
** DINSTALL_LOG_name 指定日志文件的名称。


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. 使用 Add-Smhost cmdlet 和所需参数将主机添加到 SnapCenter 服务器。
+
有关可与命令结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["《 SnapCenter 软件 cmdlet 参考指南》"^]。

. 登录到 SnapCenter ，然后从 UI 或使用 PowerShell cmdlet 上传自定义插件。
+
您可以参考从 UI 上传自定义插件 link:task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html["添加主机并在远程主机上安装插件软件包"] 部分。

+
SnapCenter cmdlet 帮助和 cmdlet 参考信息包含有关 PowerShell cmdlet 的详细信息。

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["《 SnapCenter 软件 cmdlet 参考指南》"^]。


