---
permalink: sc-automation/reference_supported_rest_apis.html 
sidebar: sidebar 
keywords: REST API categories 
summary: 通过 SnapCenter REST API 提供的资源按类别进行组织，如 SnapCenter API 文档页面上所示。 
---
= 支持的 REST API
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 SnapCenter REST API 提供的资源按类别进行组织，如 SnapCenter API 文档页面上所示。下面简要介绍了每个资源的问题描述以及基本资源路径，并在适当情况下提供了其他使用注意事项。



== 身份验证

您可以使用此 API 调用登录到 SnapCenter 服务器。此 API 将返回一个用户授权令牌，用于对后续请求进行身份验证。



== 域

您可以使用这些 API 调用执行以下操作：

* 检索所有域
* 检索特定域的详细信息
* 注册或取消注册域
* 修改域




== 作业

您可以使用这些 API 调用执行以下操作：

* 检索所有作业
* 检索作业状态
* 取消或停止作业




== 设置

您可以使用这些 API 调用执行以下操作：

* 注册，查看，修改或删除凭据
* 配置通知设置




== 主机

您可以使用这些 API 调用执行以下操作：

* 检索主机详细信息
* 检索已安装的插件及其资源详细信息
* 添加，删除或修改插件主机
* 安装或升级插件




== Resources

您可以使用这些 API 调用执行以下操作：

* 检索资源
* 创建，修改或删除资源
* 保护资源
* 备份，还原或克隆资源




== 备份

您可以使用这些 API 调用执行以下操作：

* 检索备份详细信息
* 重命名或删除备份




== 克隆

您可以使用这些 API 调用执行以下操作：

* 检索克隆详细信息
* 删除克隆。




== 克隆

您可以使用这些 API 调用执行以下操作：

* 检索克隆拆分操作的状态
* 启动或停止克隆拆分操作




== 资源组

您可以使用这些 API 调用执行以下操作：

* 检索资源组的详细信息
* 创建，修改或删除资源组
* 备份资源组




== 策略

您可以使用这些 API 调用执行以下操作：

* 检索策略详细信息
* 创建，修改或删除策略




== 存储

您可以使用这些 API 调用执行以下操作：

* 检索存储详细信息
* 创建，修改或删除存储
* 发现存储上的资源
* 在存储上创建或删除共享




== 共享

您可以使用这些 API 调用执行以下操作：

* 检索共享的详细信息
* 在存储上创建或删除共享




== 插件

您可以使用这些 API 调用来检索主机上的所有插件并执行不同的操作。



== 报告

您可以使用这些 API 调用执行以下操作：

* 生成备份，还原，克隆和插件报告
* 添加，运行，删除或修改计划




== 警报

您可以使用这些 API 调用执行以下操作：

* 检索所有警报
* 删除警报




== RBAC

您可以使用这些 API 调用执行以下操作：

* 检索用户，组和角色的详细信息
* 添加用户
* 创建，修改或删除角色
* 分配或取消分配角色和组




== Configuration

您可以使用这些 API 调用执行以下操作：

* 查看配置设置
* 修改配置设置




== 证书设置

您可以使用这些 API 调用执行以下操作：

* 查看证书状态
* 修改证书设置




== 存储库

您可以使用这些 API 调用执行以下操作：

* 备份和还原 NSM 存储库
* 保护和取消保护 NSM 存储库
* 故障转移
* 重建 NSM 存储库

