---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: '在SnapCenter左侧导航窗格中、您可以通过信息板初步了解系统的运行状况、包括最近的作业活动、警报、保护摘要、存储效率和使用情况、SnapCenter作业的状态\(备份、克隆、还原\)、独立和Windows集群主机的配置状态、 由SnapCenter管理的Storage Virtual Machine (SVM)数量以及许可证容量。' 
---
= 信息板概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 SnapCenter 左侧导航窗格中，您可以通过信息板首次查看系统运行状况，包括近期作业活动，警报，保护摘要，存储效率和使用情况， SnapCenter 作业的状态（备份，克隆，还原），独立主机和 Windows 集群主机的配置状态， 由 SnapCenter 管理的 Storage Virtual Machine （ SVM ）的数量以及许可证容量。

信息板视图中显示的信息取决于分配给当前登录到 SnapCenter 的用户的角色。如果用户无权查看某些内容，则可能不会显示这些内容。

在许多情况下，您可以通过将鼠标悬停在 * i * 上来查看有关显示的详细信息。在某些情况下，信息板显示中的信息会链接到 SnapCenter 图形用户界面页面中的详细源信息，例如 " 资源 " ， " 监控 " 和 " 报告 " 。



== 最近的作业活动

" 近期作业活动 " 图块显示您有权访问的任何备份，还原和克隆作业中的最新作业活动。此显示中的作业具有以下状态之一：已完成，警告，失败，正在运行，已排队， 和已取消。

将鼠标悬停在作业上方可提供更多信息。您可以通过单击特定作业编号来查看其他作业信息，此编号会重定向到 " 监控 " 页面。在此页面中，您可以获取作业详细信息或日志信息，并生成特定于该作业的报告。

单击 * 全部查看 * 可查看所有 SnapCenter 作业的历史记录。



== 警报

"Alerts" 图块显示主机和 SnapCenter 服务器的最新未解决严重和警告警报。

" 严重 " 和 " 警告 " 类别警报的总数显示在屏幕顶部。单击 " 严重 " 或 " 警告 " 总计可重定向到 " 警报 " 页面，并在 " 警报 " 页面中应用特定筛选器。

单击特定警报可重定向到警报页面，以了解有关该警报的详细信息。单击屏幕底部的 * 全部查看 * 将重定向到 " 警报 " 页面，以获取所有警报的列表。



== 最新保护摘要

最新的 " 保护摘要 " 图块为您提供有权访问的所有实体的保护状态。默认情况下，此显示设置为提供所有插件的状态。系统会提供有关使用 SnapMirror 和 SnapVault 技术备份到主存储作为 Snapshot 副本以及二级存储的资源的状态信息。二级存储的保护状态信息的可用性取决于所选插件类型。


NOTE: 如果您使用的是镜像 - 存储保护策略，则保护摘要的计数器将显示在 SnapVault 摘要图表中，而不是 SnapMirror 图表中。

通过从下拉菜单中选择一个插件，可以获得各个插件的保护状态。圆环图表显示选定插件的受保护资源百分比。单击一个圆环分区可重定向到 * 报告 * > * 插件 * 页面，该页面可提供有关指定插件的所有主存储活动和二级存储活动的详细报告。


IMPORTANT: 有关二级存储的报告仅适用于 SnapVault ；不支持 SnapMirror 报告。


NOTE: SAP HANA 可为 Snapshot 副本提供主存储和二级存储的保护状态信息。仅主存储保护状态可用于基于文件的备份。

|===
| 保护状态 | 主存储 | 二级存储 


 a| 
失败
 a| 
资源组中已运行备份但备份失败的实体的数量。
 a| 
备份无法传输到二级目标的实体计数。



 a| 
成功
 a| 
已成功备份资源组的资源组中的实体计数。
 a| 
具有已成功传输到二级目标的备份的实体计数。



 a| 
未配置
 a| 
不属于任何资源组且尚未备份的实体的数量。
 a| 
属于一个或多个资源组的实体计数，这些资源组未配置为将备份传输到二级目标。



 a| 
未启动
 a| 
属于资源组但尚未运行备份的实体的数量。
 a| 
不适用。

|===

NOTE: 如果使用 SnapCenter 服务器 4.2 和插件的早期版本（ 4.2 之前的版本）创建备份，则 * 最新保护摘要 * 图块不会显示这些备份的 SnapMirror 保护状态。



== 作业

Jobs （作业）磁贴可为您提供有权访问的备份，还原和克隆作业的摘要。您可以使用下拉菜单自定义任何报告的时间范围。时间范围选项固定在过去 24 小时，过去 7 天和过去 30 天。默认报告显示过去 7 天运行的数据保护作业。

备份，还原和克隆作业信息显示在圆环图表中。单击一个圆环分区会将您重定向到 " 监控 " 页面，其中作业筛选器会预先应用于所选内容。

|===
| 作业状态 | Description 


 a| 
失败
 a| 
失败的作业计数。



 a| 
警告
 a| 
发生错误的作业计数。



 a| 
成功
 a| 
已成功完成的作业计数。



 a| 
正在运行
 a| 
当前正在运行的作业数。

|===


== 存储

" 存储 " 图块显示保护作业在 90 天内占用的主存储和二级存储，以图形方式描绘了使用趋势，并计算了主存储节省量。存储信息每 24 小时在每天中午 12 点更新一次

屏幕顶部将显示一天的总使用量，其中包括 SnapCenter 中可用的备份总数以及这些备份占用的大小。一个备份可能具有多个关联的 Snapshot 副本，并且计数将反映相同的内容。这适用于主 Snapshot 副本和二级 Snapshot 副本。例如，您创建了 10 个备份，其中 2 个因基于策略的备份保留而被删除， 1 个备份由您显式删除。因此，将显示 7 个备份的计数以及这 7 个备份占用的大小。

主存储的存储节省系数是逻辑容量（克隆和 Snapshot 副本节省加上已用存储）与主存储的物理容量之比。条形图显示了存储节省量。

折线图会分别绘制连续 90 天内每天的主存储和二级存储消耗情况。将鼠标悬停在图表上可提供详细的每日结果。


NOTE: 如果使用 SnapCenter 服务器 4.2 和插件的早期版本（ 4.2 之前的版本）创建备份，则 * 存储 * 图块不会显示备份数，这些备份占用的存储， Snapshot 节省量，克隆节省量和 Snapshot 大小。



== Configuration

" 配置 " 图块提供 SnapCenter 正在管理且您有权访问的所有活动独立主机和 Windows 集群主机的整合状态信息。其中包括与这些主机关联的插件状态信息。

单击主机旁边的数字可重定向到主机页面中的受管主机部分。您可以从此处获取选定主机的详细信息。

此外，此显示还会显示 SnapCenter 正在管理且您有权访问的独立 ONTAP SVM 和集群 ONTAP SVM 的总和。单击 SVM 旁边的数字可重定向到 " 存储系统 " 页面。您可以从此处获取选定 SVM 的详细信息。

主机配置状态显示为红色（严重），黄色（警告）和绿色（活动），以及每个状态下的主机数量。系统会为每个状态提供状态消息。

|===
| 配置状态 | Description 


 a| 
必须升级
 a| 
正在运行不受支持的插件且需要升级的主机数量。不受支持的插件与此版本的 SnapCenter 不兼容。



 a| 
必须迁移
 a| 
正在运行不受支持的插件且需要迁移的主机数量。不受支持的插件与此版本的 SnapCenter 不兼容。



 a| 
未安装插件
 a| 
已成功添加但需要安装插件或插件安装失败的主机数。



 a| 
已暂停
 a| 
计划已暂停且正在维护的主机的数量。



 a| 
已停止
 a| 
已启动但插件服务未运行的主机数量。



 a| 
主机已关闭
 a| 
已关闭或无法访问的主机数。



 a| 
升级可用（可选）
 a| 
可升级较新版本插件软件包的主机数量。



 a| 
迁移可用（可选）
 a| 
可迁移较新版本插件的主机数。



 a| 
配置日志目录
 a| 
必须为 SCSQL 配置日志目录才能进行事务日志备份的主机数。



 a| 
配置 VMware 插件
 a| 
需要添加适用于 VMware vSphere 的 SnapCenter 插件的主机数。



 a| 
未知
 a| 
已注册但尚未触发安装的主机计数。



 a| 
正在运行
 a| 
已启动且插件正在运行的主机数量。对于 SCSQL 插件，会配置日志目录和虚拟机管理程序。



 a| 
安装 \ 卸载插件
 a| 
正在安装或卸载插件的主机数。

|===


== 许可容量

" 已许可容量 " 图块可显示有关 SnapCenter 基于容量的标准许可证的总许可容量，已用容量，容量阈值警报和许可证到期警报的信息。


NOTE: 只有在 Cloud Volumes ONTAP 或 ONTAP Select 平台上使用基于 SnapCenter 标准容量的许可证时，才会显示此显示。对于FAS、AFF或全SAN阵列(ASA)平台、SnapCenter许可证基于控制器、许可的容量不受限制、不需要容量许可证。

|===
| 许可证状态 | Description 


 a| 
正在使用中
 a| 
当前正在使用的容量。



 a| 
通知
 a| 
信息板上显示通知的容量阈值，如果配置了此阈值，则还会显示发送电子邮件通知的时间。



 a| 
已获得许可
 a| 
许可容量。



 a| 
超过
 a| 
已超过许可容量的容量。

|===