---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords: Manage storage system 
summary: 添加存储系统后，您可以修改存储系统配置和连接，或者删除存储系统。 
---
= 管理存储系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
添加存储系统后，您可以修改存储系统配置和连接，或者删除存储系统。



== 修改存储系统配置

如果要更改用户名，密码，平台，端口，协议， SnapCenter 超时期限，首选 IP 地址或消息传送选项。

* 关于此任务 *

您可以修改单个用户或组的存储连接。如果您属于一个或多个有权访问同一存储系统的组，则存储连接名称会在存储连接列表中多次显示，每个组对存储系统具有访问权限。

* 步骤 *

. 在左侧导航窗格中，单击 * 存储系统 * 。
. 在存储系统页面中，从 * 类型 * 下拉列表中执行以下操作之一：
+
|===
| 选择 ... | 步骤 


 a| 
ONTAP SVMs
 a| 
查看已添加的所有 Storage Virtual Machine （ SVM ），并修改所需的 SVM 配置。

.. 在存储连接页面中，单击相应的 SVM 名称。
.. 执行以下操作之一：
+
*** 如果 SVM 不属于任何集群，请在修改存储系统页面中修改配置，例如用户名，密码， EMS 和 AutoSupport 设置，平台，协议，端口，超时， 和首选 IP 。
*** 如果 SVM 是集群的一部分，则在修改存储系统页面中，选择 * 独立管理 SVM * 并修改配置，例如用户名，密码， EMS 和 AutoSupport 设置，平台，协议，端口，超时， 和首选 IP 。
+
将 SVM 修改为独立管理后，如果决定通过集群对其进行管理，则应删除此 SVM ，然后单击 * 重新发现 * 。SVM 将添加到 ONTAP 集群中。

+

NOTE: 在 SnapCenter 图形用户界面上更新存储系统密码后，您应重新启动相应插件或服务器主机的 SMCore 服务，因为更新后的密码不会反映在 SMCore 中，并且备份作业将失败并显示凭据不正确的错误。







 a| 
ONTAP 集群
 a| 
查看已添加的所有集群并修改所需的集群配置。

.. 在存储连接页面中，单击集群名称。
.. 在修改存储系统页面中，单击用户名旁边的编辑图标并修改用户名和密码。
.. 选择或清除 EMS 和 AutoSupport 设置。
.. 单击 * 更多选项 * 并修改其他配置，例如平台，协议，端口，超时和首选 IP 。


|===
. 单击 * 提交 * 。




== 删除存储系统

您可以使用 SnapCenter 删除任何未使用的存储系统。

* 关于此任务 *

您可以删除单个用户或组的存储连接。如果您属于一个或多个有权访问同一存储系统的组，则存储系统名称会在存储连接列表中多次显示，每个组对存储系统具有访问权限。


IMPORTANT: 删除存储系统时，对该存储系统执行的所有操作都将失败。

* 步骤 *

. 在左侧导航窗格中，单击 * 存储系统 * 。
. 在存储系统页面的 * 类型 * 下拉列表中，选择 * ONTAP SVM* 或 * ONTAP Clusters* 。
. 在存储连接页面中，选中要删除的 SVM 或集群旁边的复选框。
+

NOTE: 您不能选择属于集群的 SVM 。

. 单击 * 删除 * 。
. 在删除存储系统连接设置页面中，单击 * 确定 * 。
+

NOTE: 如果使用 ONTAP 图形用户界面从 ONTAP 集群中删除了 SVM ，请在 SnapCenter 图形用户界面中单击 * 重新发现 * 以更新 SVM 列表。


