---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter 提供了多种报告选项，可用于监控和管理系统运行状况以及操作成功情况。 
---
= SnapCenter 报告功能概述
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 提供了多种报告选项，可用于监控和管理系统运行状况以及操作成功情况。

|===
| 报告类型 | Description 


 a| 
备份报告
 a| 
备份报告提供了有关 SnapCenter 环境的备份趋势，备份成功率以及指定时间内执行的每个备份的一些信息的整体数据。如果删除了备份，则报告不会显示已删除备份的任何状态信息。备份详细信息报告提供了有关指定备份作业的详细信息，并列出了已成功备份的资源以及任何已失败的资源。



 a| 
克隆报告
 a| 
克隆报告提供了有关 SnapCenter 环境的克隆趋势，克隆成功率的整体数据，以及有关在指定时间内执行的每个克隆作业的一些信息。如果删除了克隆，则报告不会显示已删除克隆的任何状态信息。克隆详细信息报告提供了有关指定克隆，克隆主机和克隆作业任务状态的详细信息。如果任务失败，克隆详细信息报告将显示有关失败的信息。



 a| 
还原报告
 a| 
还原报告提供了有关还原作业的整体信息。还原详细信息报告提供了有关指定还原作业的详细信息，包括主机名，备份名称，作业开始和持续时间以及各个作业任务的状态。如果任务失败，还原详细信息报告将显示有关失败的信息。



 a| 
保护报告
 a| 
这些报告为所有 SnapCenter 插件实例管理的资源提供了保护详细信息。此报告提供了所有插件实例管理的资源的保护详细信息。您可以查看概述，未受保护资源的详细信息，生成报告时未备份的资源，备份操作失败的资源组的资源以及 SnapVault 状态。



 a| 
已计划报告
 a| 
这些报告按计划定期运行，例如每日，每周或每月。报告将在指定日期和时间自动生成，并通过电子邮件发送给相应的人员您可以启用，禁用，修改或删除计划。单击 * 立即运行 * 按钮可以按需运行已启用的计划。管理员可以运行任何计划，但生成的报告将根据创建计划的用户提供的权限包含数据。

除管理员以外的任何其他用户都可以根据其权限查看或修改计划。如果在添加角色页面中选择了此角色的所有成员都可以查看其他成员的对象选项，则此角色的其他成员将能够查看和修改。

|===


== 访问报告

您可以使用 SnapCenter 信息板快速了解系统的运行状况。您可以从信息板深入了解更多详细信息。或者，您也可以直接访问详细报告。

您可以通过以下方法之一访问报告：

* 在左侧导航窗格中，单击 * 信息板 * ，然后单击 * 上次保护摘要 * 饼图以在报告页面中查看更多详细信息。
* 在左侧导航窗格中，单击 * 报告 * 。




== 筛选报告

您可能需要根据一系列参数筛选报告数据，具体取决于所需信息的详细程度和时间范围。

* 步骤 *

. 在左侧导航窗格中，单击 * 报告 * 。
. 如果未显示参数视图，请单击报告工具栏中的 * 切换参数区域 * 图标。
. 指定要运行报告的时间范围。+ 如果省略结束日期，则会检索所有可用信息。
. 根据以下任一条件筛选报告信息：
+
** Resource group
** 主机
** 策略
** 资源
** Status
** 插件名称


. 单击 * 应用 * 。




== 导出或打印报告

通过导出 SnapCenter 报告，您可以使用各种备选格式查看报告。您也可以打印报告。

* 步骤 *

. 在左侧导航窗格中，单击 * 报告 * 。
. 从报告工具栏中，执行以下操作之一：
+
** 单击 * 切换打印预览 * 图标可预览可打印报告。
** 从 * 导出 * 图标下拉列表中选择一种格式，以将报告导出为备用格式。


. 要打印报告，请单击 * 打印 * 图标。
. 要查看特定报告摘要，请滚动到报告的相应部分。




== 为电子邮件通知设置 SMTP 服务器

您可以指定用于向自己或他人发送数据保护作业报告的 SMTP 服务器。您也可以发送测试电子邮件来验证配置。这些设置将全局应用于您为其配置电子邮件通知的任何 SnapCenter 作业。

此选项用于配置 SMTP 服务器以发送所有数据保护作业报告。但是，如果您希望定期向您自己或他人发送特定资源的 SnapCenter 数据保护作业更新，以便监控这些更新的状态，则可以配置此选项，以便在创建资源组时通过电子邮件发送 SnapCenter 报告。

* 步骤 *

. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 全局设置 * 。
. 输入 SMTP 服务器并单击 * 保存 * 。
. 要发送测试电子邮件，请输入电子邮件发往的电子邮件地址，输入主题，然后单击 * 发送 * 。




== 配置用于通过电子邮件发送报告的选项

如果您希望定期向自己或他人发送 SnapCenter 数据保护作业更新，以便监控这些更新的状态，则可以配置在创建资源组时通过电子邮件发送 SnapCenter 报告的选项。

* 您需要的内容 *

您必须已在设置下的全局设置页面上配置 SMTP 服务器。

* 步骤 *

. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 选择要查看的资源类型并单击 * 新建资源组 * ，或者选择现有资源组并单击 * 修改 * 为现有资源组配置电子邮件报告。
. 在新建资源组向导的通知面板中，从下拉菜单中选择是要始终接收报告，还是要在发生故障时接收报告，还是要在发生故障或发出警告时接收报告。
. 输入电子邮件的发件人地址，电子邮件的收件人地址以及电子邮件的主题。

