---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords:  
summary: '您可以从 " 监控 " 页面监控作业进度，获取有关已计划作业的信息以及查看事件和日志。' 
---
= 监控作业，计划，事件和日志
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从 " 监控 " 页面监控作业进度，获取有关已计划作业的信息以及查看事件和日志。



== 监控作业

您可以查看有关 SnapCenter 备份，克隆，还原和验证作业的信息。您可以根据开始和结束日期，作业类型，资源组，策略或 SnapCenter 插件筛选此视图。您还可以获取指定作业的其他详细信息和日志文件。

您还可以监控与 SnapMirror 和 SnapVault 操作相关的作业。


NOTE: 您只能监控已创建且与您相关的作业，除非您获得 SnapCenter 管理员或其他超级用户角色。

您可以执行以下与监控作业相关的任务：

* 监控备份，克隆，还原和验证操作。
* 查看作业详细信息和报告。
* 停止已计划的作业。




== 监控计划

您可能需要查看当前计划，以确定操作何时启动，上次运行时间以及下次运行时间。您还可以确定运行操作的主机以及操作的资源组和策略信息。

* 步骤 *

. 在左侧导航窗格中，单击 * 监控 * 。
. 在 "Monitor" 页面中，单击 * 计划 * 。
. 选择资源组和计划类型。
. 查看已计划操作的列表。




== 监控事件

您可以查看系统中的 SnapCenter 事件列表，例如用户创建资源组时或系统启动活动时，例如创建计划的备份。您可能需要查看事件以确定当前是否正在执行备份或还原操作等操作。

* 关于此任务 *

所有作业信息都会显示在事件页面中。例如，备份作业启动时，将显示 "`backup start` " 事件。备份完成后，将显示 "`backup complete` " 事件。

* 步骤 *

. 在左侧导航窗格中，单击 * 监控 * 。
. 在 "Monitor" 页面中，单击 * 事件 * 。
. （可选）在筛选器框中，输入开始或结束日期，事件类别（例如备份，资源组或策略）和严重性级别，然后单击 * 应用 * 。或者，也可以在搜索框中输入字符。
. 查看事件列表。




== 监控日志

您可以查看和下载 SnapCenter 服务器日志， SnapCenter 主机代理日志和插件日志。您可能希望查看日志以帮助进行故障排除。

* 关于此任务 *

您可以对日志进行筛选，以便仅显示特定的日志严重性级别：

* 调试
* 信息
* 警告
* error
* 致命


您还可以获取作业级别日志，例如有助于对备份作业失败的原因进行故障排除的日志。对于作业级别日志，请使用 * 监控 * > * 作业 * 选项。

* 步骤 *

. 在左侧导航窗格中，单击 * 监控 * 。
. 在作业页面中，选择一个作业，然后单击下载日志。
+
下载的压缩文件夹包含作业日志和常见日志。压缩文件夹名称包含选定的作业 ID 和作业类型。

. 在监控页面中，单击 * 日志 * 。
. 选择日志类型，主机和实例。
+
如果选择日志类型为 * 插件 * ，则可以选择主机或 SnapCenter 插件。如果日志类型为 * 服务器 * ，则无法执行此操作。

. 要按特定源，消息或日志级别筛选日志，请单击列标题顶部的筛选器图标。
+
要显示所有日志，请选择 * 大于或等于 * 作为 `Debug` 级别。

. 单击 * 刷新 * 。
. 查看日志列表。
. 单击 * 下载 * 下载日志。
+
下载的压缩文件夹包含作业日志和常见日志。压缩文件夹名称包含选定的作业 ID 和作业类型。



在大型配置中，为了获得最佳性能，您应使用 PowerShell cmdlet 将 SnapCenter 的日志设置设置为最低级别。

`sET-SmLogSettings -LogLevel All -MaxFileSize 10MB -MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB -Server`


NOTE: 要在故障转移作业完成后访问运行状况或配置信息，请运行 cmdlet `Get-SmRepositoryConfig` 。



== 从 SnapCenter 中删除作业和日志

您可以从 SnapCenter 中删除备份，还原，克隆和验证作业和日志。SnapCenter 会无限期存储成功和失败的作业日志，除非您将其删除。您可能需要删除它们以补充存储。

* 关于此任务 *

当前不能有正在运行的作业。您可以通过提供作业 ID 来删除特定作业，也可以在指定时间段内删除作业。

您无需将主机置于维护模式即可删除作业。

* 步骤 *

. 启动 PowerShell 。
. 在命令提示符处，输入： `Open-SMConnection`
. 在命令提示符处，输入： `Remove-SmJobs`
. 在左侧导航窗格中，单击 * 监控 * 。
. 在监控页面中，单击 * 作业 * 。
. 在作业页面中，查看作业的状态。


* 查找更多信息 *

有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["《 SnapCenter 软件 cmdlet 参考指南》"^]。
