---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords: Manage policies 
summary: 您可以将策略与资源或资源组分离，修改，删除，查看和复制。 
---
= 管理策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将策略与资源或资源组分离，修改，删除，查看和复制。



== 修改策略

在策略附加到资源或资源组时，您可以修改复制选项， Snapshot 副本保留设置，错误重试次数或脚本信息。只有在断开策略后，才能修改计划类型（频率）。

* 关于此任务 *

修改策略中的计划类型需要执行其他步骤，因为 SnapCenter 服务器仅在策略附加到资源或资源组时才会注册计划类型。

|===
| 如果您要 ... | 那么 ... 


 a| 
添加其他计划类型
 a| 
创建新策略并将其附加到必要的资源或资源组。

例如，如果某个资源组策略仅指定每小时备份，而您也要添加每日备份，则可以创建一个具有每日计划类型的策略并将其添加到资源组中。然后，该资源组将具有两个策略：每小时和每天。



 a| 
删除或更改计划类型
 a| 
执行以下操作：

. 将策略与使用该策略的每个资源和资源组分离。
. 修改计划类型。
. 将此策略重新附加到所有资源和资源组。


例如，如果某个策略指定每小时备份，而您希望将其更改为每天备份，则必须先断开此策略。

|===
* 步骤 *

. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 策略 * 。
. 选择策略，然后单击 * 修改 * 。
. 修改此信息，然后单击 * 完成 * 。




== 分离策略

您可以随时从资源或资源组中断开策略，而不再需要这些策略来控制资源的数据保护。必须先断开策略，然后才能将其删除或修改计划类型。

* 步骤 *

. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 在资源页面中，从 * 视图 * 列表中选择 * 资源组 * 。
. 选择资源组，然后单击 * 修改资源组 * 。
. 在修改资源组向导的策略页面中，从下拉列表中清除要断开的策略旁边的复选标记。
. 在向导的其余部分中对资源组进行任何其他修改，然后单击 * 完成 * 。




== 删除策略

如果您不再需要策略，则可能需要将其删除。

.开始之前
如果策略与任何资源或资源组关联，则应将此策略与资源或资源组分离。

* 步骤 *

. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 策略 * 。
. 选择策略，然后单击 * 删除 * 。
. 单击 * 是 * 。

