---
permalink: admin/concept_manage_the_snapcenter_server_repository.html 
sidebar: sidebar 
keywords:  
summary: 与从 SnapCenter 执行的各种操作相关的信息存储在 SnapCenter 服务器数据库存储库中。您必须为存储库创建备份，以防止 SnapCenter 服务器数据丢失。 
---
= 管理 SnapCenter 服务器存储库
:icons: font
:imagesdir: ../media/


[role="lead"]
与从 SnapCenter 执行的各种操作相关的信息存储在 SnapCenter 服务器数据库存储库中。您必须为存储库创建备份，以防止 SnapCenter 服务器数据丢失。

SnapCenter 服务器存储库有时称为 NSM 数据库。



== 保护 SnapCenter 存储库的前提条件

您的环境应满足保护 SnapCenter 存储库的特定前提条件。

* 管理 Storage Virtual Machine （ SVM ）连接
+
您应配置存储凭据。

* 配置主机
+
SnapCenter 存储库主机上应至少存在一个 NetApp 存储磁盘。如果 SnapCenter 存储库主机上不存在 NetApp 磁盘，则必须创建一个。

+
有关添加主机，设置 SVM 连接和配置主机的详细信息，请参见安装说明。

* 配置 iSCSI LUN 或 VMDK
+
对于高可用性（ HA ）配置，您可以在其中一个 SnapCenter 服务器中配置 iSCSI LUN 或 VMDK 。





== 备份 SnapCenter 存储库

备份 SnapCenter 服务器存储库有助于防止数据丢失。您可以运行 _protect-SmRepository_ cmdlet 来备份存储库。

* 关于此任务 *

使用 _protect-SmRepository_ cmdlet 可完成以下任务：

* 创建资源组和策略
* 为 SnapCenter 存储库创建备份计划


* 步骤 *

. 启动 PowerShell 。
. 在 SnapCenter 服务器主机上，使用 _Open-SmConnection_ cmdlet 建立会话，然后输入凭据。
. 使用 _protect-SmRepository_ cmdlet 和所需参数备份存储库。




== 查看 SnapCenter 存储库的备份

您可以运行 _Get-SmRepositoryBackups_cmdlet 来显示 SnapCenter 服务器数据库存储库备份列表。

系统将根据 _protect-SmRepository_ cmdlet 中指定的计划创建存储库备份。

* 步骤 *

. 启动 PowerShell 。
. 在命令提示符处，输入以下 cmdlet ，然后提供用于连接到 SnapCenter 服务器的凭据： _Open-SMConnection_
. 使用 _Get-SmRepositoryBackups_cmdlet 列出所有可用的 SnapCenter 数据库备份。




== 还原 SnapCenter 数据库存储库

您可以通过运行 _Restore-SmRepositoryBackup_ cmdlet 来还原 SnapCenter 存储库。

还原 SnapCenter 存储库时，正在运行的其他 SnapCenter 操作将受到影响，因为在还原操作期间，存储库数据库不可访问。

* 步骤 *

. 启动 PowerShell 。
. 在命令提示符处，输入以下 cmdlet ，然后提供用于连接到 SnapCenter 服务器的凭据： _Open-SMConnection_
. 使用 _Restore-SmRepositoryBackup_ cmdlet 还原存储库备份。
+
以下 cmdlet 可从 iSCSI LUN 或 VMDK 上的现有备份还原 SnapCenter MySQL 数据库存储库：

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445
----
+
当 iSCSI LUN 中的备份文件意外删除时，以下 cmdlet 会还原 SnapCenter MySQL 数据库。对于 VMDK ，手动从 ONTAP Snapshot 副本还原备份。

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445 -RestoreFileSystem
----




== 迁移 SnapCenter 存储库

您可以将 SnapCenter 服务器数据库存储库从默认位置迁移到另一个磁盘。如果要将存储库重新定位到具有更多空间的磁盘，则可以迁移该存储库。

* 步骤 *

. 在 Windows 中停止 MYSQL57 服务。
. 找到 MySQL 数据目录。
+
通常，您可以在 C ： \ProgramData\MySQL\MySQL Server 5.7\Data 中找到数据目录。

. 将 MySQL 数据目录复制到新位置，例如 E ： \Data\NSM 。
. 右键单击新目录，然后选择 * 属性 * > * 安全性 * 将网络服务本地服务器帐户添加到新目录中，然后为帐户分配完全控制权。
. 重命名原始数据库目录，例如 Nsm_copy 。
. 在 Windows 命令提示符处，使用 _mklink_ 命令创建一个符号目录链接。
+
` "mklink /d "C ： \ProgramData\MySQL\MySQL Server 5.7\Data\NSM" E ： \Data\NSM" "`

. 在 Windows 中启动 MYSQL57 服务。
. 登录到 SnapCenter 并检查存储库条目，或者登录到 MySQL 实用程序并连接到新存储库，以验证数据库位置更改是否成功。
. 删除已重命名的原始数据库存储库目录（ Nsm_copy ）。




== 重置 SnapCenter 存储库密码

从 SnapCenter 4.2 安装 SnapCenter 服务器期间，系统会自动生成 MySQL 服务器存储库数据库密码。SnapCenter 用户在任何时候都不知道自动生成的密码。如果要访问存储库数据库，应重置密码。

* 您需要的内容 *

要重置密码，您应具有 SnapCenter 管理员权限。

* 步骤 *

. 启动 PowerShell 。
. 在命令提示符处，输入以下命令，然后提供用于连接到 SnapCenter 服务器的凭据： _Open-SMConnection_
. 重置存储库密码： _set-SmRepositoryPassword_
+
以下命令将重置存储库密码：

+
[listing]
----

Set-SmRepositoryPassword at command pipeline position 1
Supply values for the following parameters:
NewPassword: ********
ConfirmPassword: ********
Successfully updated the MySQL server password.
----


* 查找更多信息 *

有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143["《 SnapCenter 软件 cmdlet 参考指南》"^]。
