---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords: Manage resource groups 
summary: 您可以对资源组执行各种操作。 
---
= 管理资源组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以对资源组执行各种操作。

您可以执行以下与资源组相关的任务：

* 通过选择资源组并单击 * 修改资源组 * 来编辑在创建资源组时提供的信息来修改资源组。
+

NOTE: 您可以在修改资源组时更改计划。但是，要更改计划类型，必须修改策略。

+

NOTE: 如果从资源组中删除资源，则当前附加到资源组的策略中定义的备份保留设置将继续应用于已删除的资源。

* 创建资源组的备份。
* 创建备份的克隆。
+
您可以从 SQL ， Oracle ， Windows 文件系统，自定义应用程序和 SAP HANA 数据库资源或资源组的现有备份中进行克隆。

* 创建资源组的克隆。
+
只有 SQL 资源组（仅包含数据库）才支持此操作。您可以配置克隆资源组的计划（克隆生命周期）。

* 阻止启动对资源组的计划操作。
* 删除资源组。




== 停止并恢复对资源组的操作

您可以暂时禁止对资源组启动计划的操作。稍后，您可以根据需要启用这些操作。

* 步骤 *

. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 在资源页面中，从 * 视图 * 列表中选择 * 资源组 * 。
. 选择资源组并单击 * 维护 * 。
. 单击 * 确定 * 。


如果要恢复对已置于维护模式的资源组执行的操作，请选择该资源组并单击 * 生产 * 。



== 删除资源组

如果不再需要保护资源组中的资源，可以删除该资源组。在从 SnapCenter 中删除插件之前，必须确保已删除资源组。

* 关于此任务 *

您应手动删除为资源组中的任何资源创建的所有克隆。您可以选择强制删除与资源组关联的所有备份、元数据、策略和快照。

* 步骤 *

. 在左侧导航窗格中，单击 * 资源 * ，然后从列表中选择相应的插件。
. 在资源页面中，从 * 视图 * 列表中选择 * 资源组 * 。
. 选择资源组，然后单击 * 删除 * 。
. 可选：选中*删除与此资源组关联的备份和断开策略*复选框，以删除与该资源组关联的所有备份、元数据、策略和快照。
. 单击 * 确定 * 。

