---
permalink: protect-postgresql/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: '在使用PowerShell cmdlet备份、还原或克隆PostgreSQL集群之前、您必须先创建Storage Virtual Machine (SVM)连接和凭据。' 
---
= 使用适用于PostgreSQL的PowerShell cmdlet创建存储系统连接和凭据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用PowerShell cmdlet备份、还原或克隆PostgreSQL集群之前、您必须先创建Storage Virtual Machine (SVM)连接和凭据。

.开始之前
* 您应已准备好 PowerShell 环境以执行 PowerShell cmdlet 。
* 您应具有创建存储连接所需的基础架构管理员角色权限。
* 您应确保插件安装未在进行中。
+
添加存储系统连接时、不得正在安装主机插件、因为主机缓存可能未更新、集群状态可能会在SnapCenter图形用户界面中显示为"`Not available for backup`"或"`not on NetApp storage`"。

* 存储系统名称应是唯一的。
+
SnapCenter 不支持在不同集群上使用相同名称的多个存储系统。SnapCenter 支持的每个存储系统都应具有唯一的名称和唯一的数据 LIF IP 地址。



.步骤
. 使用Open-SmConnection cmdlet启动PowerShell Core连接会话。
+
[listing]
----
PS C:\> Open-SmConnection
----
. 使用 Add-SmStorageConnection cmdlet 创建与存储系统的新连接。
+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. 使用 Add-SmCredential cmdlet 创建新凭据。
+
此示例说明如何使用 Windows 凭据创建名为 FinanceAdmin 的新凭据：

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
. 将PostgreSQL通信主机添加到SnapCenter服务器。
+
[listing]
----
PS C:> Add-SmHost -HostName 10.232.204.61 -OSType Windows -RunAsName FinanceAdmin -PluginCode PostgreSQL
----
. 在主机上安装适用于PostgreSQL的软件包和SnapCenter插件。
+
对于 Linux ：

+
[listing]
----
PS C:> Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode PostgreSQL
----
+
对于 Windows ：

+
[listing]
----
Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode PostgreSQL -FilesystemCode scw -RunAsName FinanceAdmin
----
. 设置SQLLIB的路径。
+
对于Windows、PostgreSQL插件将使用SQLLIB文件夹的默认路径：C：\Program Files\IBM\SQLIB\bin

+
如果要覆盖默认路径、请使用以下命令。

+
[listing]
----
PS C:> Set-SmConfigSettings -Plugin -HostName 10.232.204.61 -PluginCode
PostgreSQL -configSettings @{“PostgreSQL_SQLLIB_CMD” = “<custom_path>\IBM\SQLLIB\BIN”}

----


有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《 SnapCenter 软件 cmdlet 参考指南》"^]。
