---
permalink: install/concept_requirements_for_using_fc_rdm_luns_in_a_microsoft_cluster.html 
sidebar: sidebar 
keywords:  
summary: 如果您满足特定配置要求，适用于 Windows 的插件可为在属于两个不同 ESX 或 ESXi 服务器的两个不同虚拟机上使用 FC RDM LUN 的 Microsoft 集群提供支持，这两个虚拟机也称为跨机集群。 
---
= 在 Microsoft 集群中使用 FC RDM LUN 的要求
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您满足特定配置要求，适用于 Windows 的插件可为在属于两个不同 ESX 或 ESXi 服务器的两个不同虚拟机上使用 FC RDM LUN 的 Microsoft 集群提供支持，这两个虚拟机也称为跨机集群。

* 虚拟机（ VM ）必须运行相同的 Windows Server 版本。
* 每个 VMware 父主机的 ESX 或 ESXi 服务器版本必须相同。
* 每个父主机必须至少具有两个网络适配器。
* 两个 ESX 或 ESXi 服务器之间必须至少共享一个 VMware 虚拟机文件系统（ VMFS ）数据存储库。
* VMware 建议在 FC SAN 上创建共享数据存储库。
+
如有必要，还可以通过 iSCSI 创建共享数据存储库。

* 共享 RDM LUN 必须处于物理兼容模式。
* 必须在适用于 Windows 的插件之外手动创建共享 RDM LUN 。
+
您不能将虚拟磁盘用于共享存储。

* 必须在集群中的每个虚拟机上以物理兼容模式配置 SCSI 控制器：
+
Windows Server 2008 R2 要求您在每个虚拟机上配置 LSI Logic SAS SCSI 控制器。如果只有一种类型的 LSI Logic SAS 控制器存在，并且该控制器已连接到 C ：驱动器，则共享 LUN 无法使用现有 LSI Logic SAS 控制器。

+
VMware Microsoft 集群不支持半虚拟类型的 SCSI 控制器。

+

NOTE: 在物理兼容模式下将 SCSI 控制器添加到虚拟机上的共享 LUN 时，必须在 VMware Infrastructure Client 中选择 * 原始设备映射 * （ RDM ）选项，而不是 * 创建新磁盘 * 选项。

* Microsoft 虚拟机集群不能属于 VMware 集群。
* 在属于 Microsoft 集群的虚拟机上安装适用于 Windows 的插件时，您必须使用 vCenter 凭据，而不是 ESX 或 ESXi 凭据。
* 适用于 Windows 的插件无法使用多个主机中的启动程序创建一个 igroup 。
+
在创建要用作共享集群磁盘的 RDM LUN 之前，必须在存储控制器上创建包含所有 ESXi 主机中的启动程序的 igroup 。

* 确保使用 FC 启动程序在 ESXi 5.0 上创建 RDM LUN 。
+
创建 RDM LUN 时，系统将使用 ALUA 创建启动程序组。


