---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: SnapCenter 6.1支持ASA R2系统、可根据仅SAN客户的需求提供简化的体验。 
---
= 了解如何在SnapCenter中支持ASA R2系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 6.1支持ASA R2系统、可根据仅SAN客户的需求提供简化的体验。

ASA R2系统在一个HA对部署中支持所有SAN协议(iSCSI、FC和基于TCP/IP的NVMe)。SCSI (iSCSI和FC)协议使用对称双主动架构实现多路径、以便主机和存储之间的所有路径都处于主动/优化状态。iSCSI和NVMe/TCP协议支持主机和存储之间的直接路径。


NOTE: SnapCenter在ASA R2系统上仅支持VMware虚拟机文件系统(Virtual Machine File System、VMFS)。

ASA R2系统介绍了如何使用具有一致性组的存储单元：

* 存储单元可为SAN主机提供用于数据操作的存储空间。存储单元是指SCSI主机的LUN或NVMe主机的NVMe命名空间。
* 一致性组是指作为单个单元进行管理的一组存储单元。


ASA R2系统使用存储单元和一致性组来简化存储管理和数据保护。例如、假设您有一个数据库、其中一个一致性组包含10个存储单元、您需要备份整个数据库。您可以通过备份一致性组来保护整个数据库、而不是单独备份每个存储单元。

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["详细了解ASA R2系统"](英文)



== 适用于ASA R2系统的SnapCenter 6.1支持的内容

如果您使用的是ASA R2存储系统、则使用SnapCenter可以对SnapCenter支持的所有应用程序执行以下操作：

* 通过VMDK为应用程序创建主备份
* 将一致性组快照传输到二级存储系统
* 还原备份并从备用位置还原
+
** 使用VMware vMotion从主存储和二级存储进行原位还原
** 从主存储和二级存储连接和复制还原


* 克隆备份并克隆到备用位置




== 适用于ASA R2系统的SnapCenter 6.1不支持的功能

* 原始设备映射(RDM)
* 适用于Oracle的应用程序卷
* SAP HANA NDV
* LockVault
* 防篡改快照
* Flex Group
* 分层一致性组
* 从ONTAP 9.x迁移到ASA R2系统
* 重命名快照
* SnapCenter不支持对SQL插件主机的日志目录进行二级配置。您应使用ONTAP命令行界面或系统管理器手动配置。

