---
permalink: install/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: 您应了解支持的存储系统，应用程序和数据库。 
---
= 支持的存储系统和应用程序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应了解支持的存储系统，应用程序和数据库。

* SnapCenter 支持 ONTAP 9.12.1 及更高版本来保护数据。
+
对于ONTAP 9.12.1及更低版本、在还原过程中从SnapLock存储快照创建的克隆将继承SnapLock存储到期时间。存储管理员应在SnapLock到期时间后手动清理克隆。

* SnapCenter 6.1支持运行ONTAP 9.161的NetApp ASA R2系统。
+
ASA R2系统可为基于全闪存平台构建的纯SAN环境提供统一的硬件和软件解决方案。

+
有关ASA R2系统的信息，请参见 https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2文档"^]。

* SnapCenter支持Amazon FSx for NetApp ONTAP以保护您的数据。
+
如果您使用的是适用于 NetApp ONTAP 的 Amazon FSx ，请确保 SnapCenter 服务器主机插件升级到 4.5 P1 或更高版本以执行数据保护操作。

+
支持基于传输控制协议(TCP)的非易失性内存快速(NVMe)。

+
有关适用于 NetApp ONTAP 的 Amazon FSX 的信息，请参见 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP 文档"^]。

* SnapCenter 支持保护不同的应用程序和数据库。
+
有关支持的应用程序和数据库的详细信息，请参见 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 互操作性表工具"^]。

* SnapCenter 4.9 P1及更高版本支持在基于Amazon Web Services (AWS)的VMware Cloud软件定义的数据中心(SDDC)环境中保护Oracle和Microsoft SQL工作负载。
+
有关详细信息，请参见 https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["在AWS SDDC环境中的VMware Cloud中使用NetApp SnapCenter保护Oracle、MS SQL工作负载"]。


