---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: 在安装 SnapCenter 服务器和应用程序或数据库插件之前，应确保满足连接和端口要求。 
---
= 连接和端口要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装 SnapCenter 服务器和应用程序或数据库插件之前，应确保满足连接和端口要求。

* 应用程序无法共享端口。
+
每个端口都必须专用于相应的应用程序。

* 对于可自定义的端口，如果您不想使用默认端口，则可以在安装期间选择自定义端口。
+
您可以在安装后使用修改主机向导更改插件端口。

* 对于固定端口，您应接受默认端口号。
* 防火墙
+
** 防火墙，代理或其他网络设备不应干扰连接。
** 如果您在安装 SnapCenter 时指定了自定义端口，则应在插件主机上为 SnapCenter 插件加载程序的该端口添加防火墙规则。




下表列出了不同的端口及其默认值。

|===
| 端口名称 | 端口号 | 协议 | 方向 | Description 


 a| 
SnapCenter 端口
 a| 
8146
 a| 
HTTPS
 a| 
双向
 a| 
此端口用于SnapCenter客户端(SnapCenter用户)和SnapCenter服务器之间的通信、也用于从插件主机到SnapCenter服务器的通信。

您可以自定义端口号。



 a| 
SnapCenter SMCore 通信端口
 a| 
8145
 a| 
HTTPS
 a| 
双向
 a| 
此端口用于在SnapCenter 服务器与安装SnapCenter 插件的主机之间进行通信。

您可以自定义端口号。



 a| 
计划程序服务端口
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
此端口用于集中编排SnapCenter服务器主机中所有受管插件的SnapCenter计划程序工作流。

您可以自定义端口号。



 a| 
Rabbitmq端口
 a| 
5672
 a| 
TCP
 a| 
 a| 
这是Rabbitmq侦听的默认端口、用于在计划程序服务和SnapCenter之间进行发布者-订阅者模型通信。



 a| 
MySQL 端口
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
此端口用于与SnapCenter存储库数据库进行通信。您可以创建从SnapCenter服务器到MySQL服务器的安全连接。 link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["了解更多信息。"]



 a| 
Windows 插件主机
 a| 
135、445
 a| 
TCP
 a| 
 a| 
此端口用于SnapCenter服务器与安装此插件的主机之间的通信。Microsoft指定的其他动态端口范围也应处于打开状态。



 a| 
Linux 或 AIX 插件主机
 a| 
22
 a| 
SSH
 a| 
单向
 a| 
此端口用于SnapCenter服务器与主机之间的通信、此通信是从服务器启动到客户端主机的。



 a| 
适用于Windows、Linux或AIX的SnapCenter插件软件包
 a| 
8145
 a| 
HTTPS
 a| 
双向
 a| 
此端口用于SMCore与安装了插件包的主机之间的通信。可自定义。

您可以自定义端口号。



 a| 
适用于 Oracle 数据库的 SnapCenter 插件
 a| 
27216
 a| 
 a| 
 a| 
适用于 Oracle 的插件使用默认 JDBC 端口连接到 Oracle 数据库。



 a| 
适用于Exchange数据库的SnapCenter插件
 a| 
909
 a| 
 a| 
 a| 
默认的NET。 适用于Windows的插件使用TCP端口连接到Exchange VSS回调。



 a| 
NetApp支持的SnapCenter插件
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
这是一个仅在自定义插件主机上使用的内部端口；不需要防火墙异常。

SnapCenter 服务器与自定义插件之间的通信通过端口 8145 进行路由。



 a| 
ONTAP 集群或 SVM 通信端口
 a| 
* 443 (HTTPS)
* 80 (HTTP)

 a| 
* HTTPS
* HTTP

 a| 
双向
 a| 
SAL （存储抽象层）使用此端口在运行 SnapCenter 服务器的主机与 SVM 之间进行通信。SnapCenter for Windows 插件主机上的 SAL 当前也使用此端口在 SnapCenter 插件主机与 SVM 之间进行通信。



 a| 
适用于 SAP HANA 数据库的 SnapCenter 插件
 a| 
* 3instance_number13
* 3instance_number15

 a| 
* HTTPS
* HTTP

 a| 
双向
 a| 
对于多租户数据库容器（ MDC ）单租户，端口号以 13 结尾；对于非 MDC ，端口号以 15 结尾。

您可以自定义端口号。



 a| 
适用于PostgreSQL的SnapCenter插件
 a| 
5432
 a| 
 a| 
 a| 
此端口是PostgreSQL插件用于与PostgreSQL集群通信的默认PostgreSQL端口。

您可以自定义端口号。

|===
要修改端口详细信息，请参见 link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["修改插件主机"]。
