---
permalink: install/task_install_the_snapcenter_server_using_the_install_wizard.html 
sidebar: sidebar 
keywords: install, snapcenter software, install wizard, features enabled 
summary: 您可以运行 SnapCenter 服务器安装程序可执行文件来安装 SnapCenter 服务器。 
---
= 在Windows主机上安装SnapCenter服务器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以运行 SnapCenter 服务器安装程序可执行文件来安装 SnapCenter 服务器。

您可以选择使用 PowerShell cmdlet 执行多个安装和配置过程。您应使用7.4.2或更高版本。


NOTE: 不支持使用命令行静默安装 SnapCenter 服务器。

.开始之前
* SnapCenter 服务器主机必须是最新的 Windows 更新，并且不会发生待定系统重新启动。
* 您应确保计划安装 SnapCenter 服务器的主机上未安装 MySQL 服务器。
* 您应已启用 Windows 安装程序调试。
+
有关启用的信息，请参见 Microsoft 网站 https://support.microsoft.com/kb/223300["Windows 安装程序日志记录"^]。

+

NOTE: 您不应将 SnapCenter 服务器安装在具有 Microsoft Exchange Server ， Active Directory 或域名服务器的主机上。



.步骤
. 从下载 SnapCenter 服务器安装包 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp 支持站点"^]。
. 双击下载的 .exe 文件启动 SnapCenter 服务器安装。
+
启动安装后，系统将执行所有预检，如果不满足最低要求，则会显示相应的错误或警告消息。

+
您可以忽略警告消息并继续安装；但是，错误应予以修复。

. 查看安装 SnapCenter 服务器所需的预填充值，并根据需要进行修改。
+
您不必指定 MySQL Server 存储库数据库的密码。在 SnapCenter 服务器安装期间，系统会自动生成密码。

+

NOTE: 存储库数据库的自定义路径不支持特殊字符 "` %` " 。如果在路径中包含 "` %` " ，则安装将失败。

. 单击 * 立即安装 * 。
+
如果指定的值无效，则会显示相应的错误消息。您应重新输入这些值，然后启动安装。

+

NOTE: 如果单击 * 取消 * 按钮，则正在执行的步骤将完成，然后启动回滚操作。SnapCenter 服务器将从主机中完全删除。

+
但是，如果在执行 SnapCenter 服务器站点重新启动或等待 SnapCenter 服务器启动操作时单击 * 取消 * ，则安装将继续进行，而不会取消此操作。

+
日志文件始终列在管理员用户的 %temp% 文件夹中（最早的先列出）。如果要重定向日志位置，请从命令提示符处运行以下命令来启动 SnapCenter 服务器安装：``C ： \installer_location\installer_name.exe /log"C" ： \"``





== 安装期间在 Windows 主机上启用的功能

SnapCenter 服务器安装程序可在安装期间在 Windows 主机上启用 Windows 功能和角色。这些可能对故障排除和维护主机系统有用。

|===
| 类别 | 功能 


 a| 
Web 服务器
 a| 
* Internet 信息服务
* 全球 Web 服务
* 常见 HTTP 功能
+
** 默认文档
** 目录浏览
** HTTP 错误
** HTTP 重定向
** 静态内容
** WebDAV 发布


* 运行状况和诊断
+
** 自定义日志记录
** HTTP 日志记录
** 日志记录工具
** 请求监控器
** 跟踪


* 性能功能
+
** 静态内容压缩


* 安全性
+
** IP 安全性
** 基本身份验证
** 集中式 SSL 证书支持
** 客户端证书映射身份验证
** IIS 客户端证书映射身份验证
** IP 和域限制
** 请求筛选
** URL 授权
** Windows 身份验证


* 应用程序开发功能
+
** .NET 可扩展性 4.5
** 应用程序初始化
** ASP.NET Core 8.0.12 (以及所有后续的8.0.x修补程序)托管包
** 服务器端包括
** WebSocket 协议


* 管理工具
+
** IIS 管理控制台






 a| 
IIS 管理脚本和工具
 a| 
* IIS 管理服务
* Web 管理工具




 a| 
+.NET Framework 8.0.12功能+
 a| 
* ASP.NET Core 8.0.12 (以及所有后续的8.0.x修补程序)托管包
* Windows Communication Foundation （ WCF ） HTTP 激活 45
+
** TCP 激活
** HTTP 激活




有关.NET专用的故障排除信息、请参见 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["对于没有Internet连接的原有系统、SnapCenter 升级或安装失败"^]。



 a| 
Windows 进程激活服务
 a| 
流程模型



 a| 
配置 API
 a| 
全部

|===