---
permalink: install/task_create_an_ontap_cluster_role_with_minimum_privileges.html 
sidebar: sidebar 
keywords: ONTAP cluster role, privileges 
summary: 您应创建一个具有最低权限的 ONTAP 集群角色，以便不必使用 ONTAP 管理员角色在 SnapCenter 中执行操作。 
---
= 创建具有最低权限的 ONTAP 集群角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应创建一个具有最低权限的 ONTAP 集群角色，以便不必使用 ONTAP 管理员角色在 SnapCenter 中执行操作。您可以运行多个 ONTAP 命令行界面命令来创建 ONTAP 集群角色并分配最低权限。

* 步骤 *

. 在存储系统上，创建一个角色并为该角色分配所有权限。
+
`ssecurity login role create – vserver <cluster_name\>- role <role_name\> -cmddirname <permission\>`

+

NOTE: 您应对每个权限重复此命令。

. 创建一个用户并将该角色分配给该用户。
+
`ssecurity login create -user <user_name\> -vserver <cluster_name\> -application ontapi -authmethod password -role <role_name\>`

. 解除用户锁定。
+
`ssecurity login unlock -user <user_name\> -vserver <cluster_name\>`





== 用于创建集群角色和分配权限的 ONTAP 命令行界面命令

您应运行多个 ONTAP 命令行界面命令来创建集群角色和分配权限。

* `ssecurity login role create -role role_name -cmddirname "cluster identity modify" -vserver Cluster_name 或 cluster_name -access all`
* `ssecurity login role create -role role_name -cmddirname "cluster identity show" -vserver Cluster_name -access all`
* `ssecurity login role create -role role_name -cmddirname "cluster modify" -vserver Cluster_name -access all`
* `ssecurity login role create -role role_name -cmddirname "cluster peer show" -vserver Cluster_name -access all`
* `ssecurity login role create -role role_name -cmddirname "cluster show" -vserver Cluster_name -access all`
* `ssecurity login role create -role role_name -cmddirname "event generate-autosupport-log" -vserver Cluster_name -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "job history show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "job stop" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "LUN" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun igroup add" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun igroup create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun igroup delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun igroup modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun igroup rename" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun igroup show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun mapping add-reporting-nodes" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun mapping create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun mapping delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun mapping remove-reporting-nodes" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun mapping show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun move-in-volume" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun offline" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun online" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun persistent-reservation clear" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun resize" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "LUN serial " -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "lun show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "network interface create" -access readonly`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "network interface delete" -access readonly`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "network interface modify" -access readonly`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "network interface show" -access readonly`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "security login" -access readonly`
* `ssecurity login role create -role role_name -cmddirname "snapmirror create" -vserver Cluster_name -access all`
* `ssecurity login role create -role role_name -cmddirname "snapmirror list-destinations" -vserver Cluster_name -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror policy add-rule" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror policy create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror policy delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror policy modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror policy modify-rule" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror policy remove-rule" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror policy show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror restore" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror show-history" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror update" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "snapmirror update-ls-set" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system license add" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system license clean-up" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system license delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system license show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system license status show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system node modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system node show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "system status show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "version" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume clone create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume clone show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume clone split start" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume clone split stop" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume destroy" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume file clone create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume file show-disk-usage" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume offline" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume online" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume qtree create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume qtree delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume qtree modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume qtree show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume restrict" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot promote " -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot rename" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot restore" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot restore-file" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume snapshot show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "volume unmount " -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs share modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs share create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs share delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs share modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs share show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "Vserver cifs show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver export-policy create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver export-policy delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver export-policy rule create" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver export-policy rule delete" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver export-policy rule modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver export-policy rule show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver export-policy show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver iscsi connection show" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver modify" -access all`
* `ssecurity login role create -vserver Cluster_name -role role_name -cmddirname "vserver show" -access all`

