---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks 
summary: Windows 主机将存储系统上的 LUN 视为虚拟磁盘。您可以使用 SnapCenter 创建和配置 FC 连接或 iSCSI 连接的 LUN 。 
---
= 创建和管理磁盘
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 主机将存储系统上的 LUN 视为虚拟磁盘。您可以使用 SnapCenter 创建和配置 FC 连接或 iSCSI 连接的 LUN 。


NOTE: SnapCenter 不支持重命名磁盘。如果重命名由 SnapCenter 管理的磁盘， SnapCenter 操作将失败。



== 查看主机上的磁盘

您可以查看使用 SnapCenter 管理的每个 Windows 主机上的磁盘。

* 步骤 *

. 在左侧导航窗格中，单击 * 主机 * 。
. 在主机页面中，单击 * 磁盘 * 。
. 从 * 主机 * 下拉列表中选择主机。
+
此时将列出这些磁盘。





== 查看集群模式磁盘

您可以查看使用 SnapCenter 管理的集群上的集群磁盘。只有在从主机下拉列表中选择集群时，才会显示集群磁盘。

* 步骤 *

. 在左侧导航窗格中，单击 * 主机 * 。
. 在主机页面中，单击 * 磁盘 * 。
. 从 * 主机 * 下拉列表中选择集群。
+
此时将列出这些磁盘。





== 创建 FC 连接或 iSCSI 连接的 LUN 或磁盘

Windows 主机将存储系统上的 LUN 视为虚拟磁盘。您可以使用 SnapCenter 创建和配置 FC 连接或 iSCSI 连接的 LUN 。

* 您需要的内容 *

* 您必须已为存储系统上的 LUN 创建卷。
+
此卷应仅包含 LUN ，而只能包含使用 SnapCenter 创建的 LUN 。

+

NOTE: 除非已拆分此克隆，否则无法在 SnapCenter 创建的克隆卷上创建 LUN 。

* 您必须已在存储系统上启动 FC 或 iSCSI 服务。
* 如果您使用的是 iSCSI ，则必须已与存储系统建立 iSCSI 会话。
* 适用于 Windows 的 SnapCenter 插件软件包只能安装在要创建磁盘的主机上。


* 关于此任务 *

* 除非 LUN 由 Windows Server 故障转移集群中的主机共享，否则不能将 LUN 连接到多个主机。
* 如果 LUN 由使用 CSV （集群共享卷）的 Windows Server 故障转移集群中的主机共享，则必须在拥有集群组的主机上创建磁盘。


* 步骤 *

. 在左侧导航窗格中，单击 * 主机 * 。
. 在主机页面中，单击 * 磁盘 * 。
. 从 * 主机 * 下拉列表中选择主机。
. 单击 * 新建 * 。
+
此时将打开创建磁盘向导。

. 在 LUN 名称页面上，确定 LUN ：
+
|===
| 在此字段中 ... | 执行此操作 ... 


 a| 
存储系统
 a| 
为 LUN 选择 SVM 。



 a| 
LUN 路径
 a| 
单击 * 浏览 * 以选择包含 LUN 的文件夹的完整路径。



 a| 
LUN name
 a| 
输入 LUN 的名称。



 a| 
集群大小
 a| 
选择集群的 LUN 块分配大小。

集群大小取决于操作系统和应用程序。



 a| 
LUN 标签
 a| 
或者，输入 LUN 的描述性文本。

|===
. 在磁盘类型页面上，选择磁盘类型：
+
|===
| 选择 ... | 条件 


 a| 
专用磁盘
 a| 
LUN 只能由一台主机访问。

忽略 * 资源组 * 字段。



 a| 
共享磁盘
 a| 
LUN 由 Windows Server 故障转移集群中的主机共享。

在 * 资源组 * 字段中输入集群资源组的名称。您只需要在故障转移集群中的一个主机上创建磁盘。



 a| 
集群共享卷（ CSV ）
 a| 
LUN 由使用 CSV 的 Windows Server 故障转移集群中的主机共享。

在 * 资源组 * 字段中输入集群资源组的名称。确保要创建磁盘的主机是集群组的所有者。

|===
. 在驱动器属性页面上，指定驱动器属性：
+
|===
| 属性 | Description 


 a| 
自动分配挂载点
 a| 
SnapCenter 会根据系统驱动器自动分配卷挂载点。

例如，如果系统驱动器为 C ：，则 auto assign 会在 C ：驱动器（ C ： \scmnpt\ ）下创建一个卷挂载点。共享磁盘不支持自动分配。



 a| 
分配驱动器号
 a| 
将磁盘挂载到相邻下拉列表中选择的驱动器。



 a| 
使用卷挂载点
 a| 
将磁盘挂载到相邻字段中指定的驱动器路径。

卷挂载点的根目录必须归要创建磁盘的主机所有。



 a| 
请勿分配驱动器号或卷挂载点
 a| 
如果您希望在 Windows 中手动挂载磁盘，请选择此选项。



 a| 
LUN 大小
 a| 
指定 LUN 大小；最小值为 150 MB 。

在相邻下拉列表中选择 MB ， GB 或 TB 。



 a| 
对托管此 LUN 的卷使用精简配置
 a| 
对 LUN 进行精简配置。

精简配置一次只会根据需要分配尽可能多的存储空间，从而使 LUN 能够高效地增长到最大可用容量。

确保卷上有足够的可用空间来容纳您认为需要的所有 LUN 存储。



 a| 
选择分区类型
 a| 
为 GUID 分区表选择 GPT 分区，为主启动记录选择 MBR 分区。

发生原因分区可能会在 Windows Server 故障转移集群中出现 MBR 不对齐问题。


NOTE: 不支持统一可扩展固件接口（ Unified 可扩展固件接口， UEFI ）分区磁盘。

|===
. 在映射 LUN 页面上，选择主机上的 iSCSI 或 FC 启动程序：
+
|===
| 在此字段中 ... | 执行此操作 ... 


 a| 
主机
 a| 
双击集群组名称以显示一个下拉列表，其中显示了属于集群的主机，然后选择启动程序的主机。

只有当 LUN 由 Windows Server 故障转移集群中的主机共享时，才会显示此字段。



 a| 
选择主机启动程序
 a| 
选择 * 光纤通道 * 或 * iSCSI * ，然后选择主机上的启动程序。

如果您使用的是具有多路径 I/O （ MPIO ）的 FC ，则可以选择多个 FC 启动程序。

|===
. 在组类型页面上，指定是要将现有 igroup 映射到 LUN ，还是要创建新的 igroup ：
+
|===
| 选择 ... | 条件 


 a| 
为选定启动程序创建新的 igroup
 a| 
要为选定启动程序创建新的 igroup 。



 a| 
选择一个现有 igroup 或为选定启动程序指定一个新的 igroup
 a| 
您希望为选定启动程序指定一个现有 igroup ，或者使用指定的名称创建一个新的 igroup 。

在 * igroup name* 字段中键入 igroup 名称。键入现有 igroup 名称的前几个字母以自动填写此字段。

|===
. 在摘要页面上，查看您选择的内容，然后单击 * 完成 * 。
+
SnapCenter 将创建 LUN 并将其连接到主机上的指定驱动器或驱动器路径。





== 调整磁盘大小

您可以根据存储系统需要的变化增加或减小磁盘大小。

* 关于此任务 *

* 对于精简配置的 LUN ， ONTAP LUN 几何大小显示为最大大小。
* 对于厚配置 LUN ，可扩展大小（卷中的可用大小）显示为最大大小。
* 具有 MBR 模式分区的 LUN 的大小限制为 2 TB 。
* 具有 GPT 模式分区的 LUN 的存储系统大小限制为 16 TB 。
* 最好在调整 LUN 大小之前创建 Snapshot 副本。
* 如果需要从调整 LUN 大小之前创建的 Snapshot 副本还原 LUN ， SnapCenter 会自动将 LUN 大小调整为 Snapshot 副本的大小。
+
执行还原操作后，必须从调整大小后创建的 Snapshot 副本还原在调整 LUN 大小后添加到 LUN 中的数据。



* 步骤 *

. 在左侧导航窗格中，单击 * 主机 * 。
. 在主机页面中，单击 * 磁盘 * 。
. 从主机下拉列表中选择主机。
+
此时将列出这些磁盘。

. 选择要调整大小的磁盘，然后单击 * 调整大小 * 。
. 在调整磁盘大小对话框中，使用滑块工具指定磁盘的新大小，或者在大小字段中输入新大小。
+

NOTE: 如果您手动输入大小，则需要在大小字段外单击，然后才能正确启用缩减或扩展按钮。此外，您还必须单击 MB ， GB 或 TB 以指定度量单位。

. 对输入的内容感到满意后，根据需要单击 * 缩减 * 或 * 扩展 * 。
+
SnapCenter 会调整磁盘大小。





== 连接磁盘

您可以使用连接磁盘向导将现有 LUN 连接到主机，或者重新连接已断开连接的 LUN 。

* 您需要的内容 *

* 您必须已在存储系统上启动 FC 或 iSCSI 服务。
* 如果您使用的是 iSCSI ，则必须已与存储系统建立 iSCSI 会话。
* 除非 LUN 由 Windows Server 故障转移集群中的主机共享，否则不能将 LUN 连接到多个主机。
* 如果 LUN 由使用 CSV （集群共享卷）的 Windows Server 故障转移集群中的主机共享，则必须将磁盘连接到拥有集群组的主机上。
* 适用于 Windows 的插件只需安装在要连接磁盘的主机上。


* 步骤 *

. 在左侧导航窗格中，单击 * 主机 * 。
. 在主机页面中，单击 * 磁盘 * 。
. 从 * 主机 * 下拉列表中选择主机。
. 单击 * 连接 * 。
+
此时将打开连接磁盘向导。

. 在 LUN 名称页面上，确定要连接到的 LUN ：
+
|===
| 在此字段中 ... | 执行此操作 ... 


 a| 
存储系统
 a| 
为 LUN 选择 SVM 。



 a| 
LUN 路径
 a| 
单击 * 浏览 * 以选择包含 LUN 的卷的完整路径。



 a| 
LUN name
 a| 
输入 LUN 的名称。



 a| 
集群大小
 a| 
选择集群的 LUN 块分配大小。

集群大小取决于操作系统和应用程序。



 a| 
LUN 标签
 a| 
或者，输入 LUN 的描述性文本。

|===
. 在磁盘类型页面上，选择磁盘类型：
+
|===
| 选择 ... | 条件 


 a| 
专用磁盘
 a| 
LUN 只能由一台主机访问。



 a| 
共享磁盘
 a| 
LUN 由 Windows Server 故障转移集群中的主机共享。

您只需将磁盘连接到故障转移集群中的一台主机即可。



 a| 
集群共享卷（ CSV ）
 a| 
LUN 由使用 CSV 的 Windows Server 故障转移集群中的主机共享。

确保要连接到磁盘的主机是集群组的所有者。

|===
. 在驱动器属性页面上，指定驱动器属性：
+
|===
| 属性 | Description 


 a| 
自动分配
 a| 
让 SnapCenter 根据系统驱动器自动分配卷挂载点。

例如，如果系统驱动器为 C ：，则 auto assign 属性会在 C ：驱动器（ C ： \scmnpt\ ）下创建一个卷挂载点。共享磁盘不支持自动分配属性。



 a| 
分配驱动器号
 a| 
将磁盘挂载到相邻下拉列表中选择的驱动器。



 a| 
使用卷挂载点
 a| 
将磁盘挂载到相邻字段中指定的驱动器路径。

卷挂载点的根目录必须归要创建磁盘的主机所有。



 a| 
请勿分配驱动器号或卷挂载点
 a| 
如果您希望在 Windows 中手动挂载磁盘，请选择此选项。

|===
. 在映射 LUN 页面上，选择主机上的 iSCSI 或 FC 启动程序：
+
|===
| 在此字段中 ... | 执行此操作 ... 


 a| 
主机
 a| 
双击集群组名称以显示一个下拉列表，其中显示了属于集群的主机，然后选择启动程序的主机。

只有当 LUN 由 Windows Server 故障转移集群中的主机共享时，才会显示此字段。



 a| 
选择主机启动程序
 a| 
选择 * 光纤通道 * 或 * iSCSI * ，然后选择主机上的启动程序。

如果将 FC 与 MPIO 结合使用，则可以选择多个 FC 启动程序。

|===
. 在组类型页面上，指定要将现有 igroup 映射到 LUN 还是创建新的 igroup ：
+
|===
| 选择 ... | 条件 


 a| 
为选定启动程序创建新的 igroup
 a| 
要为选定启动程序创建新的 igroup 。



 a| 
选择一个现有 igroup 或为选定启动程序指定一个新的 igroup
 a| 
您希望为选定启动程序指定一个现有 igroup ，或者使用指定的名称创建一个新的 igroup 。

在 * igroup name* 字段中键入 igroup 名称。键入现有 igroup 名称的前几个字母以自动填写此字段。

|===
. 在摘要页面上，查看所做的选择并单击 * 完成 * 。
+
SnapCenter 会将 LUN 连接到主机上的指定驱动器或驱动器路径。





== 断开磁盘连接

您可以在不影响 LUN 内容的情况下将 LUN 与主机断开连接，但有一个例外：如果在拆分克隆之前断开克隆的连接，则克隆的内容将丢失。

* 您需要的内容 *

* 确保 LUN 未被任何应用程序使用。
* 确保监控软件不会监控 LUN 。
* 如果 LUN 是共享的，请确保从 LUN 中删除集群资源依赖关系，并验证集群中的所有节点是否均已打开电源，正常运行并可供 SnapCenter 使用。


* 关于此任务 *

如果断开 SnapCenter 创建的 FlexClone 卷中的 LUN ，并且该卷上没有连接任何其他 LUN ，则 SnapCenter 会删除该卷。断开 LUN 连接之前， SnapCenter 会显示一条消息，警告您可能会删除 FlexClone 卷。

为避免自动删除 FlexClone 卷，应在断开最后一个 LUN 的连接之前重命名此卷。重命名卷时，请确保更改多个字符，而不仅仅是名称中的最后一个字符。

* 步骤 *

. 在左侧导航窗格中，单击 * 主机 * 。
. 在主机页面中，单击 * 磁盘 * 。
. 从 * 主机 * 下拉列表中选择主机。
+
此时将列出这些磁盘。

. 选择要断开连接的磁盘，然后单击 * 断开连接 * 。
. 在断开磁盘连接对话框中，单击 * 确定 * 。
+
SnapCenter 将断开磁盘连接。





== 删除磁盘

您可以删除不再需要的磁盘。删除磁盘后，您将无法取消删除该磁盘。

* 步骤 *

. 在左侧导航窗格中，单击 * 主机 * 。
. 在主机页面中，单击 * 磁盘 * 。
. 从 * 主机 * 下拉列表中选择主机。
+
此时将列出这些磁盘。

. 选择要删除的磁盘，然后单击 * 删除 * 。
. 在删除磁盘对话框中，单击 * 确定 * 。
+
SnapCenter 将删除该磁盘。


