---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: 您可以配置以记录软件平台以及这些平台上运行的所有软件的安全事件。 
---
= 配置审核日志设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系统会为SnapCenter 服务器的每个活动生成审核日志。默认情况下、审核日志会在默认安装位置_C：\Program Files\NetApp\SnapCenter WebApp\audit中受到保护。

通过为每个审核事件生成数字签名摘要来保护审核日志、防止未经授权的修改。生成的摘要保存在单独的审核校验和文件中、并定期进行完整性检查以确保内容的完整性。

您应已以 "SnapCenterAdmin" 角色登录。

* 关于此任务 *

* 在以下情况下会发送警报：
+
** 已启用或禁用审核日志完整性检查计划或系统日志服务器
** 审核日志完整性检查、审核日志或系统日志服务器日志失败
** 磁盘空间不足


* 只有在完整性检查失败时、才会发送电子邮件。
* 您应同时修改审核日志目录和审核校验和日志目录路径。您不能仅修改其中一个。
* 修改审核日志目录和审核校验和日志目录路径后、无法对早期位置的审核日志执行完整性检查。
* 审核日志目录和审核校验和日志目录路径应位于SnapCenter 服务器的本地驱动器上。
+
不支持共享驱动器或网络挂载驱动器。

* 如果在系统日志服务器设置中使用UDP协议、则由于端口关闭或不可用而导致的错误无法在SnapCenter 中捕获为错误或警报。
* 您可以使用Set-SmAudit设置和Get-SmAudit设置命令配置审核日志。
+
有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 get-help command_name 来获取。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《 SnapCenter 软件 cmdlet 参考指南》"^]。



* 步骤 *

. 在*设置*页面中、导航到*设置*>*全局设置*>*审核日志设置*。
. 在Audit log部分中、输入详细信息。
. 输入*审核日志目录*和*审核校验和日志目录*
+
.. 输入最大文件大小
.. 输入最大日志文件数
.. 输入要发送警报的磁盘空间使用量百分比


. (可选)启用*记录UTC时间*。
. (可选)启用*审核日志完整性检查计划*并单击*启动完整性检查*以进行按需完整性检查。
+
您还可以运行*启动-小型审核集成检查*命令来启动按需完整性检查。

. (可选)启用转发到远程系统日志服务器的审核日志并输入系统日志服务器详细信息。
+
您应将证书从系统日志服务器导入到TLS 1.2协议的"可信根"中。

+
.. 输入系统日志服务器主机
.. 输入系统日志服务器端口
.. 输入系统日志服务器协议
.. 输入RFC格式


. 单击 * 保存 * 。
. 您可以通过单击*监控*>*作业*来查看审核完整性检查和磁盘空间检查。

