---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: 在添加主机并安装插件软件包之前，您必须满足所有要求。 
---
= 添加主机和安装适用于Linux的插件软件包的前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在添加主机并安装适用于Linux的插件软件包之前、您必须满足所有要求。

* 如果使用的是 iSCSI ，则 iSCSI 服务必须正在运行。
* 您可以对root用户或非root用户使用基于密码的身份验证、也可以使用基于SSH密钥的身份验证。
+
非root用户可以安装适用于Unix文件系统的SnapCenter插件。但是，您应该为非 root 用户配置 sudo 权限，以便安装和启动插件过程。安装此插件后、这些进程将以有效的非root用户身份运行。

* 为安装用户创建身份验证模式为Linux的凭据。
* 您必须已在Linux主机上安装Java 11。
+

NOTE: 确保在Linux主机上仅安装了经过认证的Java 11版本。

+
有关下载 Java 的信息，请参见： http://www.java.com/en/download/manual.jsp["适用于所有操作系统的 Java 下载"^]

* 您应将*bash*用作插件安装的默认shell。




== Linux 主机要求

在安装适用于 Linux 的 SnapCenter 插件软件包之前，应确保主机满足要求。

|===
| 项目 | 要求 


 a| 
操作系统
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server （ SLES ）




 a| 
主机上 SnapCenter 插件的最小 RAM
 a| 
2 GB



 a| 
主机上 SnapCenter 插件的最小安装和日志空间
 a| 
2 GB


NOTE: 您应分配足够的磁盘空间并通过 logs 文件夹监控存储消耗。所需的日志空间因要保护的实体数量和数据保护操作的频率而异。如果没有足够的磁盘空间，则不会为最近运行的操作创建日志。



 a| 
所需的软件包
 a| 
Java 11 Oracle Java和OpenJDK


NOTE: 确保在Linux主机上仅安装了经过认证的Java 11版本。

如果已将 Java 升级到最新版本，则必须确保 /var/opt/snapcenter/spl/etc/spl.properties 上的 java_home 选项设置为正确的 Java 版本和路径。

|===
有关受支持版本的最新信息、请参见 https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT[][ NetApp互操作性表工具^]。
