---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: 为要备份的Unix文件系统创建一个备份策略。 
---
= 为Unix文件系统创建备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter备份Unix文件系统之前、您必须为要备份的资源或资源组创建备份策略。备份策略是一组规则，用于控制如何管理，计划和保留备份。您还可以指定复制，脚本和备份类型设置。如果要在其他资源或资源组上重复使用策略，则创建策略可节省时间。

.开始之前
* 您必须已完成安装SnapCenter、添加主机、发现文件系统和创建存储系统连接等任务、为数据保护做好准备。
* 如果要将快照复制到镜像或存储二级存储、则SnapCenter管理员必须已为源卷和目标卷分配SVM。
* 查看SnapMirror主动同步的特定前提条件和限制。有关信息，请参阅 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror活动同步的对象限制"]。


.步骤
. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 策略 * 。
. 从下拉列表中选择*Unix文件系统*。
. 单击 * 新建 * 。
. 在名称页面中，输入策略名称和问题描述。
. 通过选择 * 按需 * ， * 每小时 * ， * 每日 * ， * 每周 * 或 * 每月 * 来指定计划频率。
. 在保留页面中，指定备份类型的保留设置以及在备份类型页面中选择的计划类型：
+
|===


| 如果您要 ... | 那么 ... 


 a| 
保留一定数量的快照
 a| 
选择*要保留的Snapshot副本总数*、然后指定要保留的Snapshot数量。

如果快照数量超过指定数量、则会删除快照、并首先删除最早的副本。


NOTE: 对于 ONTAP 9.4 或更高版本上的资源，最大保留值为 1018 ，对于 ONTAP 9.3 或更早版本上的资源，最大保留值为 254 。如果将保留设置为高于底层 ONTAP 版本支持的值，则备份将失败。


IMPORTANT: 如果计划启用 SnapVault 复制，则必须将保留计数设置为 2 或更高。如果将保留计数设置为1、则保留操作可能会失败、因为第一个快照是SnapVault关系的参考快照、直到将较新的快照复制到目标为止。



 a| 
将Snapshot保留一定天数
 a| 
选择*保留Snapshot副本的时间*、然后指定要在删除快照之前保留这些快照的天数。

|===
+

NOTE: 只有在备份过程中选择了归档日志文件时，才能保留归档日志备份。

. 在复制页面中，指定复制设置：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
创建本地 Snapshot 副本后更新 SnapMirror
 a| 
选择此字段可在另一个卷上创建备份集的镜像副本（ SnapMirror 复制）。

对于SnapMirror活动同步、应启用此选项。



 a| 
创建本地 Snapshot 副本后更新 SnapVault
 a| 
选择此选项可执行磁盘到磁盘备份复制（ SnapVault 备份）。



 a| 
二级策略标签
 a| 
选择 Snapshot 标签。

根据您选择的Snapshot标签、ONTAP会应用与该标签匹配的二级Snapshot保留策略。


NOTE: 如果选择了 * 创建本地 Snapshot 副本后更新 Snapmirror* ，则可以选择指定二级策略标签。但是，如果在创建本地 Snapshot 副本之后选择了 * 更新 SnapVault * ，则应指定二级策略标签。



 a| 
错误重试次数
 a| 
输入操作停止前允许的最大复制尝试次数。

|===
+

NOTE: 您应在ONTAP中为二级存储配置SnapMirror保留策略、以避免达到二级存储上Snapshot的最大限制。

. 在脚本页面中，分别输入要在备份操作之前或之后运行的预处理或后处理的路径和参数。
+

NOTE: 您应通过以下路径检查插件主机上的命令列表中是否存在这些命令：_/opt/NetApp/snapcentre/SCC//etc/ALLOED_commands.config_。

+
您还可以指定脚本超时值。默认值为 60 秒。

. 查看摘要，然后单击 * 完成 * 。

