---
permalink: protect-db2/prerequisites-to-adding-hosts-and-installing-snapcenter-plug-in-for-ibm-db2.html 
sidebar: sidebar 
keywords: credentials, Windows, Linux, AIX 
summary: 在添加主机并安装插件软件包之前，您必须满足所有要求。适用于IBM DB2的SnapCenter插件在Windows、Linux和AIX环境中受支持。 
---
= 添加主机和安装适用于Windows、Linux或AIX的插件软件包的前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在添加主机并安装插件软件包之前，您必须满足所有要求。适用于IBM DB2的SnapCenter插件在Windows、Linux和AIX环境中受支持。

* 您必须已在主机上安装Java 11。
+

NOTE: IBM Java 在 Windows 和 Linux 主机上不受支持。

* 对于Windows、插件Creator Service应使用"`LocalSystem`" Windows用户运行、这是以域管理员身份安装适用于IBM DB2的插件时的默认行为。
* 在 Windows 主机上安装插件时，如果您指定的凭据不是内置的，或者用户属于本地工作组用户，则必须在主机上禁用 UAC 。默认情况下、适用于Microsoft Windows的SnapCenter插件将与IBM DB2插件一起部署在Windows主机上。
* SnapCenter服务器应有权访问IBM DB2主机的插件的8145或自定义端口。




== Windows 主机

* 您必须具有具有本地管理员权限的域用户，并在远程主机上具有本地登录权限。
* 在Windows主机上安装适用于IBM DB2的插件时、会自动安装适用于Microsoft Windows的SnapCenter插件。
* 您必须已为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须已在Windows主机上安装Java 11。
+
http://www.java.com/en/download/manual.jsp["下载适用于 Windows 的 JAVA"]





== Linux和AIX主机

* 您必须已为 root 用户或非 root 用户启用基于密码的 SSH 连接。
* 您必须已在Linux主机上安装Java 11。
+
http://www.java.com/en/download/manual.jsp["下载适用于 Linux 的 JAVA"]

+
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?license=IBM["下载适用于 AIX 的 JAVA"]

* 对于在Linux主机上运行的IBM DB2数据库、在安装适用于IBM DB2的插件时、系统会自动安装适用于UNIX的SnapCenter插件。
* 您应将*bash*用作插件安装的默认shell。




== 补充命令

要在适用于IBM DB2的SnapCenter插件上运行补充命令、必须将其包含在_ALLOED_commands.config_文件中。

* Windows主机上的默认位置：_C：\Program NetApp SnapCenter SnapCenter Plug-in Creper\ETC\Allowed_commands.config_
* Linux主机上的默认位置：/opt/linux/linux/SCC//etc/Allowed_commands.config_ NetApp SnapCenter


要在插件主机上使用补充命令、请在编辑器中打开_ALLOED_commands.config_文件。在单独的行中输入每个命令、这些命令不区分大小写。请确保指定完全限定路径名、如果路径名包含空格、请将其用引号(")括起来。

例如：

命令：mount

命令：umount

命令："C：\Program Files\NetApp\SnapCreator commands\sdcli.exe"

命令：myscript.bat

如果_ALLOED_commands.config_文件不存在、则命令或脚本执行将被阻止、并且工作流将失败并显示以下错误：

"[/mnt/mount -a]不允许执行。通过在插件主机上的文件%s中添加命令进行授权。"

如果_ALLOED_commands.config_中不存在命令或脚本、则命令或脚本执行将被阻止、并且工作流将失败并显示以下错误：

"[/mnt/mount -a]不允许执行。通过在插件主机上的文件%s中添加命令进行授权。"


NOTE: 不应使用通配符条目(*)来允许所有命令。



== 为 Linux 主机的非 root 用户配置 sudo 权限

SnapCenter允许非root用户安装适用于Linux的SnapCenter插件软件包并启动插件进程。此插件进程将以有效的非root用户身份运行。您应为非 root 用户配置 sudo 权限，以提供对多个路径的访问权限。

* 您需要的内容 *

* sudo 1.8.7或更高版本。
* 如果umask为0027、请确保Java文件夹和其中的所有文件都具有555的权限。否则、插件安装可能会失败。
* 对于非root用户、请确保非root用户的名称和用户组的名称应相同。
* 编辑 /etc/ssh/sshd_config_ 文件以配置消息身份验证代码算法： macs HMAC-SHA2-256 和 MAC HMAC-SHA2-512 。
+
更新配置文件后重新启动 sshd 服务。

+
示例

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


* 关于此任务 *

您应为非 root 用户配置 sudo 权限，以提供对以下路径的访问：

* /home/_Linux_user_//.SC_NetApp/snapcenter_linux_host_plugin.bin
* /custom_location/netapp/snapcenter/spl/installation/plugins/uninstall
* /custom_location/netapp/snapcenter/spl/bin/spl


* 步骤 *

. 登录到要安装适用于 Linux 的 SnapCenter 插件软件包的 Linux 主机。
. 使用 visudo Linux 实用程序将以下行添加到 /etc/sudoers 文件中。
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+

NOTE: 如果您正在设置RAC以及其他允许的命令、则应将以下命令添加到/etc/sudoers文件中："/rc/bin/olsnodes'<crs_home>



您可以从/etc/oracle/ocl.loc_文件中获取_crs_home_的值。

_linux_user_是 您创建的非root用户的名称。

您可以从*SC_UNIX)插件校验和.txt文件获取_校 验和值_，该文件位于：

* _C：\ProgramData\NetApp\SnapCenter\Package Repository \SC_UNIS_plugins_校 验和.TXT_(如果SnapCenter服务器安装在Windows主机上)。
* _/opt/NetApp/snapcentre/SnapManagerWeb/Repository /SC_UNIX)插件_Checksum．txt _(如果SnapCenter服务器安装在Linux主机上)。



IMPORTANT: 此示例只能用作创建自己数据的参考。



== 为 AIX 主机的非 root 用户配置 sudo 权限

通过 SnapCenter 4.4 及更高版本，非 root 用户可以安装适用于 AIX 的 SnapCenter 插件软件包并启动插件过程。此插件进程将以有效的非root用户身份运行。您应为非 root 用户配置 sudo 权限，以提供对多个路径的访问权限。

* 您需要的内容 *

* sudo 1.8.7或更高版本。
* 如果umask为0027、请确保Java文件夹和其中的所有文件都具有555的权限。否则、插件安装可能会失败。
* 编辑 /etc/ssh/sshd_config_ 文件以配置消息身份验证代码算法： macs HMAC-SHA2-256 和 MAC HMAC-SHA2-512 。
+
更新配置文件后重新启动 sshd 服务。

+
示例

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


* 关于此任务 *

您应为非 root 用户配置 sudo 权限，以提供对以下路径的访问：

* /home/_aix_user_//.SC_NetApp/snapcenter_aix_host_plugin.bsx
* /custom_location/netapp/snapcenter/spl/installation/plugins/uninstall
* /custom_location/netapp/snapcenter/spl/bin/spl


* 步骤 *

. 登录到要安装适用于 AIX 的 SnapCenter 插件软件包的 AIX 主机。
. 使用 visudo Linux 实用程序将以下行添加到 /etc/sudoers 文件中。
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+

NOTE: 如果您正在设置RAC以及其他允许的命令、则应将以下命令添加到/etc/sudoers文件中："/rc/bin/olsnodes'<crs_home>



您可以从/etc/oracle/ocl.loc_文件中获取_crs_home_的值。

_aix_user_是 您创建的非 root 用户的名称。

您可以从*SC_UNIX)插件校验和.txt文件获取_校 验和值_，该文件位于：

* _C：\ProgramData\NetApp\SnapCenter\Package Repository \SC_UNIS_plugins_校 验和.TXT_(如果SnapCenter服务器安装在Windows主机上)。
* _/opt/NetApp/snapcentre/SnapManagerWeb/Repository /SC_UNIX)插件_Checksum．txt _(如果SnapCenter服务器安装在Linux主机上)。



IMPORTANT: 此示例只能用作创建自己数据的参考。
