---
permalink: protect-nsp/create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: credentials 
summary: 在使用PowerShell cmdlet执行数据保护操作之前、您必须先创建存储系统连接和凭据。 
---
= 使用 PowerShell cmdlet 创建存储系统连接和凭据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 PowerShell cmdlet 执行数据保护操作之前，您必须创建 Storage Virtual Machine （ SVM ）连接和凭据。

.开始之前
* 您应已准备好 PowerShell 环境以执行 PowerShell cmdlet 。
* 您应具有创建存储连接所需的基础架构管理员角色权限。
* 您应确保插件安装未在进行中。
+
添加存储系统连接时，主机插件安装不得正在进行中，因为主机缓存可能不会更新，并且数据库状态可能会在 SnapCenter 图形用户界面中显示为 "`不可用于备份` " 或 "`不在 NetApp 存储` 上 " 。

* 存储系统名称应是唯一的。
+
SnapCenter 不支持在不同集群上使用相同名称的多个存储系统。SnapCenter 支持的每个存储系统都应具有唯一的名称和唯一的管理 LIF IP 地址。



.步骤
. 使用Open-SmConnection cmdlet启动PowerShell Core连接会话。
+
此示例将打开 PowerShell 会话：

+
[listing]
----
PS C:\> Open-SmConnection
----
. 使用 Add-SmStorageConnection cmdlet 创建与存储系统的新连接。
+
此示例将创建一个新的存储系统连接：

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. 使用 Add-SmCredential cmdlet 创建新凭据。
+
此示例将使用 Windows 凭据创建一个名为 FinanceAdmin 的新凭据：

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


有关可与 cmdlet 结合使用的参数及其说明的信息，可通过运行 _get-help command_name_ 来获取。或者，您也可以参考 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["《 SnapCenter 软件 cmdlet 参考指南》"^]。
