---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: 凭据使用不同的身份验证方法，具体取决于应用程序或环境。凭据用于对用户进行身份验证，以便用户可以执行 SnapCenter 操作。您应创建一组用于安装插件的凭据，并创建另一组用于数据保护操作的凭据。 
---
= SnapCenter凭据的身份验证方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
凭据使用不同的身份验证方法、具体取决于应用程序或环境。凭据用于对用户进行身份验证，以便用户可以执行 SnapCenter 操作。您应创建一组凭据来安装插件、而创建另一组凭据来执行数据保护操作。



== Windows 身份验证

Windows 身份验证方法根据 Active Directory 进行身份验证。对于 Windows 身份验证， Active Directory 是在 SnapCenter 之外设置的。SnapCenter 无需进行额外配置即可进行身份验证。要添加主机、安装插件软件包和计划作业、您需要Windows凭据。



== 不可信域身份验证

SnapCenter允许属于不可信域的用户和组创建Windows凭据。要成功进行身份验证，您应向 SnapCenter 注册不可信域。



== 本地工作组身份验证

SnapCenter 允许使用本地工作组用户和组创建 Windows 凭据。本地工作组用户和组的Windows身份验证不会在创建Windows凭据期间进行、而是会延迟到执行主机注册和其他主机操作后再进行。



== SQL Server 身份验证

SQL 身份验证方法针对 SQL Server 实例进行身份验证。这意味着必须在 SnapCenter 中发现 SQL Server 实例。因此，在添加 SQL 凭据之前，您必须添加主机，安装插件软件包并刷新资源。要执行诸如在SQL Server上计划或发现资源等操作、您需要使用SQL Server身份验证。



== Linux 身份验证

Linux 身份验证方法可针对 Linux 主机进行身份验证。在从 SnapCenter 图形用户界面远程添加 Linux 主机和安装适用于 Linux 的 SnapCenter 插件软件包的初始步骤中，您需要进行 Linux 身份验证。



== AIX 身份验证

AIX 身份验证方法可针对 AIX 主机进行身份验证。在从 SnapCenter 图形用户界面远程添加 AIX 主机和安装适用于 AIX 的 SnapCenter 插件软件包的初始步骤中，您需要 AIX 身份验证。



== Oracle 数据库身份验证

Oracle 数据库身份验证方法可针对 Oracle 数据库进行身份验证。如果在数据库主机上禁用了操作系统（ OS ）身份验证，则需要使用 Oracle 数据库身份验证对 Oracle 数据库执行操作。因此、在添加Oracle数据库凭据之前、您应使用sysdba Privileges在Oracle数据库中创建一个Oracle用户。



== Oracle ASM 身份验证

Oracle ASM 身份验证方法可针对 Oracle 自动存储管理（ Automatic Storage Management ， ASM ）实例进行身份验证。如果您需要访问Oracle ASM实例、并且数据库主机上已禁用操作系统身份验证、则需要进行Oracle ASM身份验证。在添加Oracle ASM凭据之前、请在ASM实例中使用系统Privileges创建一个Oracle用户。



== RMAN 目录身份验证

RMAN 目录身份验证方法根据 Oracle Recovery Manager （ RMAN ）目录数据库进行身份验证。如果您已配置外部目录机制并将数据库注册到目录数据库，则需要添加 RMAN 目录身份验证。
