---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: 在使用 SnapCenter 之前，了解与要执行的备份，克隆和还原操作相关的基本概念非常有用。 
---
= 数据保护的关键概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter之前、请了解有关备份、克隆和还原的重要概念。



== Resources

资源包括使用SnapCenter备份或克隆的数据库、Windows文件系统或文件共享。根据您的环境、资源可能还包括数据库实例、SQL Server可用性组、Oracle数据库、RAC数据库或自定义应用程序组。



== Resource group

资源组是主机或集群上的一组资源、可能来自多个主机和集群。根据指定的计划、对资源组执行的操作将应用于其所有资源。您可以对单个资源或组执行按需或计划备份。


NOTE: 如果共享资源组中的一台主机进入维护模式、则该组的所有计划操作都将在所有主机上暂停。

使用相关插件备份特定资源：适用于数据库的数据库插件、适用于文件系统的文件系统插件以及适用于VMware vSphere的VM和数据存储库SnapCenter插件。



== 策略

策略用于指定数据保护操作的备份频率、副本保留、复制、脚本和其他特征。

创建资源组或执行按需备份时、可以选择一个或多个策略。

资源组定义了需要保护的内容以及保护时间。策略用于说明如何执行保护。例如、如果需要备份主机的所有数据库或文件系统、则可以创建一个资源组、其中包含主机中的所有数据库或文件系统。然后、可以将两个策略附加到资源组：每日策略和每小时策略。

创建资源组并附加策略时、可以将其配置为每天执行完整备份、并为日志备份创建另一个计划、该计划为每小时执行一次。

自定义的前处理脚本和后处理脚本可用于数据保护操作。通过这些脚本、可以在执行数据保护作业之前或之后实现自动化。例如、脚本可以自动通知数据保护作业失败或出现警告。在设置脚本和后处理脚本之前、了解创建这些脚本的要求至关重要。



== 前处理脚本和后处理脚本的使用

自定义的前处理脚本和后处理脚本可以在作业之前或之后自动执行数据保护任务。例如、您可以添加一个脚本、用于在作业失败或出现警告时向您发出通知。在设置这些脚本之前、请确保您了解这些脚本的要求。



=== 支持的脚本类型

Windows支持以下类型的脚本：

* 批处理文件
* PowerShell 脚本
* Perl 脚本


UNIX支持以下类型的脚本：

* Perl 脚本
* Python脚本
* Shell脚本
+

NOTE: 除了默认的bash shell之外、还支持其他shell、例如sh-shell、k-shell和c-shell。





=== 脚本路径

在非虚拟化和虚拟化存储系统上作为SnapCenter操作的一部分运行的所有前处理脚本和后处理脚本都在插件主机上执行。

* Windows脚本应位于插件主机上。



NOTE: 预处理脚本或后处理脚本路径不应包含驱动器或共享。路径应与scripts_path相关。

* UNIX脚本应位于插件主机上。



NOTE: 脚本路径会在执行时进行验证。



=== 指定脚本的位置

脚本在备份策略中指定。备份作业启动时、策略会自动将脚本与要备份的资源关联起来。创建备份策略时，您可以指定 prestpt 和 postScript 参数。


NOTE: 您不能指定多个脚本。



=== 脚本超时

默认情况下、超时设置为60秒。您可以修改超时值。



=== 脚本输出

Windows预处理和后处理脚本输出文件的默认目录为Windows\System32。

UNIX预处理和后处理脚本没有默认位置。您可以将输出文件重定向到任何首选位置。
