---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: SnapCenter软件6.0版包括几项新功能和增强功能。 
---
= SnapCenter软件6.0中的新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter软件6.0版包括几项新功能和增强功能。

|===
| 更新 | Description 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["支持企业级工作负载插件并支持NetApp"]  a| 
SnapCenter提供了一些插件来管理PostgreSQL、MySQL和IBM DB2等工作负载。您可以自动发现、备份、还原、挂载和克隆工作负载。

SnapCenter还提供了一些插件来管理SAP ASE、SAP MaxDB、MongoDB、Oracle应用程序和ONTAP存储等工作负载。您可以备份、还原和克隆工作负载。



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["支持在云和内部工作负载中使用Linux版本的SnapCenter"]  a| 
* 支持Azure NetApp Files、Amazon FSx for NetApp ONTAP、Cloud Volumes ONTAP和ONTAP存储。
* 适用于Red Hat Enterprise Linux (RHEL)、Oracle Linux和SUSE Linux Enterprise Server (SLES)等Linux模式的单独二进制文件。
* 支持SAP HANA、Oracle、IBM DB2、SAP ASE、SAP MaxDB等经典数据库。
* 支持PostgreSQL、MySQL和MongoDB等现代工作负载。
* 支持用于ONTAP卷和Linux文件系统的插件、用于保护任何不受支持的或自行开发的应用程序。




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["支持SnapMirror活动同步"]  a| 
能够无缝备份、还原和克隆SAN工作负载(数据库和VMware VM)、这些工作负载配置用于透明的应用程序故障转移和业务连续性。



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["通过SMB3支持Microsoft SQL Server"]  a| 
现在、在ONTAP、Azure NetApp Files、Amazon FSx for NetApp ONTAP和ONTAP云卷中基于SMB3协议部署的Microsoft SQL Server数据库可以使用SnapCenter进行保护。



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["支持NVMe/TCP"]  a| 
如果要将关键工作负载迁移到NVMe/TCP以提高性能、则可以使用SnapCenter备份和恢复应用程序和文件系统。



| 支持VMware vvol  a| 
如果您已在VMware vvol上部署数据库和文件系统、则可以使用SnapCenter对其进行保护。

|===