---
permalink: protect-mysql/create-backup-policies-for-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: 在使用SnapCenter备份MySQL数据库资源之前、您必须为要备份的资源或资源组创建一个备份策略。备份策略是一组规则，用于控制如何管理，计划和保留备份。 
---
= 为MySQL创建备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用SnapCenter备份MySQL资源之前、您必须为要备份的资源或资源组创建一个备份策略。备份策略是一组规则，用于控制如何管理，计划和保留备份。

.开始之前
* 您必须已定义备份策略。
+
有关详细信息、请参见有关为MySQL数据库定义数据保护策略的信息。

* 您必须已通过完成安装 SnapCenter ，添加主机，设置存储系统连接和添加资源等任务为数据保护做好准备。
* 如果要将快照复制到镜像或存储、SnapCenter管理员必须已将源卷和目标卷的SVM分配给您。
+
此外，您还可以在策略中指定复制，脚本和应用程序设置。如果要将策略重复用于其他资源组，这些选项可节省时间。



.关于此任务
* SnapLock
+
** 如果选择了"将备份副本保留特定天数"选项、则SnapLock保留期限必须小于或等于上述保留天数。
** 指定快照锁定期限可防止删除快照、直到保留期限到期为止。这样可能会保留比策略中指定的数量更多的快照。
** 对于ONTAP 9.12.1及更低版本、在还原过程中从SnapLock存储快照创建的克隆将继承SnapLock存储到期时间。存储管理员应在SnapLock到期时间后手动清理克隆。




.步骤
. 在左侧导航窗格中，单击 * 设置 * 。
. 在设置页面中，单击 * 策略 * 。
. 单击 * 新建 * 。
. 在名称页面中、输入策略名称和详细信息。
. 在策略类型页面中、执行以下操作：
+
.. 选择存储类型。
.. 在自定义备份设置部分中、以键值格式提供必须传递到此插件的任何特定备份设置。
+
您可以提供多个要传递到插件的密钥值。



. 在Snapshot and Replication页面中、执行以下步骤：
+
.. 通过选择 * 按需 * ， * 每小时 * ， * 每日 * ， * 每周 * 或 * 每月 * 来指定计划类型。
+

NOTE: 您可以在创建资源组时为备份操作指定计划（开始日期，结束日期和频率）。这样，您可以创建共享相同策略和备份频率的资源组，但可以为每个策略分配不同的备份计划。

+

NOTE: 如果您已计划凌晨 2 ： 00 ，则在夏令时（ DST ）期间不会触发此计划。

.. 在Snapshot设置部分中，指定在*Backup Type*页面中选择的备份类型和计划类型的保留设置：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
保留一定数量的快照
 a| 
选择*要保留的副本*，然后指定要保留的快照数。

如果快照数量超过指定数量、则会删除快照、并首先删除最早的副本。


NOTE: 如果计划启用 SnapVault 复制，则必须将保留计数设置为 2 或更高。如果将保留计数设置为1、则保留操作可能会失败、因为第一个快照是SnapVault关系的参考快照、直到将较新的快照复制到目标为止。


NOTE: 最大保留值为1018。如果将保留设置为高于底层 ONTAP 版本支持的值，则备份将失败。



 a| 
将Snapshot保留一定天数
 a| 
选择*保留副本时间*、然后指定要在删除快照之前保留这些快照的天数。



 a| 
快照副本锁定期
 a| 
选择*Snapshot 副本锁定期限*，并指定天、月或年。

SnapLock保留期限应少于100年。

|===
.. 选择策略标签。
+

NOTE: 您可以为远程复制的主快照分配SnapMirror标签，从而允许主快照将快照复制操作从SnapCenter卸载到ONTAP二级系统。无需在策略页面中启用SnapMirror或SnapVault选项即可完成此操作。



. 在选择二级复制选项部分中、选择以下一个或两个二级复制选项：
+
|===
| 对于此字段 ... | 执行此操作 ... 


 a| 
* 创建本地 Snapshot 副本后更新 SnapMirror *
 a| 
选择此字段可在另一个卷上创建备份集的镜像副本（ SnapMirror 复制）。

如果ONTAP中的保护关系类型为"镜像和存储"、而您仅选择此选项、则在主系统上创建的快照不会传输到目标系统、而是会在目标系统中列出。如果从目标中选择此Snapshot来执行还原操作、则会显示以下错误消息：Secondary Location is not available for the selected vauled/Mirrored backup。

在二级复制期间、SnapLock到期时间会加载主SnapLock到期时间。

单击"Topology"页面中的*Refresh*按钮可刷新从ONTAP检索到的二级和主SnapLock到期时间。

请参阅。 link:view-mysql-database-backups-and-clones-in-the-topology-page.html["在Topology页面中查看MySQL资源相关的备份和克隆"]



 a| 
* 创建本地 Snapshot 副本后更新 SnapVault *
 a| 
选择此选项可执行磁盘到磁盘备份复制（ SnapVault 备份）。

在二级复制期间、SnapLock到期时间会加载主SnapLock到期时间。单击"Topology"页面中的*Refresh*按钮可刷新从ONTAP检索到的二级和主SnapLock到期时间。

如果仅在ONTAP中称为SnapLock存储的二级系统上配置了SnapLock，则单击“拓扑”页面中的*Refresh*按钮可刷新从ONTAP检索到的二级系统上的锁定期限。

有关SnapLock存储的详细信息、请参见将快照提交到存储上的WORM
destination

请参阅。 link:view-mysql-database-backups-and-clones-in-the-topology-page.html["在Topology页面中查看MySQL资源相关的备份和克隆"]



 a| 
* 错误重试计数 *
 a| 
输入操作停止前允许的最大复制尝试次数。

|===
+

NOTE: 您应在ONTAP中为二级存储配置SnapMirror保留策略、以避免达到二级存储上Snapshot的最大限制。

. 查看摘要，然后单击 * 完成 * 。

